export interface PracticeQuestion {
  id: string;
  questionText: string;
  options: string[];
  correctIndex: number;
  unit: number;
}

export interface BeginnerQuiz {
  id: number;
  title: string;
  subtitle: string;
  units: number[];
  label: string;
}

export const BEGINNER_QUIZZES: BeginnerQuiz[] = [
  { id: 1, title: "Quiz 1", subtitle: "Hello & Introductions", units: [1, 2, 3], label: "Units 1–3" },
  { id: 2, title: "Quiz 2", subtitle: "Family & Daily Life",   units: [4, 5, 6], label: "Units 4–6" },
  { id: 3, title: "Quiz 3", subtitle: "Shopping & The Past",   units: [7, 8, 9], label: "Units 7–9" },
  { id: 4, title: "Quiz 4", subtitle: "Past Simple & Abilities", units: [10, 11], label: "Units 10–11" },
  { id: 5, title: "Quiz 5", subtitle: "Present & Future",      units: [12, 13, 14], label: "Units 12–14" },
];

const questions: PracticeQuestion[] = [
  // ── Unit 1 – Greetings & am/is/are ───────────────────────────────────────
  { id: "u1q1", unit: 1,
    questionText: "Hello, ___ name's Anna. What's your name?",
    options: ["Your", "My", "You", "I"], correctIndex: 1 },
  { id: "u1q2", unit: 1,
    questionText: "Hi, how ___ you?",
    options: ["is", "am", "are", "be"], correctIndex: 2 },
  { id: "u1q3", unit: 1,
    questionText: "This ___ a book.",
    options: ["am", "are", "is", "be"], correctIndex: 2 },
  { id: "u1q4", unit: 1,
    questionText: "Pierre, this is Yukio. Yukio, ___ Pierre.",
    options: ["is this", "this is", "this", "is"], correctIndex: 1 },
  { id: "u1q5", unit: 1,
    questionText: "Hello. I ___ Sandra.",
    options: ["is", "are", "am", "be"], correctIndex: 2 },
  { id: "u1q6", unit: 1,
    questionText: "What ___ your name?",
    options: ["am", "is", "are", "be"], correctIndex: 1 },
  { id: "u1q7", unit: 1,
    questionText: "A: 'How are you?' B: 'Fine, ___ .'",
    options: ["please", "thanks", "sorry", "pardon"], correctIndex: 1 },
  { id: "u1q8", unit: 1,
    questionText: "A: 'What's this in English?' B: '___ 's a pen.'",
    options: ["A", "Is", "It", "This"], correctIndex: 2 },

  // ── Unit 2 – Countries & nationalities ───────────────────────────────────
  { id: "u2q1", unit: 2,
    questionText: "Where are you ___?",
    options: ["at", "from", "in", "of"], correctIndex: 1 },
  { id: "u2q2", unit: 2,
    questionText: "Tokyo is ___ Japan.",
    options: ["from", "at", "on", "in"], correctIndex: 3 },
  { id: "u2q3", unit: 2,
    questionText: "His name's Massimo. ___ from Italy.",
    options: ["She's", "They're", "He's", "I'm"], correctIndex: 2 },
  { id: "u2q4", unit: 2,
    questionText: "Where's London? ___ in England.",
    options: ["He's", "She's", "They're", "It's"], correctIndex: 3 },
  { id: "u2q5", unit: 2,
    questionText: "Barcelona is in ___.",
    options: ["France", "Italy", "Spain", "Brazil"], correctIndex: 2 },
  { id: "u2q6", unit: 2,
    questionText: "Paris is in ___.",
    options: ["Italy", "France", "Spain", "Japan"], correctIndex: 1 },
  { id: "u2q7", unit: 2,
    questionText: "She's from Argentina. Where ___ she from?",
    options: ["am", "are", "is", "be"], correctIndex: 2 },
  { id: "u2q8", unit: 2,
    questionText: "They're from the United States. Where ___ they from?",
    options: ["am", "is", "be", "are"], correctIndex: 3 },

  // ── Unit 3 – Negatives, short answers, jobs ───────────────────────────────
  { id: "u3q1", unit: 3,
    questionText: "He's from France. He ___ from France.",
    options: ["aren't", "isn't", "not", "am not"], correctIndex: 1 },
  { id: "u3q2", unit: 3,
    questionText: "Is she a nurse? No, ___ isn't.",
    options: ["he", "I", "she", "they"], correctIndex: 2 },
  { id: "u3q3", unit: 3,
    questionText: "Are you from England? Yes, I ___.",
    options: ["is", "be", "am", "are"], correctIndex: 2 },
  { id: "u3q4", unit: 3,
    questionText: "How ___ are you? I'm 31.",
    options: ["much", "many", "old", "where"], correctIndex: 2 },
  { id: "u3q5", unit: 3,
    questionText: "You're 23. You ___ 23.",
    options: ["isn't", "am not", "aren't", "not are"], correctIndex: 2 },
  { id: "u3q6", unit: 3,
    questionText: "Is her phone number 314566? Yes, ___ is.",
    options: ["he", "she", "they", "it"], correctIndex: 3 },
  { id: "u3q7", unit: 3,
    questionText: "At 08:00 you say: '___'",
    options: ["Good evening", "Good night", "Good afternoon", "Good morning"], correctIndex: 3 },
  { id: "u3q8", unit: 3,
    questionText: "She ___ a nurse. She's a doctor.",
    options: ["is", "am", "are", "isn't"], correctIndex: 3 },

  // ── Unit 4 – Possessives, family, have/has ────────────────────────────────
  { id: "u4q1", unit: 4,
    questionText: "She's from Spain. ___ house is in Malaga.",
    options: ["My", "His", "Their", "Her"], correctIndex: 3 },
  { id: "u4q2", unit: 4,
    questionText: "We ___ a dog.",
    options: ["has", "is", "are", "have"], correctIndex: 3 },
  { id: "u4q3", unit: 4,
    questionText: "Andy ___ a lot of CDs.",
    options: ["have", "are", "has", "is"], correctIndex: 2 },
  { id: "u4q4", unit: 4,
    questionText: "Ruth and Peter are students. ___ school is in London.",
    options: ["His", "Her", "My", "Their"], correctIndex: 3 },
  { id: "u4q5", unit: 4,
    questionText: "Tom is Barry's ___.",
    options: ["mother", "sister", "father", "daughter"], correctIndex: 2 },
  { id: "u4q6", unit: 4,
    questionText: "Jan and I ___ a flat in London.",
    options: ["has", "is", "are", "have"], correctIndex: 3 },
  { id: "u4q7", unit: 4,
    questionText: "Our school ___ three classrooms.",
    options: ["have", "are", "is", "has"], correctIndex: 3 },
  { id: "u4q8", unit: 4,
    questionText: "Stefan is in Rome. What's ___ phone number?",
    options: ["my", "her", "his", "their"], correctIndex: 2 },

  // ── Unit 5 – Present simple do/does, sports, food ────────────────────────
  { id: "u5q1", unit: 5,
    questionText: "Do you like pizza? Yes, I ___.",
    options: ["does", "am", "like", "do"], correctIndex: 3 },
  { id: "u5q2", unit: 5,
    questionText: "They ___ live in Canada now.",
    options: ["doesn't", "isn't", "aren't", "don't"], correctIndex: 3 },
  { id: "u5q3", unit: 5,
    questionText: "What nationality is someone from Brazil?",
    options: ["Brasilian", "Brazilian", "Brazilish", "Brazilean"], correctIndex: 1 },
  { id: "u5q4", unit: 5,
    questionText: "___ sports do you like?",
    options: ["Where", "How", "What", "Who"], correctIndex: 2 },
  { id: "u5q5", unit: 5,
    questionText: "How many languages do you ___?",
    options: ["talk", "tell", "say", "speak"], correctIndex: 3 },
  { id: "u5q6", unit: 5,
    questionText: "They don't like beer. Do they like beer? No, they ___.",
    options: ["doesn't", "aren't", "don't", "isn't"], correctIndex: 2 },
  { id: "u5q7", unit: 5,
    questionText: "I think you ___ from Canada.",
    options: ["is", "am", "come", "goes"], correctIndex: 2 },
  { id: "u5q8", unit: 5,
    questionText: "Lucy and William ___ both teachers.",
    options: ["is", "has", "are", "have"], correctIndex: 2 },

  // ── Unit 6 – Daily routines, frequency adverbs, time ─────────────────────
  { id: "u6q1", unit: 6,
    questionText: "She ___ work at 6.30 in the evening.",
    options: ["leave", "leaving", "leaved", "leaves"], correctIndex: 3 },
  { id: "u6q2", unit: 6,
    questionText: "Does he have a shower? Yes, he ___.",
    options: ["do", "is", "have", "does"], correctIndex: 3 },
  { id: "u6q3", unit: 6,
    questionText: "Peter gets up at five. He ___ get up at five.",
    options: ["isn't", "not", "don't", "doesn't"], correctIndex: 3 },
  { id: "u6q4", unit: 6,
    questionText: "Mary ___ watches TV in the morning.",
    options: ["always", "usually", "never", "often"], correctIndex: 2 },
  { id: "u6q5", unit: 6,
    questionText: "What time ___ you get up?",
    options: ["is", "does", "do", "are"], correctIndex: 2 },
  { id: "u6q6", unit: 6,
    questionText: "They ___ eat pizza because they don't like Italian food.",
    options: ["always", "never", "usually", "sometimes"], correctIndex: 1 },
  { id: "u6q7", unit: 6,
    questionText: "He ___ in a small house in Oxford.",
    options: ["live", "lives", "is live", "are living"], correctIndex: 1 },
  { id: "u6q8", unit: 6,
    questionText: "She sometimes ___ and she goes to French lessons.",
    options: ["paint", "paints", "painting", "painted"], correctIndex: 1 },

  // ── Unit 7 – Object pronouns, adjectives, question words ─────────────────
  { id: "u7q1", unit: 7,
    questionText: "Do you like apples? No, I hate ___.",
    options: ["it", "they", "their", "them"], correctIndex: 3 },
  { id: "u7q2", unit: 7,
    questionText: "My brother Barry is a doctor. This is a photo of ___.",
    options: ["he", "his", "they", "him"], correctIndex: 3 },
  { id: "u7q3", unit: 7,
    questionText: "___ does the film start?",
    options: ["Who", "What", "When", "Where"], correctIndex: 2 },
  { id: "u7q4", unit: 7,
    questionText: "Can I ___ on this T-shirt, please?",
    options: ["go", "buy", "get", "try"], correctIndex: 3 },
  { id: "u7q5", unit: 7,
    questionText: "Our son Paul lives in London. He visits ___ at the weekend.",
    options: ["we", "our", "us", "ours"], correctIndex: 2 },
  { id: "u7q6", unit: 7,
    questionText: "John likes you ___.",
    options: ["very much", "very many", "a lots", "much very"], correctIndex: 0 },
  { id: "u7q7", unit: 7,
    questionText: "'___ much is that book?' '£9.99.'",
    options: ["What", "How", "Where", "Who"], correctIndex: 1 },
  { id: "u7q8", unit: 7,
    questionText: "Maria likes Italian food. She cooks ___ at home.",
    options: ["it", "him", "her", "them"], correctIndex: 0 },

  // ── Unit 8 – There is/are, prepositions, furniture ────────────────────────
  { id: "u8q1", unit: 8,
    questionText: "___ a sofa in the living room.",
    options: ["There are", "There aren't", "There isn't", "There's"], correctIndex: 3 },
  { id: "u8q2", unit: 8,
    questionText: "The keys are ___ the floor.",
    options: ["next to", "in", "at", "on"], correctIndex: 3 },
  { id: "u8q3", unit: 8,
    questionText: "___ any chairs in the room? No, there aren't.",
    options: ["Is there", "There is", "There are", "Are there"], correctIndex: 3 },
  { id: "u8q4", unit: 8,
    questionText: "The mobile phone is ___ the drawer.",
    options: ["on", "under", "in", "next to"], correctIndex: 2 },
  { id: "u8q5", unit: 8,
    questionText: "The TV is ___ the armchair.",
    options: ["in", "at", "under", "next to"], correctIndex: 3 },
  { id: "u8q6", unit: 8,
    questionText: "___ two magazines on that table.",
    options: ["There's", "There is", "There are", "There aren't"], correctIndex: 2 },
  { id: "u8q7", unit: 8,
    questionText: "Go straight on and turn ___ into Forest Road.",
    options: ["straight", "left", "on", "right"], correctIndex: 3 },
  { id: "u8q8", unit: 8,
    questionText: "The camera is ___ the lamp.",
    options: ["in", "under", "next to", "at"], correctIndex: 2 },

  // ── Unit 9 – Was/were, past tense of be, years, dates ────────────────────
  { id: "u9q1", unit: 9,
    questionText: "When ___ your father born?",
    options: ["is", "are", "were", "was"], correctIndex: 3 },
  { id: "u9q2", unit: 9,
    questionText: "Gandhi ___ a politician.",
    options: ["is", "were", "are", "was"], correctIndex: 3 },
  { id: "u9q3", unit: 9,
    questionText: "They ___ American. They were from England.",
    options: ["wasn't", "aren't", "isn't", "weren't"], correctIndex: 3 },
  { id: "u9q4", unit: 9,
    questionText: "Was Pete at home yesterday? No, he ___.",
    options: ["weren't", "isn't", "aren't", "wasn't"], correctIndex: 3 },
  { id: "u9q5", unit: 9,
    questionText: "Were Pete and Clare at work yesterday? Yes, they ___.",
    options: ["was", "is", "are", "were"], correctIndex: 3 },
  { id: "u9q6", unit: 9,
    questionText: "Beethoven ___ a scientist. He was a composer.",
    options: ["was", "is", "were", "wasn't"], correctIndex: 3 },
  { id: "u9q7", unit: 9,
    questionText: "Last week I ___ shopping in London.",
    options: ["go", "goes", "were", "went"], correctIndex: 3 },
  { id: "u9q8", unit: 9,
    questionText: "Pamela ___ the film was very good.",
    options: ["say", "says", "said", "saids"], correctIndex: 2 },

  // ── Unit 10 – Past simple regular & irregular ─────────────────────────────
  { id: "u10q1", unit: 10,
    questionText: "Alan and Maria ___ tennis last weekend.",
    options: ["play", "plays", "playing", "played"], correctIndex: 3 },
  { id: "u10q2", unit: 10,
    questionText: "Pamela ___ a film yesterday evening.",
    options: ["see", "sees", "saws", "saw"], correctIndex: 3 },
  { id: "u10q3", unit: 10,
    questionText: "Did Tony buy some food? Yes, he ___.",
    options: ["does", "do", "was", "did"], correctIndex: 3 },
  { id: "u10q4", unit: 10,
    questionText: "Mike painted the picture. Mike ___ paint the picture.",
    options: ["wasn't", "didn't", "don't", "doesn't"], correctIndex: 1 },
  { id: "u10q5", unit: 10,
    questionText: "Frank and Betty ___ a beautiful painting.",
    options: ["buy", "buys", "bought", "buyed"], correctIndex: 2 },
  { id: "u10q6", unit: 10,
    questionText: "She listened to the radio last night. She ___ listen to the radio.",
    options: ["didn't", "doesn't", "wasn't", "don't"], correctIndex: 0 },
  { id: "u10q7", unit: 10,
    questionText: "Where ___ you go? We went to London.",
    options: ["do", "does", "did", "was"], correctIndex: 2 },
  { id: "u10q8", unit: 10,
    questionText: "Paul ___ a new computer from that shop yesterday.",
    options: ["buy", "buys", "buying", "bought"], correctIndex: 3 },

  { id: "u10q9", unit: 10,
    questionText: "We ___ at home this morning. We went to the market.",
    options: ["stayed", "didn't stay", "don't stay", "weren't stay"], correctIndex: 1 },
  { id: "u10q10", unit: 10,
    questionText: "She ___ to the radio last night.",
    options: ["listen", "listens", "listened", "was listen"], correctIndex: 2 },
  { id: "u10q11", unit: 10,
    questionText: "They ___ shopping in Oxford Street.",
    options: ["go", "goes", "went", "were go"], correctIndex: 2 },
  { id: "u10q12", unit: 10,
    questionText: "What ___ they buy? They bought some books.",
    options: ["do", "does", "did", "was"], correctIndex: 2 },

  // ── Unit 11 – Can/can't, everyday expressions ─────────────────────────────
  { id: "u11q1", unit: 11,
    questionText: "Can John read music? Yes, he ___.",
    options: ["do", "is", "has", "can"], correctIndex: 3 },
  { id: "u11q2", unit: 11,
    questionText: "___ Katarina play the guitar? No, she can't.",
    options: ["Does", "Is", "Has", "Can"], correctIndex: 3 },
  { id: "u11q3", unit: 11,
    questionText: "Colin ___ cook, but Samantha can.",
    options: ["isn't", "hasn't", "doesn't", "can't"], correctIndex: 3 },
  { id: "u11q4", unit: 11,
    questionText: "Excuse ___. Can you help me?",
    options: ["I", "my", "me", "mine"], correctIndex: 2 },
  { id: "u11q5", unit: 11,
    questionText: "This machine doesn't ___. I put in 50p but got nothing.",
    options: ["go", "make", "work", "run"], correctIndex: 2 },
  { id: "u11q6", unit: 11,
    questionText: "I don't ___. What does 'brilliant' mean?",
    options: ["know", "understand", "speak", "read"], correctIndex: 1 },
  { id: "u11q7", unit: 11,
    questionText: "Martin ___ ride a horse. He's never tried.",
    options: ["doesn't", "isn't", "can't", "hasn't"], correctIndex: 2 },
  { id: "u11q8", unit: 11,
    questionText: "What's the ___? Are you OK?",
    options: ["problem", "matter", "wrong", "trouble"], correctIndex: 1 },
  { id: "u11q9", unit: 11,
    questionText: "Simon and Martha ___ swim. Yes, they can.",
    options: ["can", "are", "do", "have"], correctIndex: 0 },
  { id: "u11q10", unit: 11,
    questionText: "You can ___ a film in the cinema.",
    options: ["go", "make", "watch", "read"], correctIndex: 2 },
  { id: "u11q11", unit: 11,
    questionText: "___ you push this button? Did you try?",
    options: ["Do", "Are", "Did", "Can"], correctIndex: 2 },
  { id: "u11q12", unit: 11,
    questionText: "I'm really ___. I forgot your name.",
    options: ["matter", "understand", "sorry", "pardon"], correctIndex: 2 },

  // ── Unit 12 – Would like, food & restaurant ───────────────────────────────
  { id: "u12q1", unit: 12,
    questionText: "Would you like a cup of coffee? Yes, ___ please.",
    options: ["I do,", "I like,", "I would,", "I want,"], correctIndex: 2 },
  { id: "u12q2", unit: 12,
    questionText: "___ a stamp for this postcard, please.",
    options: ["Would I", "Do I", "Can I", "I'd like"], correctIndex: 3 },
  { id: "u12q3", unit: 12,
    questionText: "Are you ready to order? Yes, ___ the chicken soup.",
    options: ["I like", "I want", "would I", "I'd like"], correctIndex: 3 },
  { id: "u12q4", unit: 12,
    questionText: "'How ___ is that book?' '£9.99.'",
    options: ["many", "old", "big", "much"], correctIndex: 3 },
  { id: "u12q5", unit: 12,
    questionText: "Here's your stamp, and 70p ___.",
    options: ["rest", "money", "changes", "change"], correctIndex: 3 },
  { id: "u12q6", unit: 12,
    questionText: "___ you like to go for a walk? No, thanks.",
    options: ["Do", "Can", "Would", "Are"], correctIndex: 2 },
  { id: "u12q7", unit: 12,
    questionText: "How would you like your steak ___?",
    options: ["made", "done", "cooked", "prepared"], correctIndex: 2 },
  { id: "u12q8", unit: 12,
    questionText: "James ___ a new CD player.",
    options: ["want", "wants", "is wanting", "would"], correctIndex: 1 },

  // ── Unit 13 – Present continuous, colours, clothes ────────────────────────
  { id: "u13q1", unit: 13,
    questionText: "He ___ a book at the moment.",
    options: ["read", "reads", "are reading", "is reading"], correctIndex: 3 },
  { id: "u13q2", unit: 13,
    questionText: "We usually play tennis but today we ___ football.",
    options: ["play", "played", "playing", "are playing"], correctIndex: 3 },
  { id: "u13q3", unit: 13,
    questionText: "___ Frances cooking dinner? No, she isn't.",
    options: ["Does", "Do", "Has", "Is"], correctIndex: 3 },
  { id: "u13q4", unit: 13,
    questionText: "Look! Armando ___ green trousers.",
    options: ["wear", "wears", "wore", "is wearing"], correctIndex: 3 },
  { id: "u13q5", unit: 13,
    questionText: "We ___ enjoying this music. It's terrible.",
    options: ["are", "is", "aren't", "isn't"], correctIndex: 2 },
  { id: "u13q6", unit: 13,
    questionText: "The sky is ___. It's a beautiful day.",
    options: ["black", "brown", "blue", "grey"], correctIndex: 2 },
  { id: "u13q7", unit: 13,
    questionText: "She usually eats out but today she ___ pizza at home.",
    options: ["make", "makes", "made", "is making"], correctIndex: 3 },
  { id: "u13q8", unit: 13,
    questionText: "They're ___ a great time on holiday.",
    options: ["have", "has", "having", "had"], correctIndex: 2 },

  // ── Unit 14 – Present continuous for future, travel ─────────────────────
  { id: "u14q1", unit: 14,
    questionText: "How are you ___ to London tomorrow?",
    options: ["go", "went", "goes", "going"], correctIndex: 3 },
  { id: "u14q2", unit: 14,
    questionText: "We ___ to Oxford next Thursday.",
    options: ["go", "went", "goes", "are going"], correctIndex: 3 },
  { id: "u14q3", unit: 14,
    questionText: "Mustafa ___ his grandparents on Saturday.",
    options: ["visit", "visited", "visits", "is visiting"], correctIndex: 3 },
  { id: "u14q4", unit: 14,
    questionText: "When ___ you leaving?",
    options: ["do", "does", "are", "is"], correctIndex: 2 },
  { id: "u14q5", unit: 14,
    questionText: "Karen ___ her homework at the moment.",
    options: ["do", "does", "is doing", "are doing"], correctIndex: 2 },
  { id: "u14q6", unit: 14,
    questionText: "Next weekend they ___ a new computer.",
    options: ["buy", "buys", "are buying", "bought"], correctIndex: 2 },
  { id: "u14q7", unit: 14,
    questionText: "We can't play tennis, it ___.",
    options: ["rain", "rains", "rained", "is raining"], correctIndex: 3 },
  { id: "u14q8", unit: 14,
    questionText: "I can't help you now, I ___ dinner.",
    options: ["cook", "cooks", "am cooking", "cooked"], correctIndex: 2 },
];

export function getQuestionsForQuiz(quizId: number): PracticeQuestion[] {
  const quiz = BEGINNER_QUIZZES.find((q) => q.id === quizId);
  if (!quiz) return [];
  return questions.filter((q) => quiz.units.includes(q.unit));
}

export default questions;
