export interface PracticeQuestion {
  id: string;
  questionText: string;
  options: string[];
  correctIndex: number;
  unit: number;
}

export interface IntermediateQuiz {
  id: number; title: string; subtitle: string; units: number[]; label: string;
}

export const INTERMEDIATE_QUIZZES: IntermediateQuiz[] = [
  { id: 1, title: "Quiz 1", subtitle: "Tense Review & Present Perfect",   units: [1, 2, 3],  label: "Units 1–3" },
  { id: 2, title: "Quiz 2", subtitle: "Future & Conditionals 1 & 2",      units: [4, 5, 6],  label: "Units 4–6" },
  { id: 3, title: "Quiz 3", subtitle: "Modals & Passive Voice",           units: [7, 8],     label: "Units 7–8" },
  { id: 4, title: "Quiz 4", subtitle: "Reported Speech & Relatives",      units: [9, 10],    label: "Units 9–10" },
  { id: 5, title: "Quiz 5", subtitle: "Gerunds, Infinitives & Articles",  units: [11, 12],   label: "Units 11–12" },
];

const questions: PracticeQuestion[] = [

  // ── Unit 1 – Tense review ─────────────────────────────────────────────────
  { id: "i1q1", unit: 1,
    questionText: "She ___ for this company since 2015.",
    options: ["works", "worked", "has worked", "was working"], correctIndex: 2 },
  { id: "i1q2", unit: 1,
    questionText: "He ___ to London three times.",
    options: ["went", "goes", "has been", "had been"], correctIndex: 2 },
  { id: "i1q3", unit: 1,
    questionText: "'Where's John?' 'He ___ with a client.'",
    options: ["meets", "has met", "is meeting", "met"], correctIndex: 2 },
  { id: "i1q4", unit: 1,
    questionText: "I ___ him yesterday but he wasn't there.",
    options: ["call", "called", "have called", "was calling"], correctIndex: 1 },
  { id: "i1q5", unit: 1,
    questionText: "We ___ here since we were children.",
    options: ["live", "lived", "have lived", "are living"], correctIndex: 2 },
  { id: "i1q6", unit: 1,
    questionText: "She ___ to the radio when the news came on.",
    options: ["listened", "was listening", "has listened", "listens"], correctIndex: 1 },
  { id: "i1q7", unit: 1,
    questionText: "By the time I arrived, they ___.",
    options: ["left", "have left", "had left", "were leaving"], correctIndex: 2 },
  { id: "i1q8", unit: 1,
    questionText: "By next year, she ___ her degree.",
    options: ["finishes", "has finished", "will have finished", "will finish"], correctIndex: 2 },
  { id: "i1q9", unit: 1,
    questionText: "She ___ Spanish every day.",
    options: ["is studying", "studies", "has studied", "was studying"], correctIndex: 1 },
  { id: "i1q10", unit: 1,
    questionText: "I was so tired because I ___ well the night before.",
    options: ["don't sleep", "didn't sleep", "hadn't slept", "wasn't sleeping"], correctIndex: 2 },

  // ── Unit 2 – Present perfect simple vs continuous ─────────────────────────
  { id: "i2q1", unit: 2,
    questionText: "I'm tired because I ___ all day.",
    options: ["work", "worked", "have worked", "have been working"], correctIndex: 3 },
  { id: "i2q2", unit: 2,
    questionText: "How long ___ you been waiting?",
    options: ["did", "are", "do", "have"], correctIndex: 3 },
  { id: "i2q3", unit: 2,
    questionText: "She ___ three cups of coffee this morning.",
    options: ["had", "has had", "has been having", "was having"], correctIndex: 1 },
  { id: "i2q4", unit: 2,
    questionText: "He looks exhausted. He ___ too hard.",
    options: ["has worked", "has been working", "worked", "works"], correctIndex: 1 },
  { id: "i2q5", unit: 2,
    questionText: "I ___ this book three times.",
    options: ["have read", "have been reading", "read", "am reading"], correctIndex: 0 },
  { id: "i2q6", unit: 2,
    questionText: "They ___ building the new road for months.",
    options: ["have built", "built", "have been building", "are building"], correctIndex: 2 },
  { id: "i2q7", unit: 2,
    questionText: "She ___ for the job for ages.",
    options: ["looks", "has looked", "has been looking", "looked"], correctIndex: 2 },
  { id: "i2q8", unit: 2,
    questionText: "He ___ five emails today.",
    options: ["has written", "has been writing", "wrote", "writes"], correctIndex: 0 },
  { id: "i2q9", unit: 2,
    questionText: "We ___ all afternoon — can we stop?",
    options: ["clean", "have cleaned", "have been cleaning", "cleaned"], correctIndex: 2 },
  { id: "i2q10", unit: 2,
    questionText: "How many chapters ___ you read so far?",
    options: ["did", "are", "have", "were"], correctIndex: 2 },

  // ── Unit 3 – Narrative tenses (past simple/continuous/perfect) ─────────────
  { id: "i3q1", unit: 3,
    questionText: "When I arrived, she ___ already left.",
    options: ["has", "is", "had", "was"], correctIndex: 2 },
  { id: "i3q2", unit: 3,
    questionText: "He was cooking when the fire ___.",
    options: ["started", "was starting", "had started", "starts"], correctIndex: 0 },
  { id: "i3q3", unit: 3,
    questionText: "She ___ the film before, so she knew the ending.",
    options: ["saw", "has seen", "was seeing", "had seen"], correctIndex: 3 },
  { id: "i3q4", unit: 3,
    questionText: "While I ___ the dishes, the phone rang.",
    options: ["washed", "was washing", "had washed", "wash"], correctIndex: 1 },
  { id: "i3q5", unit: 3,
    questionText: "He felt sick because he ___ too much.",
    options: ["ate", "eats", "was eating", "had eaten"], correctIndex: 3 },
  { id: "i3q6", unit: 3,
    questionText: "By the time they arrived, we ___ dinner.",
    options: ["finish", "finished", "had finished", "were finishing"], correctIndex: 2 },
  { id: "i3q7", unit: 3,
    questionText: "She ___ home when it started raining.",
    options: ["walked", "was walking", "had walked", "walks"], correctIndex: 1 },
  { id: "i3q8", unit: 3,
    questionText: "What ___ you doing when I called?",
    options: ["do", "did", "were", "had"], correctIndex: 2 },
  { id: "i3q9", unit: 3,
    questionText: "When she got to the station, the train ___ already left.",
    options: ["has", "is", "had", "was"], correctIndex: 2 },
  { id: "i3q10", unit: 3,
    questionText: "I was exhausted because I ___ all night.",
    options: ["drive", "drove", "was driving", "had been driving"], correctIndex: 3 },

  // ── Unit 4 – Future forms ─────────────────────────────────────────────────
  { id: "i4q1", unit: 4,
    questionText: "I'll call you when I ___ home.",
    options: ["get", "will get", "am going to get", "getting"], correctIndex: 0 },
  { id: "i4q2", unit: 4,
    questionText: "Look at those clouds! It ___ rain.",
    options: ["will", "is going to", "is", "shall"], correctIndex: 1 },
  { id: "i4q3", unit: 4,
    questionText: "She ___ to London tomorrow. She's already booked the ticket.",
    options: ["will fly", "is flying", "flies", "fly"], correctIndex: 1 },
  { id: "i4q4", unit: 4,
    questionText: "I promise I ___ call you.",
    options: ["am going", "going to", "will", "am"], correctIndex: 2 },
  { id: "i4q5", unit: 4,
    questionText: "By 2030, scientists ___ a cure for cancer.",
    options: ["will find", "find", "will have found", "found"], correctIndex: 2 },
  { id: "i4q6", unit: 4,
    questionText: "She ___ to university next year — she's just got her results.",
    options: ["goes", "will go", "is going", "went"], correctIndex: 2 },
  { id: "i4q7", unit: 4,
    questionText: "He ___ probably be late. He always is.",
    options: ["goes", "is going", "will", "is"], correctIndex: 2 },
  { id: "i4q8", unit: 4,
    questionText: "The train ___ at 8:30. (timetable)",
    options: ["is going", "will", "leaves", "leaving"], correctIndex: 2 },
  { id: "i4q9", unit: 4,
    questionText: "He might ___ late — the traffic is terrible.",
    options: ["being", "be", "been", "to be"], correctIndex: 1 },
  { id: "i4q10", unit: 4,
    questionText: "We ___ dinner at 8. Do you want to join us?",
    options: ["have", "had", "will have", "are having"], correctIndex: 3 },

  // ── Unit 5 – First and second conditionals ────────────────────────────────
  { id: "i5q1", unit: 5,
    questionText: "If it rains, we ___ inside.",
    options: ["stay", "stayed", "will stay", "would stay"], correctIndex: 2 },
  { id: "i5q2", unit: 5,
    questionText: "If I had more time, I ___ learn the guitar.",
    options: ["will", "am going to", "would", "shall"], correctIndex: 2 },
  { id: "i5q3", unit: 5,
    questionText: "If I ___ you, I'd be more careful.",
    options: ["am", "was", "were", "will be"], correctIndex: 2 },
  { id: "i5q4", unit: 5,
    questionText: "Unless you ___, you'll fail the test.",
    options: ["study", "studied", "will study", "won't study"], correctIndex: 0 },
  { id: "i5q5", unit: 5,
    questionText: "If he ___ harder, he'd pass the exam.",
    options: ["studies", "will study", "studied", "study"], correctIndex: 2 },
  { id: "i5q6", unit: 5,
    questionText: "I'll send you an email as soon as I ___ the results.",
    options: ["will get", "get", "got", "am getting"], correctIndex: 1 },
  { id: "i5q7", unit: 5,
    questionText: "What ___ you do if you lost your job?",
    options: ["will", "do", "would", "are"], correctIndex: 2 },
  { id: "i5q8", unit: 5,
    questionText: "She would be happier if she ___ more.",
    options: ["exercises", "will exercise", "exercised", "would exercise"], correctIndex: 2 },
  { id: "i5q9", unit: 5,
    questionText: "If they ___ the bus, they'll be late.",
    options: ["miss", "missed", "would miss", "will miss"], correctIndex: 0 },
  { id: "i5q10", unit: 5,
    questionText: "She ___ come if you invite her.",
    options: ["would", "will", "shall", "might to"], correctIndex: 1 },

  // ── Unit 6 – Third conditional and wish ───────────────────────────────────
  { id: "i6q1", unit: 6,
    questionText: "If I ___ harder, I would have passed the exam.",
    options: ["study", "studied", "had studied", "have studied"], correctIndex: 2 },
  { id: "i6q2", unit: 6,
    questionText: "She wishes she ___ taller.",
    options: ["is", "was", "were", "has been"], correctIndex: 2 },
  { id: "i6q3", unit: 6,
    questionText: "If we had left earlier, we ___ the train.",
    options: ["don't miss", "wouldn't miss", "wouldn't have missed", "hadn't missed"], correctIndex: 2 },
  { id: "i6q4", unit: 6,
    questionText: "I wish I ___ that. I'm sorry.",
    options: ["didn't say", "hadn't said", "don't say", "haven't said"], correctIndex: 1 },
  { id: "i6q5", unit: 6,
    questionText: "If he ___ the map, he wouldn't have got lost.",
    options: ["checked", "had checked", "would check", "checks"], correctIndex: 1 },
  { id: "i6q6", unit: 6,
    questionText: "She wishes she ___ harder at school.",
    options: ["worked", "works", "had worked", "would work"], correctIndex: 2 },
  { id: "i6q7", unit: 6,
    questionText: "If you had told me, I ___ helped you.",
    options: ["will", "would have", "had", "was"], correctIndex: 1 },
  { id: "i6q8", unit: 6,
    questionText: "I wish it ___ so cold. I hate winter.",
    options: ["isn't", "wasn't", "wouldn't be", "hadn't been"], correctIndex: 1 },
  { id: "i6q9", unit: 6,
    questionText: "If she hadn't missed the interview, she ___ the job.",
    options: ["gets", "would get", "got", "would have got"], correctIndex: 3 },
  { id: "i6q10", unit: 6,
    questionText: "They ___ have caught the flight if they'd left on time.",
    options: ["can", "will", "would", "should"], correctIndex: 2 },

  // ── Unit 7 – Modal verbs (past modals) ────────────────────────────────────
  { id: "i7q1", unit: 7,
    questionText: "You ___ have told me! I was worried sick.",
    options: ["should", "must", "can", "would"], correctIndex: 0 },
  { id: "i7q2", unit: 7,
    questionText: "She ___ be at home — her lights are on.",
    options: ["can", "should", "must", "would"], correctIndex: 2 },
  { id: "i7q3", unit: 7,
    questionText: "He ___ be her father — he's too young!",
    options: ["can't", "mustn't", "shouldn't", "wouldn't"], correctIndex: 0 },
  { id: "i7q4", unit: 7,
    questionText: "They ___ have left already. I can't find them.",
    options: ["should", "might", "must to", "can"], correctIndex: 1 },
  { id: "i7q5", unit: 7,
    questionText: "You ___ have parked here. It's illegal!",
    options: ["shouldn't", "mustn't", "couldn't", "wouldn't"], correctIndex: 0 },
  { id: "i7q6", unit: 7,
    questionText: "She ___ have taken the early train — she was here before 9.",
    options: ["should", "might", "must", "can"], correctIndex: 2 },
  { id: "i7q7", unit: 7,
    questionText: "He passed easily — the test ___ have been very hard.",
    options: ["must", "can't", "couldn't", "should"], correctIndex: 1 },
  { id: "i7q8", unit: 7,
    questionText: "I ___ see the board from the back. Can I move?",
    options: ["mustn't", "can't", "shouldn't", "wouldn't"], correctIndex: 1 },
  { id: "i7q9", unit: 7,
    questionText: "You ___ take an umbrella — it might rain.",
    options: ["should", "must to", "can", "would"], correctIndex: 0 },
  { id: "i7q10", unit: 7,
    questionText: "Where are my keys? I ___ have left them in the car.",
    options: ["can", "should", "might", "will"], correctIndex: 2 },

  // ── Unit 8 – Passive voice ────────────────────────────────────────────────
  { id: "i8q1", unit: 8,
    questionText: "The Eiffel Tower ___ in 1889.",
    options: ["built", "was built", "is built", "has built"], correctIndex: 1 },
  { id: "i8q2", unit: 8,
    questionText: "English ___ all over the world.",
    options: ["speaks", "is spoken", "is speaking", "spoke"], correctIndex: 1 },
  { id: "i8q3", unit: 8,
    questionText: "The report ___ by Friday.",
    options: ["will finish", "will be finished", "is finishing", "finishes"], correctIndex: 1 },
  { id: "i8q4", unit: 8,
    questionText: "She ___ offered the job.",
    options: ["were", "is being", "was", "has been"], correctIndex: 2 },
  { id: "i8q5", unit: 8,
    questionText: "The new bridge ___ at the moment.",
    options: ["builds", "is building", "is being built", "built"], correctIndex: 2 },
  { id: "i8q6", unit: 8,
    questionText: "Cheese ___ from milk.",
    options: ["made", "makes", "is made", "is making"], correctIndex: 2 },
  { id: "i8q7", unit: 8,
    questionText: "The windows ___ yet.",
    options: ["haven't cleaned", "haven't been cleaned", "didn't clean", "weren't clean"], correctIndex: 1 },
  { id: "i8q8", unit: 8,
    questionText: "The letter ___ yesterday.",
    options: ["sent", "has sent", "was sent", "is sent"], correctIndex: 2 },
  { id: "i8q9", unit: 8,
    questionText: "A new hospital ___ near the city centre.",
    options: ["is building", "builds", "is being built", "has built"], correctIndex: 2 },
  { id: "i8q10", unit: 8,
    questionText: "The car ___ when we arrived.",
    options: ["was repairing", "has been repaired", "was being repaired", "repaired"], correctIndex: 2 },

  // ── Unit 9 – Reported speech ──────────────────────────────────────────────
  { id: "i9q1", unit: 9,
    questionText: "She said she ___ tired.",
    options: ["is", "was", "has been", "were"], correctIndex: 1 },
  { id: "i9q2", unit: 9,
    questionText: "He told me he ___ come to the party.",
    options: ["can't", "won't", "couldn't", "didn't"], correctIndex: 2 },
  { id: "i9q3", unit: 9,
    questionText: "She asked me where I ___.",
    options: ["live", "lived", "am living", "will live"], correctIndex: 1 },
  { id: "i9q4", unit: 9,
    questionText: "He said he ___ the film the day before.",
    options: ["saw", "had seen", "has seen", "was seeing"], correctIndex: 1 },
  { id: "i9q5", unit: 9,
    questionText: "She told me ___ open the window.",
    options: ["don't", "not to", "to not", "didn't"], correctIndex: 1 },
  { id: "i9q6", unit: 9,
    questionText: "He asked me if I ___ help him.",
    options: ["can", "will", "could", "would to"], correctIndex: 2 },
  { id: "i9q7", unit: 9,
    questionText: "She said she ___ call me the next day.",
    options: ["will", "would", "can", "shall"], correctIndex: 1 },
  { id: "i9q8", unit: 9,
    questionText: "'I live in Paris.' She said she ___ in Paris.",
    options: ["lives", "lived", "is living", "has lived"], correctIndex: 1 },
  { id: "i9q9", unit: 9,
    questionText: "He asked where ___ from.",
    options: ["I come", "do I come", "I came", "did I come"], correctIndex: 2 },
  { id: "i9q10", unit: 9,
    questionText: "He told me he ___ waiting for an hour.",
    options: ["has been", "is", "had been", "was"], correctIndex: 2 },

  // ── Unit 10 – Relative clauses ────────────────────────────────────────────
  { id: "i10q1", unit: 10,
    questionText: "The man ___ lives next door is a doctor.",
    options: ["which", "what", "who", "whose"], correctIndex: 2 },
  { id: "i10q2", unit: 10,
    questionText: "This is the book ___ I was telling you about.",
    options: ["who", "whose", "which", "what"], correctIndex: 2 },
  { id: "i10q3", unit: 10,
    questionText: "She's the woman ___ husband is a film star.",
    options: ["who", "which", "that", "whose"], correctIndex: 3 },
  { id: "i10q4", unit: 10,
    questionText: "The hotel ___ we stayed was very expensive.",
    options: ["which", "where", "who", "that"], correctIndex: 1 },
  { id: "i10q5", unit: 10,
    questionText: "This is the house ___ Shakespeare was born.",
    options: ["which", "who", "where", "that"], correctIndex: 2 },
  { id: "i10q6", unit: 10,
    questionText: "The car, ___ I bought last year, broke down.",
    options: ["that", "which", "who", "where"], correctIndex: 1 },
  { id: "i10q7", unit: 10,
    questionText: "Do you know the reason ___ she left?",
    options: ["which", "where", "who", "why"], correctIndex: 3 },
  { id: "i10q8", unit: 10,
    questionText: "The film ___ we watched last night was brilliant.",
    options: ["who", "whose", "that", "where"], correctIndex: 2 },
  { id: "i10q9", unit: 10,
    questionText: "She's the girl ___ father is a famous actor.",
    options: ["who", "which", "whose", "that"], correctIndex: 2 },
  { id: "i10q10", unit: 10,
    questionText: "He's the person ___ helped me get the job.",
    options: ["which", "whose", "what", "who"], correctIndex: 3 },

  // ── Unit 11 – Gerunds and infinitives ─────────────────────────────────────
  { id: "i11q1", unit: 11,
    questionText: "I managed ___ the exam.",
    options: ["passing", "pass", "to pass", "passed"], correctIndex: 2 },
  { id: "i11q2", unit: 11,
    questionText: "She admitted ___ the money.",
    options: ["steal", "to steal", "stealing", "to stealing"], correctIndex: 2 },
  { id: "i11q3", unit: 11,
    questionText: "He suggested ___ to a restaurant.",
    options: ["go", "to go", "going", "went"], correctIndex: 2 },
  { id: "i11q4", unit: 11,
    questionText: "I regret ___ you that you haven't got the job.",
    options: ["tell", "to tell", "telling", "told"], correctIndex: 1 },
  { id: "i11q5", unit: 11,
    questionText: "She kept ___ even though everyone asked her to stop.",
    options: ["talk", "to talk", "talked", "talking"], correctIndex: 3 },
  { id: "i11q6", unit: 11,
    questionText: "He seems ___ very tired today.",
    options: ["be", "to be", "being", "been"], correctIndex: 1 },
  { id: "i11q7", unit: 11,
    questionText: "I remember ___ her at the party.",
    options: ["meet", "to meet", "met", "meeting"], correctIndex: 3 },
  { id: "i11q8", unit: 11,
    questionText: "Would you mind ___ the window?",
    options: ["open", "to open", "opened", "opening"], correctIndex: 3 },
  { id: "i11q9", unit: 11,
    questionText: "She agreed ___ us.",
    options: ["helping", "to help", "help", "helped"], correctIndex: 1 },
  { id: "i11q10", unit: 11,
    questionText: "I avoid ___ to work by car.",
    options: ["drive", "to drive", "driving", "drove"], correctIndex: 2 },

  // ── Unit 12 – Articles ────────────────────────────────────────────────────
  { id: "i12q1", unit: 12,
    questionText: "She plays ___ violin beautifully.",
    options: ["a", "an", "the", "-"], correctIndex: 2 },
  { id: "i12q2", unit: 12,
    questionText: "I usually have ___ coffee for breakfast.",
    options: ["a", "an", "the", "-"], correctIndex: 3 },
  { id: "i12q3", unit: 12,
    questionText: "He goes to ___ school by bus.",
    options: ["a", "an", "the", "-"], correctIndex: 3 },
  { id: "i12q4", unit: 12,
    questionText: "We visited ___ Eiffel Tower in Paris.",
    options: ["a", "an", "the", "-"], correctIndex: 2 },
  { id: "i12q5", unit: 12,
    questionText: "She is ___ best student in the class.",
    options: ["a", "an", "the", "-"], correctIndex: 2 },
  { id: "i12q6", unit: 12,
    questionText: "I bought ___ new jacket yesterday.",
    options: ["a", "an", "the", "-"], correctIndex: 0 },
  { id: "i12q7", unit: 12,
    questionText: "He works in ___ hospital in the city centre.",
    options: ["a", "an", "the", "-"], correctIndex: 0 },
  { id: "i12q8", unit: 12,
    questionText: "'___ life is too short.' Which article is correct?",
    options: ["A", "An", "The", "-"], correctIndex: 3 },
  { id: "i12q9", unit: 12,
    questionText: "She went to ___ bed early.",
    options: ["a", "an", "the", "-"], correctIndex: 3 },
  { id: "i12q10", unit: 12,
    questionText: "He's ___ honest man.",
    options: ["a", "an", "the", "-"], correctIndex: 1 },
];

export function getQuestionsForIntermediateQuiz(quizId: number): PracticeQuestion[] {
  const quiz = INTERMEDIATE_QUIZZES.find((q) => q.id === quizId);
  if (!quiz) return [];
  return questions.filter((q) => quiz.units.includes(q.unit));
}

export default questions;
