export interface PracticeQuestion {
  id: string;
  questionText: string;
  options: string[];
  correctIndex: number;
  unit: number;
}

export interface PreIntermediateQuiz {
  id: number;
  title: string;
  subtitle: string;
  units: number[];
  label: string;
}

export const PRE_INTERMEDIATE_QUIZZES: PreIntermediateQuiz[] = [
  { id: 1, title: "Quiz 1", subtitle: "Present Tenses & Past Simple",      units: [1, 2, 3],  label: "Units 1–3" },
  { id: 2, title: "Quiz 2", subtitle: "Past Continuous, Verbs & Questions", units: [4, 5, 6],  label: "Units 4–6" },
  { id: 3, title: "Quiz 3", subtitle: "Comparatives & Present Perfect",     units: [7, 8],     label: "Units 7–8" },
  { id: 4, title: "Quiz 4", subtitle: "Future Forms",                       units: [9, 10],    label: "Units 9–10" },
  { id: 5, title: "Quiz 5", subtitle: "Modals & Second Conditional",        units: [11, 12],   label: "Units 11–12" },
];

const questions: PracticeQuestion[] = [

  // ── Unit 1 – Present simple & continuous (review) ────────────────────────
  { id: "p1q1", unit: 1,
    questionText: "She ___ in a bank.",
    options: ["work", "is working", "works", "working"], correctIndex: 2 },
  { id: "p1q2", unit: 1,
    questionText: "'Where's Mark?' 'He ___ in the garden.'",
    options: ["work", "works", "is working", "working"], correctIndex: 2 },
  { id: "p1q3", unit: 1,
    questionText: "I ___ to music every morning.",
    options: ["am listening", "listens", "listen", "listening"], correctIndex: 2 },
  { id: "p1q4", unit: 1,
    questionText: "Look! The sun ___!",
    options: ["shine", "shines", "is shining", "shining"], correctIndex: 2 },
  { id: "p1q5", unit: 1,
    questionText: "He never ___ to work by car.",
    options: ["is going", "goes", "go", "going"], correctIndex: 1 },
  { id: "p1q6", unit: 1,
    questionText: "___ you speak any foreign languages?",
    options: ["Are", "Is", "Do", "Does"], correctIndex: 2 },
  { id: "p1q7", unit: 1,
    questionText: "She ___ French, Spanish, and Italian.",
    options: ["is speaking", "speaks", "speak", "speaking"], correctIndex: 1 },
  { id: "p1q8", unit: 1,
    questionText: "We ___ a new house at the moment.",
    options: ["are building", "build", "builds", "building"], correctIndex: 0 },
  { id: "p1q9", unit: 1,
    questionText: "He ___ a shower every morning.",
    options: ["have", "is having", "has", "having"], correctIndex: 2 },
  { id: "p1q10", unit: 1,
    questionText: "They ___ dinner. Can you call back later?",
    options: ["have", "has", "are having", "having"], correctIndex: 2 },

  // ── Unit 2 – Present simple vs continuous ────────────────────────────────
  { id: "p2q1", unit: 2,
    questionText: "I ___ a book. Can I call you back?",
    options: ["read", "reads", "am reading", "reading"], correctIndex: 2 },
  { id: "p2q2", unit: 2,
    questionText: "How often ___ you play tennis?",
    options: ["are", "do", "is", "does"], correctIndex: 1 },
  { id: "p2q3", unit: 2,
    questionText: "She always ___ late.",
    options: ["are arriving", "arrive", "arrives", "arriving"], correctIndex: 2 },
  { id: "p2q4", unit: 2,
    questionText: "I don't understand. What ___ he saying?",
    options: ["does", "is", "do", "are"], correctIndex: 1 },
  { id: "p2q5", unit: 2,
    questionText: "Water ___ at 100 degrees.",
    options: ["boil", "is boiling", "boils", "boiling"], correctIndex: 2 },
  { id: "p2q6", unit: 2,
    questionText: "She ___ her grandmother every Sunday.",
    options: ["is visiting", "visit", "visits", "visiting"], correctIndex: 2 },
  { id: "p2q7", unit: 2,
    questionText: "I'm sorry, I ___ understand.",
    options: ["not", "don't", "am not", "doesn't"], correctIndex: 1 },
  { id: "p2q8", unit: 2,
    questionText: "They ___ a new restaurant downtown right now.",
    options: ["open", "opens", "are opening", "opening"], correctIndex: 2 },
  { id: "p2q9", unit: 2,
    questionText: "He ___ very well this week.",
    options: ["work", "is working", "works", "working"], correctIndex: 1 },
  { id: "p2q10", unit: 2,
    questionText: "What ___ you usually have for breakfast?",
    options: ["are", "is", "do", "does"], correctIndex: 2 },

  // ── Unit 3 – Past simple ─────────────────────────────────────────────────
  { id: "p3q1", unit: 3,
    questionText: "She ___ to Paris last year.",
    options: ["go", "goes", "went", "gone"], correctIndex: 2 },
  { id: "p3q2", unit: 3,
    questionText: "He ___ his wallet on the bus.",
    options: ["leave", "left", "leaved", "leaving"], correctIndex: 1 },
  { id: "p3q3", unit: 3,
    questionText: "Did he call you? No, he ___.",
    options: ["didn't", "don't", "wasn't", "haven't"], correctIndex: 0 },
  { id: "p3q4", unit: 3,
    questionText: "Where ___ you go on holiday last summer?",
    options: ["do", "are", "have", "did"], correctIndex: 3 },
  { id: "p3q5", unit: 3,
    questionText: "She ___ up very early this morning.",
    options: ["get", "got", "gotten", "getting"], correctIndex: 1 },
  { id: "p3q6", unit: 3,
    questionText: "I ___ a lot of interesting people at the party.",
    options: ["meet", "met", "meeted", "meeting"], correctIndex: 1 },
  { id: "p3q7", unit: 3,
    questionText: "We ___ dinner at 8 o'clock last night.",
    options: ["have", "had", "have had", "having"], correctIndex: 1 },
  { id: "p3q8", unit: 3,
    questionText: "He ___ the test because he studied hard.",
    options: ["pass", "passes", "passed", "passing"], correctIndex: 2 },
  { id: "p3q9", unit: 3,
    questionText: "Did you enjoy the film? Yes, I ___ it.",
    options: ["love", "loved", "was loving", "have loved"], correctIndex: 1 },
  { id: "p3q10", unit: 3,
    questionText: "She ___ not write to me for months.",
    options: ["didn't", "don't", "hasn't", "wasn't"], correctIndex: 0 },

  // ── Unit 4 – Past continuous ─────────────────────────────────────────────
  { id: "p4q1", unit: 4,
    questionText: "I ___ TV when the phone rang.",
    options: ["watch", "watched", "was watching", "have watched"], correctIndex: 2 },
  { id: "p4q2", unit: 4,
    questionText: "She ___ when she fell.",
    options: ["ran", "run", "was running", "has run"], correctIndex: 2 },
  { id: "p4q3", unit: 4,
    questionText: "They ___ dinner when we arrived.",
    options: ["have", "had", "were having", "have had"], correctIndex: 2 },
  { id: "p4q4", unit: 4,
    questionText: "While he ___ the car, he heard a strange noise.",
    options: ["drive", "drove", "was driving", "drives"], correctIndex: 2 },
  { id: "p4q5", unit: 4,
    questionText: "It ___ when we went out.",
    options: ["rained", "rain", "was raining", "rains"], correctIndex: 2 },
  { id: "p4q6", unit: 4,
    questionText: "What ___ he doing at midnight?",
    options: ["is", "did", "does", "was"], correctIndex: 3 },
  { id: "p4q7", unit: 4,
    questionText: "She met her husband while she ___ in London.",
    options: ["live", "lived", "was living", "lives"], correctIndex: 2 },
  { id: "p4q8", unit: 4,
    questionText: "I ___ not sleeping when you called.",
    options: ["wasn't", "didn't", "don't", "haven't"], correctIndex: 0 },
  { id: "p4q9", unit: 4,
    questionText: "At 7 o'clock yesterday, she ___ to work.",
    options: ["drive", "drove", "was driving", "drives"], correctIndex: 2 },
  { id: "p4q10", unit: 4,
    questionText: "What were you doing when I ___?",
    options: ["call", "called", "was calling", "have called"], correctIndex: 1 },

  // ── Unit 5 – Verb patterns (want/like/love + to/ing) ─────────────────────
  { id: "p5q1", unit: 5,
    questionText: "I want ___ to Paris.",
    options: ["go", "going", "to go", "went"], correctIndex: 2 },
  { id: "p5q2", unit: 5,
    questionText: "She loves ___ in the rain.",
    options: ["to walking", "walk", "walking", "walked"], correctIndex: 2 },
  { id: "p5q3", unit: 5,
    questionText: "He decided ___ a new job.",
    options: ["find", "finding", "to find", "found"], correctIndex: 2 },
  { id: "p5q4", unit: 5,
    questionText: "She refused ___.",
    options: ["help", "helping", "to help", "helped"], correctIndex: 2 },
  { id: "p5q5", unit: 5,
    questionText: "I can't stand ___.",
    options: ["wait", "to wait", "waiting", "waited"], correctIndex: 2 },
  { id: "p5q6", unit: 5,
    questionText: "He managed ___ the exam.",
    options: ["pass", "passing", "to pass", "passed"], correctIndex: 2 },
  { id: "p5q7", unit: 5,
    questionText: "Would you like ___ some coffee?",
    options: ["have", "having", "to have", "had"], correctIndex: 2 },
  { id: "p5q8", unit: 5,
    questionText: "They hope ___ next year.",
    options: ["travel", "to travel", "travelling", "travelled"], correctIndex: 1 },
  { id: "p5q9", unit: 5,
    questionText: "I don't mind ___ late.",
    options: ["work", "to work", "working", "worked"], correctIndex: 2 },
  { id: "p5q10", unit: 5,
    questionText: "Do you enjoy ___?",
    options: ["cook", "to cook", "cooking", "cooked"], correctIndex: 2 },

  // ── Unit 6 – Question forms ───────────────────────────────────────────────
  { id: "p6q1", unit: 6,
    questionText: "___ does she live? In Paris.",
    options: ["Where", "When", "How", "What"], correctIndex: 0 },
  { id: "p6q2", unit: 6,
    questionText: "___ did you go on holiday? Last summer.",
    options: ["Where", "Who", "When", "How"], correctIndex: 2 },
  { id: "p6q3", unit: 6,
    questionText: "___ did they go? By train.",
    options: ["When", "Why", "What", "How"], correctIndex: 3 },
  { id: "p6q4", unit: 6,
    questionText: "___ does he work for? A big company.",
    options: ["Who", "What", "Where", "Which"], correctIndex: 0 },
  { id: "p6q5", unit: 6,
    questionText: "___ did she leave? Because she was tired.",
    options: ["What", "When", "How", "Why"], correctIndex: 3 },
  { id: "p6q6", unit: 6,
    questionText: "___ long does the journey take? Two hours.",
    options: ["How", "What", "When", "Where"], correctIndex: 0 },
  { id: "p6q7", unit: 6,
    questionText: "___ people were at the party? About 50.",
    options: ["What", "Who", "How many", "How much"], correctIndex: 2 },
  { id: "p6q8", unit: 6,
    questionText: "___ is your sister like? She's tall and funny.",
    options: ["How", "What", "Who", "Where"], correctIndex: 1 },
  { id: "p6q9", unit: 6,
    questionText: "___ is your phone number?",
    options: ["What", "Where", "Who", "Which"], correctIndex: 0 },
  { id: "p6q10", unit: 6,
    questionText: "___ did you buy that coat? It's lovely!",
    options: ["When", "Who", "Where", "Why"], correctIndex: 2 },

  // ── Unit 7 – Comparatives and superlatives ────────────────────────────────
  { id: "p7q1", unit: 7,
    questionText: "This is ___ film I've ever seen.",
    options: ["the baddest", "the worse", "worst", "the worst"], correctIndex: 3 },
  { id: "p7q2", unit: 7,
    questionText: "She's ___ student in the class.",
    options: ["the more intelligent", "most intelligent", "the most intelligent", "the intelligent"], correctIndex: 2 },
  { id: "p7q3", unit: 7,
    questionText: "He's ___ than his brother.",
    options: ["tall", "taller", "tallest", "more taller"], correctIndex: 1 },
  { id: "p7q4", unit: 7,
    questionText: "This restaurant is ___ than the last one.",
    options: ["more expensive", "expensiver", "most expensive", "expensive"], correctIndex: 0 },
  { id: "p7q5", unit: 7,
    questionText: "Which is ___ city in the world?",
    options: ["bigger", "the bigger", "the biggest", "more big"], correctIndex: 2 },
  { id: "p7q6", unit: 7,
    questionText: "My English is getting ___.",
    options: ["more good", "the best", "better", "best"], correctIndex: 2 },
  { id: "p7q7", unit: 7,
    questionText: "This book is ___ interesting than that one.",
    options: ["most", "more", "very", "much"], correctIndex: 1 },
  { id: "p7q8", unit: 7,
    questionText: "It was ___ day of the year.",
    options: ["the hotter", "the hottest", "hotter", "most hot"], correctIndex: 1 },
  { id: "p7q9", unit: 7,
    questionText: "She runs ___ than I do.",
    options: ["more faster", "fastest", "more fast", "faster"], correctIndex: 3 },
  { id: "p7q10", unit: 7,
    questionText: "He's ___ person I know.",
    options: ["the friendliest", "friendlier", "more friendlier", "most friendly"], correctIndex: 0 },

  // ── Unit 8 – Present perfect ──────────────────────────────────────────────
  { id: "p8q1", unit: 8,
    questionText: "I ___ never been to Japan.",
    options: ["am", "have", "had", "was"], correctIndex: 1 },
  { id: "p8q2", unit: 8,
    questionText: "She ___ just finished her homework.",
    options: ["is", "was", "had", "has"], correctIndex: 3 },
  { id: "p8q3", unit: 8,
    questionText: "Have you ever ___ sushi?",
    options: ["eat", "ate", "eaten", "eating"], correctIndex: 2 },
  { id: "p8q4", unit: 8,
    questionText: "___ you ever tried Mexican food?",
    options: ["Did", "Are", "Do", "Have"], correctIndex: 3 },
  { id: "p8q5", unit: 8,
    questionText: "We ___ lived here for ten years.",
    options: ["are", "were", "had", "have"], correctIndex: 3 },
  { id: "p8q6", unit: 8,
    questionText: "She has worked here ___ 2015.",
    options: ["for", "ago", "since", "in"], correctIndex: 2 },
  { id: "p8q7", unit: 8,
    questionText: "I haven't seen him ___ last week.",
    options: ["for", "in", "since", "ago"], correctIndex: 2 },
  { id: "p8q8", unit: 8,
    questionText: "He has already ___ the email.",
    options: ["send", "sent", "sends", "sending"], correctIndex: 1 },
  { id: "p8q9", unit: 8,
    questionText: "I've known her ___ many years.",
    options: ["since", "ago", "for", "in"], correctIndex: 2 },
  { id: "p8q10", unit: 8,
    questionText: "He ___ not finished the report yet.",
    options: ["did", "does", "has", "have"], correctIndex: 2 },

  // ── Unit 9 – Future (will, going to, present continuous) ──────────────────
  { id: "p9q1", unit: 9,
    questionText: "I think it ___ rain tomorrow.",
    options: ["is going", "going to", "will", "is"], correctIndex: 2 },
  { id: "p9q2", unit: 9,
    questionText: "We ___ going to visit Rome next month.",
    options: ["am", "is", "will", "are"], correctIndex: 3 },
  { id: "p9q3", unit: 9,
    questionText: "Look at those dark clouds! It ___ rain.",
    options: ["will", "is going to", "is", "was"], correctIndex: 1 },
  { id: "p9q4", unit: 9,
    questionText: "She ___ to London tomorrow. She's already booked the ticket.",
    options: ["will fly", "is flying", "flies", "fly"], correctIndex: 1 },
  { id: "p9q5", unit: 9,
    questionText: "I promise I ___ call you.",
    options: ["am going", "going to", "will", "am"], correctIndex: 2 },
  { id: "p9q6", unit: 9,
    questionText: "What ___ you doing tomorrow evening?",
    options: ["do", "will", "have", "are"], correctIndex: 3 },
  { id: "p9q7", unit: 9,
    questionText: "He ___ probably be late. He always is.",
    options: ["goes", "is going", "will", "is"], correctIndex: 2 },
  { id: "p9q8", unit: 9,
    questionText: "The train ___ at 8:30. (timetable)",
    options: ["is going", "will", "leaves", "leaving"], correctIndex: 2 },
  { id: "p9q9", unit: 9,
    questionText: "They ___ get married next year.",
    options: ["will", "are going to", "do", "have"], correctIndex: 1 },
  { id: "p9q10", unit: 9,
    questionText: "'___ you have dinner with us tonight?' 'Yes, I'd love to.'",
    options: ["Are", "Will", "Do", "Have"], correctIndex: 1 },

  // ── Unit 10 – Present perfect vs past simple ──────────────────────────────
  { id: "p10q1", unit: 10,
    questionText: "I ___ to Paris three times.",
    options: ["went", "have been", "was", "have went"], correctIndex: 1 },
  { id: "p10q2", unit: 10,
    questionText: "She ___ the book last week.",
    options: ["has read", "have read", "read", "reads"], correctIndex: 2 },
  { id: "p10q3", unit: 10,
    questionText: "___ you ever eaten sushi?",
    options: ["Did", "Have", "Do", "Were"], correctIndex: 1 },
  { id: "p10q4", unit: 10,
    questionText: "He ___ in London from 2010 to 2015.",
    options: ["has lived", "have lived", "lives", "lived"], correctIndex: 3 },
  { id: "p10q5", unit: 10,
    questionText: "I ___ never tried skydiving.",
    options: ["did", "was", "have", "had"], correctIndex: 2 },
  { id: "p10q6", unit: 10,
    questionText: "When ___ you arrive? I arrived at 8.",
    options: ["have", "has", "did", "do"], correctIndex: 2 },
  { id: "p10q7", unit: 10,
    questionText: "How long ___ you known her?",
    options: ["did", "have", "do", "are"], correctIndex: 1 },
  { id: "p10q8", unit: 10,
    questionText: "They ___ just arrived from Tokyo.",
    options: ["are", "did", "were", "have"], correctIndex: 3 },
  { id: "p10q9", unit: 10,
    questionText: "I ___ this film in 2019.",
    options: ["have seen", "has seen", "saw", "see"], correctIndex: 2 },
  { id: "p10q10", unit: 10,
    questionText: "She ___ already left when I called.",
    options: ["is", "has", "had", "have"], correctIndex: 2 },

  // ── Unit 11 – Modals (should, must, have to, can) ─────────────────────────
  { id: "p11q1", unit: 11,
    questionText: "You ___ see a doctor. You don't look well.",
    options: ["must", "should", "can", "have"], correctIndex: 1 },
  { id: "p11q2", unit: 11,
    questionText: "She ___ work on Saturdays. It's in her contract.",
    options: ["should", "can", "has to", "must to"], correctIndex: 2 },
  { id: "p11q3", unit: 11,
    questionText: "You ___ smoke in here. It's not allowed.",
    options: ["should", "can", "mustn't", "have to"], correctIndex: 2 },
  { id: "p11q4", unit: 11,
    questionText: "He ___ speak four languages. He's very talented.",
    options: ["should", "has to", "must", "can"], correctIndex: 3 },
  { id: "p11q5", unit: 11,
    questionText: "You ___ forget your passport. It's very important.",
    options: ["should", "shouldn't", "mustn't", "don't have to"], correctIndex: 2 },
  { id: "p11q6", unit: 11,
    questionText: "I think you ___ apologise to her.",
    options: ["must", "should", "can", "have"], correctIndex: 1 },
  { id: "p11q7", unit: 11,
    questionText: "She ___ pay — it's free for students.",
    options: ["shouldn't", "doesn't have to", "mustn't", "can't"], correctIndex: 1 },
  { id: "p11q8", unit: 11,
    questionText: "You ___ be quiet in the library.",
    options: ["should", "can", "must", "have to"], correctIndex: 2 },
  { id: "p11q9", unit: 11,
    questionText: "___ I use your phone? Mine is out of battery.",
    options: ["Must", "Should", "Have", "Can"], correctIndex: 3 },
  { id: "p11q10", unit: 11,
    questionText: "Students ___ wear a uniform at this school.",
    options: ["should", "can", "have to", "must to"], correctIndex: 2 },

  // ── Unit 12 – Second conditional ─────────────────────────────────────────
  { id: "p12q1", unit: 12,
    questionText: "If I ___ more money, I'd buy a new car.",
    options: ["have", "had", "would have", "will have"], correctIndex: 1 },
  { id: "p12q2", unit: 12,
    questionText: "She would travel the world if she ___ rich.",
    options: ["is", "would be", "were", "will be"], correctIndex: 2 },
  { id: "p12q3", unit: 12,
    questionText: "If you studied harder, you ___ pass the exam.",
    options: ["will", "would", "can", "could to"], correctIndex: 1 },
  { id: "p12q4", unit: 12,
    questionText: "What would you do if you ___ the lottery?",
    options: ["win", "would win", "won", "wins"], correctIndex: 2 },
  { id: "p12q5", unit: 12,
    questionText: "If I ___ you, I'd tell her the truth.",
    options: ["am", "would be", "will be", "were"], correctIndex: 3 },
  { id: "p12q6", unit: 12,
    questionText: "He ___ call you if he had your number.",
    options: ["will", "can", "would", "should"], correctIndex: 2 },
  { id: "p12q7", unit: 12,
    questionText: "If we ___ earlier, we wouldn't miss the train.",
    options: ["leave", "left", "would leave", "leaves"], correctIndex: 1 },
  { id: "p12q8", unit: 12,
    questionText: "She could help us if she ___ more time.",
    options: ["has", "have", "would have", "had"], correctIndex: 3 },
  { id: "p12q9", unit: 12,
    questionText: "If they invited me, I ___ definitely go.",
    options: ["will", "would", "can", "should"], correctIndex: 1 },
  { id: "p12q10", unit: 12,
    questionText: "I wouldn't do that if I ___ you.",
    options: ["am", "would be", "were", "will be"], correctIndex: 2 },
];

export function getQuestionsForPreIntermediateQuiz(quizId: number): PracticeQuestion[] {
  const quiz = PRE_INTERMEDIATE_QUIZZES.find((q) => q.id === quizId);
  if (!quiz) return [];
  return questions.filter((q) => quiz.units.includes(q.unit));
}

export default questions;
