export interface PracticeQuestion {
  id: string;
  questionText: string;
  options: string[];
  correctIndex: number;
  unit: number;
}

export interface UpperIntermediateQuiz {
  id: number; title: string; subtitle: string; units: number[]; label: string;
}

export const UPPER_INTERMEDIATE_QUIZZES: UpperIntermediateQuiz[] = [
  { id: 1, title: "Quiz 1", subtitle: "Complex Tenses & Aspect",          units: [1, 2, 3],  label: "Units 1–3" },
  { id: 2, title: "Quiz 2", subtitle: "Passives & Complex Conditionals",  units: [4, 5, 6],  label: "Units 4–6" },
  { id: 3, title: "Quiz 3", subtitle: "Wish, Regret & Advanced Modals",   units: [7, 8],     label: "Units 7–8" },
  { id: 4, title: "Quiz 4", subtitle: "Reported Speech & Relative Clauses", units: [9, 10],  label: "Units 9–10" },
  { id: 5, title: "Quiz 5", subtitle: "Inversion, Emphasis & Verb Patterns", units: [11, 12], label: "Units 11–12" },
];

const questions: PracticeQuestion[] = [

  // ── Unit 1 – Complex tenses ───────────────────────────────────────────────
  { id: "u1q1", unit: 1,
    questionText: "She ___ here for ten years by the time she retires.",
    options: ["will work", "works", "will have worked", "has worked"], correctIndex: 2 },
  { id: "u1q2", unit: 1,
    questionText: "I ___ all morning — that's why I'm so tired.",
    options: ["have worked", "work", "have been working", "worked"], correctIndex: 2 },
  { id: "u1q3", unit: 1,
    questionText: "They ___ the project before the deadline — I'm sure of it.",
    options: ["finish", "will finish", "will have finished", "have finished"], correctIndex: 2 },
  { id: "u1q4", unit: 1,
    questionText: "By the time she called, I ___ for two hours.",
    options: ["waited", "was waiting", "had been waiting", "have waited"], correctIndex: 2 },
  { id: "u1q5", unit: 1,
    questionText: "He looks dirty. He ___ in the garden.",
    options: ["works", "worked", "has been working", "has worked"], correctIndex: 2 },
  { id: "u1q6", unit: 1,
    questionText: "This time tomorrow, we ___ on the beach.",
    options: ["lie", "will lie", "will be lying", "are lying"], correctIndex: 2 },
  { id: "u1q7", unit: 1,
    questionText: "I ___ three coffees already. I need to stop.",
    options: ["have been drinking", "have drunk", "am drinking", "drink"], correctIndex: 1 },
  { id: "u1q8", unit: 1,
    questionText: "She realised she ___ her keys at home.",
    options: ["left", "leaves", "had left", "was leaving"], correctIndex: 2 },
  { id: "u1q9", unit: 1,
    questionText: "He ___ for this company for 20 years when he finally retired.",
    options: ["has worked", "worked", "had been working", "was working"], correctIndex: 2 },
  { id: "u1q10", unit: 1,
    questionText: "By next month, I ___ this course.",
    options: ["finish", "am finishing", "will have finished", "will finish"], correctIndex: 2 },

  // ── Unit 2 – Future perfect and continuous ────────────────────────────────
  { id: "u2q1", unit: 2,
    questionText: "This time next week, I ___ on a beach in Spain.",
    options: ["sit", "will sit", "will be sitting", "am sitting"], correctIndex: 2 },
  { id: "u2q2", unit: 2,
    questionText: "Don't call after 10 — I ___ asleep.",
    options: ["will be", "am", "will have been", "would be"], correctIndex: 0 },
  { id: "u2q3", unit: 2,
    questionText: "By the time he arrives, the film ___.",
    options: ["will start", "starts", "will have started", "is starting"], correctIndex: 2 },
  { id: "u2q4", unit: 2,
    questionText: "At 9 p.m. tonight, they ___ dinner.",
    options: ["have", "will have", "will be having", "had"], correctIndex: 2 },
  { id: "u2q5", unit: 2,
    questionText: "In two years, she ___ her degree.",
    options: ["completes", "will complete", "will have completed", "is completing"], correctIndex: 2 },
  { id: "u2q6", unit: 2,
    questionText: "How long ___ you been learning English?",
    options: ["do", "did", "have", "are"], correctIndex: 2 },
  { id: "u2q7", unit: 2,
    questionText: "I ___ here since 7 a.m. I'm ready to go home.",
    options: ["am sitting", "sit", "have been sitting", "was sitting"], correctIndex: 2 },
  { id: "u2q8", unit: 2,
    questionText: "She hopes she ___ the project by Friday.",
    options: ["finishes", "has finished", "will have finished", "will finish"], correctIndex: 2 },
  { id: "u2q9", unit: 2,
    questionText: "When you arrive, I ___ for three hours.",
    options: ["cook", "will cook", "will have been cooking", "am cooking"], correctIndex: 2 },
  { id: "u2q10", unit: 2,
    questionText: "Next year, she ___ here for a decade.",
    options: ["works", "will work", "will have been working", "has worked"], correctIndex: 2 },

  // ── Unit 3 – Narrative tenses (advanced) ──────────────────────────────────
  { id: "u3q1", unit: 3,
    questionText: "She was exhausted because she ___ all day.",
    options: ["worked", "has worked", "had been working", "works"], correctIndex: 2 },
  { id: "u3q2", unit: 3,
    questionText: "He didn't know the area well. He ___ there before.",
    options: ["hasn't been", "wasn't", "hadn't been", "doesn't go"], correctIndex: 2 },
  { id: "u3q3", unit: 3,
    questionText: "While she ___ the report, her computer crashed.",
    options: ["wrote", "was writing", "had written", "writes"], correctIndex: 1 },
  { id: "u3q4", unit: 3,
    questionText: "By the time the ambulance arrived, he ___ already.",
    options: ["recovered", "has recovered", "had recovered", "recovers"], correctIndex: 2 },
  { id: "u3q5", unit: 3,
    questionText: "I suddenly remembered that I ___ to turn off the oven.",
    options: ["forget", "forgot", "had forgotten", "have forgotten"], correctIndex: 2 },
  { id: "u3q6", unit: 3,
    questionText: "She ___ for hours before she finally found a taxi.",
    options: ["walked", "was walking", "had been walking", "has walked"], correctIndex: 2 },
  { id: "u3q7", unit: 3,
    questionText: "When I met him, he ___ for the company for five years.",
    options: ["worked", "was working", "had been working", "has worked"], correctIndex: 2 },
  { id: "u3q8", unit: 3,
    questionText: "The meeting ___ by the time we got there.",
    options: ["already started", "has already started", "had already started", "already starts"], correctIndex: 2 },
  { id: "u3q9", unit: 3,
    questionText: "He looked pale because he ___ all night.",
    options: ["studies", "studied", "was studying", "had been studying"], correctIndex: 3 },
  { id: "u3q10", unit: 3,
    questionText: "She ___ to Paris twice before she moved there.",
    options: ["went", "goes", "had been", "was going"], correctIndex: 2 },

  // ── Unit 4 – Complex passives ─────────────────────────────────────────────
  { id: "u4q1", unit: 4,
    questionText: "She ___ offered a promotion last week.",
    options: ["has", "is", "was", "had"], correctIndex: 2 },
  { id: "u4q2", unit: 4,
    questionText: "The suspect ___ questioned by police right now.",
    options: ["is being", "has been", "was", "is"], correctIndex: 0 },
  { id: "u4q3", unit: 4,
    questionText: "The results ___ announced tomorrow.",
    options: ["are being", "have been", "were", "will be"], correctIndex: 3 },
  { id: "u4q4", unit: 4,
    questionText: "By 1900, the telephone ___ already invented.",
    options: ["is", "was", "had been", "has been"], correctIndex: 2 },
  { id: "u4q5", unit: 4,
    questionText: "I got the car repaired. This means someone ___ the car for me.",
    options: ["repaired", "was repairing", "repaired", "had repaired"], correctIndex: 0 },
  { id: "u4q6", unit: 4,
    questionText: "She ___ told to wait outside.",
    options: ["is", "was", "has", "had been"], correctIndex: 1 },
  { id: "u4q7", unit: 4,
    questionText: "The documents ___ stolen before we noticed.",
    options: ["are", "were", "have been", "had been"], correctIndex: 3 },
  { id: "u4q8", unit: 4,
    questionText: "She needs to ___ her eyes tested.",
    options: ["get", "have got", "have", "be having"], correctIndex: 0 },
  { id: "u4q9", unit: 4,
    questionText: "The bridge ___ for two years before it opened.",
    options: ["was built", "was being built", "had been built", "has been built"], correctIndex: 1 },
  { id: "u4q10", unit: 4,
    questionText: "Nothing ___ about the problem yet.",
    options: ["did", "was done", "has been done", "is doing"], correctIndex: 2 },

  // ── Unit 5 – Mixed conditionals ───────────────────────────────────────────
  { id: "u5q1", unit: 5,
    questionText: "If I had studied medicine, I ___ a doctor now.",
    options: ["was", "would be", "will be", "am"], correctIndex: 1 },
  { id: "u5q2", unit: 5,
    questionText: "If she weren't so shy, she ___ spoken to him at the party.",
    options: ["would", "will have", "would have", "had"], correctIndex: 2 },
  { id: "u5q3", unit: 5,
    questionText: "If he had taken the job, he ___ in London now.",
    options: ["lived", "would live", "will live", "would have lived"], correctIndex: 1 },
  { id: "u5q4", unit: 5,
    questionText: "But for your help, I ___ finished on time.",
    options: ["wouldn't have", "won't have", "hadn't", "didn't"], correctIndex: 0 },
  { id: "u5q5", unit: 5,
    questionText: "If only I ___ harder when I was young.",
    options: ["study", "studied", "had studied", "would study"], correctIndex: 2 },
  { id: "u5q6", unit: 5,
    questionText: "Had I known about the problem, I ___ you earlier.",
    options: ["told", "would tell", "will tell", "would have told"], correctIndex: 3 },
  { id: "u5q7", unit: 5,
    questionText: "If it weren't for her support, I ___ given up.",
    options: ["will have", "would have", "had", "would"], correctIndex: 1 },
  { id: "u5q8", unit: 5,
    questionText: "She would be fluent now if she ___ more when she was young.",
    options: ["practised", "had practised", "practises", "would practise"], correctIndex: 1 },
  { id: "u5q9", unit: 5,
    questionText: "___ I been there, I would have helped.",
    options: ["If", "Were", "Should", "Had"], correctIndex: 3 },
  { id: "u5q10", unit: 5,
    questionText: "He ___ be alive today if the doctors hadn't operated.",
    options: ["won't", "wouldn't", "won't have", "wouldn't have"], correctIndex: 1 },

  // ── Unit 6 – Advanced verb patterns ──────────────────────────────────────
  { id: "u6q1", unit: 6,
    questionText: "I remember ___ him at the airport — it was years ago.",
    options: ["to meet", "meeting", "meet", "to have met"], correctIndex: 1 },
  { id: "u6q2", unit: 6,
    questionText: "Please remember ___ the door when you leave.",
    options: ["locking", "lock", "to lock", "locked"], correctIndex: 2 },
  { id: "u6q3", unit: 6,
    questionText: "She stopped ___ because it was bad for her health.",
    options: ["to smoke", "smoke", "smoking", "smoked"], correctIndex: 2 },
  { id: "u6q4", unit: 6,
    questionText: "He stopped ___ at the shop on the way home.",
    options: ["to buy", "buying", "buy", "bought"], correctIndex: 0 },
  { id: "u6q5", unit: 6,
    questionText: "I tried ___ the stain but it didn't work.",
    options: ["remove", "to remove", "removing", "removed"], correctIndex: 1 },
  { id: "u6q6", unit: 6,
    questionText: "She went on ___ for an hour despite the noise.",
    options: ["talk", "to talk", "talking", "talked"], correctIndex: 2 },
  { id: "u6q7", unit: 6,
    questionText: "He denied ___ the money.",
    options: ["steal", "to steal", "stealing", "to stealing"], correctIndex: 2 },
  { id: "u6q8", unit: 6,
    questionText: "I didn't mean ___ you.",
    options: ["upsetting", "upset", "to upset", "to upsetting"], correctIndex: 2 },
  { id: "u6q9", unit: 6,
    questionText: "She's used to ___ early. It doesn't bother her.",
    options: ["get up", "gets up", "getting up", "got up"], correctIndex: 2 },
  { id: "u6q10", unit: 6,
    questionText: "We're looking forward to ___ you.",
    options: ["see", "seeing", "to see", "have seen"], correctIndex: 1 },

  // ── Unit 7 – Wish, regret and if only ────────────────────────────────────
  { id: "u7q1", unit: 7,
    questionText: "I wish I ___ speak Japanese. It would be so useful.",
    options: ["can", "could", "would", "will"], correctIndex: 1 },
  { id: "u7q2", unit: 7,
    questionText: "She wishes she ___ so rude to him yesterday.",
    options: ["wasn't", "isn't", "hadn't been", "won't be"], correctIndex: 2 },
  { id: "u7q3", unit: 7,
    questionText: "If only I ___ that email before sending it.",
    options: ["check", "checked", "had checked", "would check"], correctIndex: 2 },
  { id: "u7q4", unit: 7,
    questionText: "He regrets ___ so much time on social media.",
    options: ["spend", "to spend", "spending", "spent"], correctIndex: 2 },
  { id: "u7q5", unit: 7,
    questionText: "It's time we ___ — it's getting late.",
    options: ["go", "went", "have gone", "going"], correctIndex: 1 },
  { id: "u7q6", unit: 7,
    questionText: "I'd rather you ___ tell anyone about this.",
    options: ["don't", "didn't", "hadn't", "wouldn't"], correctIndex: 1 },
  { id: "u7q7", unit: 7,
    questionText: "She wishes things ___ differently.",
    options: ["are", "were", "have been", "had been"], correctIndex: 3 },
  { id: "u7q8", unit: 7,
    questionText: "If only he ___ to her advice!",
    options: ["listens", "listened", "had listened", "would listen"], correctIndex: 2 },
  { id: "u7q9", unit: 7,
    questionText: "I'd rather ___ at home tonight.",
    options: ["staying", "stay", "to stay", "stayed"], correctIndex: 1 },
  { id: "u7q10", unit: 7,
    questionText: "It's about time you ___ a decision.",
    options: ["make", "made", "have made", "making"], correctIndex: 1 },

  // ── Unit 8 – Advanced modal verbs ────────────────────────────────────────
  { id: "u8q1", unit: 8,
    questionText: "You ___ have seen her — she left hours ago!",
    options: ["mustn't", "can't", "shouldn't", "wouldn't"], correctIndex: 1 },
  { id: "u8q2", unit: 8,
    questionText: "She ___ have forgotten — she never forgets anything.",
    options: ["can't", "mustn't", "shouldn't", "wouldn't"], correctIndex: 0 },
  { id: "u8q3", unit: 8,
    questionText: "I ___ have been more careful — it was my fault.",
    options: ["can", "could", "may", "must"], correctIndex: 1 },
  { id: "u8q4", unit: 8,
    questionText: "He ___ have taken the wrong turn. He's very lost.",
    options: ["must", "can", "should", "will"], correctIndex: 0 },
  { id: "u8q5", unit: 8,
    questionText: "They ___ have arrived by now. I wonder what happened.",
    options: ["can", "should", "will", "would"], correctIndex: 1 },
  { id: "u8q6", unit: 8,
    questionText: "She ___ have been lying — her story changed completely.",
    options: ["must", "can't", "shouldn't", "wouldn't"], correctIndex: 0 },
  { id: "u8q7", unit: 8,
    questionText: "I ___ have told you earlier. I'm really sorry.",
    options: ["can", "should", "must", "would"], correctIndex: 1 },
  { id: "u8q8", unit: 8,
    questionText: "He passed the test easily — it ___ have been very difficult.",
    options: ["must", "should", "can't", "won't"], correctIndex: 2 },
  { id: "u8q9", unit: 8,
    questionText: "She ___ have been at the party — I didn't see her.",
    options: ["must", "should", "might not", "can"], correctIndex: 2 },
  { id: "u8q10", unit: 8,
    questionText: "You ___ have asked permission first. That was rude.",
    options: ["may", "should", "can", "will"], correctIndex: 1 },

  // ── Unit 9 – Complex reported speech ─────────────────────────────────────
  { id: "u9q1", unit: 9,
    questionText: "She demanded that we ___ immediately.",
    options: ["leave", "left", "would leave", "had left"], correctIndex: 0 },
  { id: "u9q2", unit: 9,
    questionText: "He insisted that he ___ innocent.",
    options: ["is", "was", "has been", "be"], correctIndex: 1 },
  { id: "u9q3", unit: 9,
    questionText: "She asked how long I ___ for the job.",
    options: ["have applied", "applied", "had been applying", "am applying"], correctIndex: 2 },
  { id: "u9q4", unit: 9,
    questionText: "He claimed to ___ the answer all along.",
    options: ["know", "have known", "knowing", "known"], correctIndex: 1 },
  { id: "u9q5", unit: 9,
    questionText: "She warned me ___ trust him.",
    options: ["don't", "not", "not to", "to not"], correctIndex: 2 },
  { id: "u9q6", unit: 9,
    questionText: "They admitted ___ the mistake.",
    options: ["make", "to make", "making", "made"], correctIndex: 2 },
  { id: "u9q7", unit: 9,
    questionText: "He told me that he ___ to resign the following week.",
    options: ["is planning", "plans", "had been planning", "was planning"], correctIndex: 3 },
  { id: "u9q8", unit: 9,
    questionText: "She asked whether I ___ interested in the position.",
    options: ["am", "was", "had been", "were"], correctIndex: 1 },
  { id: "u9q9", unit: 9,
    questionText: "He confessed to ___ the money from his employer.",
    options: ["steal", "stolen", "having stolen", "have stolen"], correctIndex: 2 },
  { id: "u9q10", unit: 9,
    questionText: "She reminded me ___ the report before lunch.",
    options: ["finish", "finishing", "to finish", "finished"], correctIndex: 2 },

  // ── Unit 10 – Advanced relative clauses ──────────────────────────────────
  { id: "u10q1", unit: 10,
    questionText: "The town ___ I grew up has changed a lot.",
    options: ["which", "that", "where", "who"], correctIndex: 2 },
  { id: "u10q2", unit: 10,
    questionText: "She gave me a book, ___ I found extremely helpful.",
    options: ["that", "who", "which", "what"], correctIndex: 2 },
  { id: "u10q3", unit: 10,
    questionText: "That is the company for ___ she works.",
    options: ["that", "which", "who", "what"], correctIndex: 1 },
  { id: "u10q4", unit: 10,
    questionText: "___ I find most interesting is her attitude.",
    options: ["That", "Which", "What", "Who"], correctIndex: 2 },
  { id: "u10q5", unit: 10,
    questionText: "He's the man ___ car was stolen last week.",
    options: ["who", "which", "that", "whose"], correctIndex: 3 },
  { id: "u10q6", unit: 10,
    questionText: "The reason ___ she left is still a mystery.",
    options: ["which", "that", "why", "where"], correctIndex: 2 },
  { id: "u10q7", unit: 10,
    questionText: "This is the hotel ___ we stayed last summer.",
    options: ["which", "who", "where", "that"], correctIndex: 2 },
  { id: "u10q8", unit: 10,
    questionText: "Everything ___ he said turned out to be true.",
    options: ["which", "who", "that", "what"], correctIndex: 2 },
  { id: "u10q9", unit: 10,
    questionText: "She's someone on ___ you can always rely.",
    options: ["that", "whom", "who", "which"], correctIndex: 1 },
  { id: "u10q10", unit: 10,
    questionText: "The year ___ she was born, the war ended.",
    options: ["which", "that", "when", "where"], correctIndex: 2 },

  // ── Unit 11 – Inversion and emphasis ─────────────────────────────────────
  { id: "u11q1", unit: 11,
    questionText: "Never ___ such a beautiful sunset.",
    options: ["I have seen", "have I seen", "I saw", "did I see"], correctIndex: 1 },
  { id: "u11q2", unit: 11,
    questionText: "Not only ___ late, but he also forgot his homework.",
    options: ["he was", "he is", "was he", "is he"], correctIndex: 2 },
  { id: "u11q3", unit: 11,
    questionText: "It ___ John who solved the problem.",
    options: ["is", "was", "has been", "were"], correctIndex: 1 },
  { id: "u11q4", unit: 11,
    questionText: "Hardly ___ sat down when the phone rang.",
    options: ["I had", "had I", "I have", "have I"], correctIndex: 1 },
  { id: "u11q5", unit: 11,
    questionText: "___ is the history that makes this place special.",
    options: ["It", "That", "This", "What"], correctIndex: 3 },
  { id: "u11q6", unit: 11,
    questionText: "Under no circumstances ___ leave the building.",
    options: ["you should", "should you", "you must", "must you"], correctIndex: 1 },
  { id: "u11q7", unit: 11,
    questionText: "Only after the meeting ___ what had happened.",
    options: ["I understood", "did I understand", "I did understand", "understood I"], correctIndex: 1 },
  { id: "u11q8", unit: 11,
    questionText: "What I ___ is a good night's sleep.",
    options: ["need", "needs", "am needing", "have needed"], correctIndex: 0 },
  { id: "u11q9", unit: 11,
    questionText: "Little ___ that she was being followed.",
    options: ["she knew", "did she know", "she did know", "knew she"], correctIndex: 1 },
  { id: "u11q10", unit: 11,
    questionText: "Seldom ___ such dedication in a student.",
    options: ["I have seen", "have I seen", "I see", "do I see"], correctIndex: 1 },

  // ── Unit 12 – Participle clauses and advanced grammar ─────────────────────
  { id: "u12q1", unit: 12,
    questionText: "___ the instructions carefully, she assembled the furniture.",
    options: ["Read", "Reading", "Having read", "To read"], correctIndex: 2 },
  { id: "u12q2", unit: 12,
    questionText: "___ from a distance, the island looked deserted.",
    options: ["Seeing", "Seen", "Having seen", "To see"], correctIndex: 1 },
  { id: "u12q3", unit: 12,
    questionText: "She sat in the garden, ___ a book.",
    options: ["reads", "read", "to read", "reading"], correctIndex: 3 },
  { id: "u12q4", unit: 12,
    questionText: "___ about the delay, the passengers grew angry.",
    options: ["Told", "Telling", "Having told", "To tell"], correctIndex: 0 },
  { id: "u12q5", unit: 12,
    questionText: "The report, ___ by the committee, was rejected.",
    options: ["writing", "written", "having written", "to write"], correctIndex: 1 },
  { id: "u12q6", unit: 12,
    questionText: "He walked out of the office, ___ the door behind him.",
    options: ["slammed", "slam", "slamming", "to slam"], correctIndex: 2 },
  { id: "u12q7", unit: 12,
    questionText: "___ in a small village, she always dreamed of city life.",
    options: ["Grown up", "Growing up", "Having grown up", "To grow up"], correctIndex: 2 },
  { id: "u12q8", unit: 12,
    questionText: "The man ___ by the window is my boss.",
    options: ["stands", "standing", "stood", "to stand"], correctIndex: 1 },
  { id: "u12q9", unit: 12,
    questionText: "___ what to do, she called her friend.",
    options: ["Not knowing", "Known", "Not known", "Knowing not"], correctIndex: 0 },
  { id: "u12q10", unit: 12,
    questionText: "The painting ___ by Picasso sold for millions.",
    options: ["creating", "created", "having created", "to create"], correctIndex: 1 },
];

export function getQuestionsForUpperIntermediateQuiz(quizId: number): PracticeQuestion[] {
  const quiz = UPPER_INTERMEDIATE_QUIZZES.find((q) => q.id === quizId);
  if (!quiz) return [];
  return questions.filter((q) => quiz.units.includes(q.unit));
}

export default questions;
