export interface PracticeQuestion {
  id: string;
  questionText: string;
  options: string[];
  correctIndex: number;
  unit: number;
}

export interface AdvancedQuiz {
  id: number; title: string; subtitle: string; units: number[]; label: string;
}

export const ADVANCED_QUIZZES: AdvancedQuiz[] = [
  { id: 1, title: "Quiz 1", subtitle: "Perfect Tenses & Complex Aspect",    units: [1, 2, 3],  label: "Units 1–3" },
  { id: 2, title: "Quiz 2", subtitle: "Conditionals, Subjunctive & Wish",   units: [4, 5, 6],  label: "Units 4–6" },
  { id: 3, title: "Quiz 3", subtitle: "Passives & Emphasis",                units: [7, 8],     label: "Units 7–8" },
  { id: 4, title: "Quiz 4", subtitle: "Discourse & Reported Speech",        units: [9, 10],    label: "Units 9–10" },
  { id: 5, title: "Quiz 5", subtitle: "Advanced Modals & Word Grammar",     units: [11, 12],   label: "Units 11–12" },
];

const questions: PracticeQuestion[] = [

  // ── Unit 1 – Perfect aspect (all tenses) ─────────────────────────────────
  { id: "a1q1", unit: 1,
    questionText: "She ___ in this city all her life, and she loves it.",
    options: ["lives", "is living", "has lived", "had lived"], correctIndex: 2 },
  { id: "a1q2", unit: 1,
    questionText: "By the time the rescue team arrived, the survivors ___ for days.",
    options: ["wait", "waited", "had been waiting", "were waiting"], correctIndex: 2 },
  { id: "a1q3", unit: 1,
    questionText: "She realised she ___ the wrong document to the client.",
    options: ["sends", "sent", "had sent", "was sending"], correctIndex: 2 },
  { id: "a1q4", unit: 1,
    questionText: "I can't believe you ___ the same mistake again!",
    options: ["made", "have made", "had made", "are making"], correctIndex: 1 },
  { id: "a1q5", unit: 1,
    questionText: "This time next year, they ___ in their new house for six months.",
    options: ["will live", "live", "will have been living", "are living"], correctIndex: 2 },
  { id: "a1q6", unit: 1,
    questionText: "He looked pale. It was clear that he ___ very little.",
    options: ["slept", "sleeps", "has slept", "had been sleeping"], correctIndex: 3 },
  { id: "a1q7", unit: 1,
    questionText: "The painting ___ to be a fake — experts confirmed it last week.",
    options: ["proves", "has proved", "proved", "had proved"], correctIndex: 1 },
  { id: "a1q8", unit: 1,
    questionText: "No sooner ___ the door than the alarm went off.",
    options: ["I opened", "did I open", "had I opened", "I had opened"], correctIndex: 2 },
  { id: "a1q9", unit: 1,
    questionText: "We ___ for the train for an hour when they announced a delay.",
    options: ["waited", "have waited", "had been waiting", "were waiting"], correctIndex: 2 },
  { id: "a1q10", unit: 1,
    questionText: "By next spring, the construction ___ for two years.",
    options: ["will go on", "will have been going on", "goes on", "is going on"], correctIndex: 1 },

  // ── Unit 2 – Aspect in context ────────────────────────────────────────────
  { id: "a2q1", unit: 2,
    questionText: "She ___ on this novel for three years. It's almost done.",
    options: ["works", "worked", "has been working", "had worked"], correctIndex: 2 },
  { id: "a2q2", unit: 2,
    questionText: "He ___ her somewhere before — her face was familiar.",
    options: ["sees", "saw", "has seen", "had seen"], correctIndex: 3 },
  { id: "a2q3", unit: 2,
    questionText: "The results show that temperatures ___ dramatically over the past century.",
    options: ["rise", "rose", "have risen", "had risen"], correctIndex: 2 },
  { id: "a2q4", unit: 2,
    questionText: "I'm exhausted. I ___ non-stop since 6 a.m.",
    options: ["work", "worked", "have been working", "had worked"], correctIndex: 2 },
  { id: "a2q5", unit: 2,
    questionText: "The economy ___ sharply in the first quarter, then stabilised.",
    options: ["declines", "has declined", "declined", "was declining"], correctIndex: 2 },
  { id: "a2q6", unit: 2,
    questionText: "By the deadline, she will ___ the entire database.",
    options: ["reorganise", "be reorganising", "have reorganised", "reorganised"], correctIndex: 2 },
  { id: "a2q7", unit: 2,
    questionText: "He ___ the company ever since he took over in 2010.",
    options: ["transforms", "has been transforming", "transformed", "was transforming"], correctIndex: 1 },
  { id: "a2q8", unit: 2,
    questionText: "Once she ___ her PhD, she plans to travel the world.",
    options: ["finishes", "will finish", "has finished", "finished"], correctIndex: 2 },
  { id: "a2q9", unit: 2,
    questionText: "The number of applicants ___ every year for the past decade.",
    options: ["grows", "grew", "has grown", "had grown"], correctIndex: 2 },
  { id: "a2q10", unit: 2,
    questionText: "I ___ you — why didn't you call?",
    options: ["expect", "was expecting", "have been expecting", "had expected"], correctIndex: 1 },

  // ── Unit 3 – Advanced narrative tenses ────────────────────────────────────
  { id: "a3q1", unit: 3,
    questionText: "She spoke with confidence, having ___ the speech many times.",
    options: ["rehearse", "rehearsed", "been rehearsing", "been rehearsed"], correctIndex: 1 },
  { id: "a3q2", unit: 3,
    questionText: "No sooner had we sat down ___ the lights went out.",
    options: ["when", "than", "as", "while"], correctIndex: 1 },
  { id: "a3q3", unit: 3,
    questionText: "He ___ the manuscript for years when he finally destroyed it.",
    options: ["wrote", "had been writing", "was writing", "has written"], correctIndex: 1 },
  { id: "a3q4", unit: 3,
    questionText: "Scarcely ___ the office when his phone rang.",
    options: ["he had left", "had he left", "he left", "did he leave"], correctIndex: 1 },
  { id: "a3q5", unit: 3,
    questionText: "She walked in to find that someone ___ through her desk.",
    options: ["rummaged", "was rummaging", "had been rummaging", "rummages"], correctIndex: 2 },
  { id: "a3q6", unit: 3,
    questionText: "He discovered that the report ___ without his knowledge.",
    options: ["filed", "was filing", "had been filed", "has been filed"], correctIndex: 2 },
  { id: "a3q7", unit: 3,
    questionText: "While ___ his email, he noticed something strange.",
    options: ["he checks", "checking", "he has checked", "checked"], correctIndex: 1 },
  { id: "a3q8", unit: 3,
    questionText: "The moment the doors opened, customers ___ in.",
    options: ["flood", "flooded", "were flooding", "had flooded"], correctIndex: 1 },
  { id: "a3q9", unit: 3,
    questionText: "By the time the investigation concluded, the suspect ___.",
    options: ["escaped", "has escaped", "had escaped", "was escaping"], correctIndex: 2 },
  { id: "a3q10", unit: 3,
    questionText: "___ several years abroad, he had a very different perspective.",
    options: ["After spent", "Having spent", "Having been spending", "After spending"], correctIndex: 1 },

  // ── Unit 4 – Complex and mixed conditionals ───────────────────────────────
  { id: "a4q1", unit: 4,
    questionText: "___ you to need help, don't hesitate to call.",
    options: ["Were", "Should", "Had", "Would"], correctIndex: 1 },
  { id: "a4q2", unit: 4,
    questionText: "___ I known about the risks, I would never have invested.",
    options: ["Were", "Should", "Would", "Had"], correctIndex: 3 },
  { id: "a4q3", unit: 4,
    questionText: "But for her intervention, the situation ___ much worse.",
    options: ["would be", "will be", "would have been", "had been"], correctIndex: 2 },
  { id: "a4q4", unit: 4,
    questionText: "If it weren't for the traffic, I ___ on time this morning.",
    options: ["would arrive", "had arrived", "would have arrived", "arrived"], correctIndex: 2 },
  { id: "a4q5", unit: 4,
    questionText: "Supposing you ___ discovered — what would you do?",
    options: ["were", "would be", "are", "had been"], correctIndex: 0 },
  { id: "a4q6", unit: 4,
    questionText: "___ it not been for their support, the project would have failed.",
    options: ["Were", "Should", "Had", "Would"], correctIndex: 2 },
  { id: "a4q7", unit: 4,
    questionText: "Had she taken the medicine, she ___ better by now.",
    options: ["would feel", "would have felt", "feels", "felt"], correctIndex: 0 },
  { id: "a4q8", unit: 4,
    questionText: "Provided that everyone ___ on time, we can start immediately.",
    options: ["arrives", "arrived", "will arrive", "would arrive"], correctIndex: 0 },
  { id: "a4q9", unit: 4,
    questionText: "On the condition that you ___ the terms, the deal is yours.",
    options: ["accept", "accepted", "will accept", "would accept"], correctIndex: 0 },
  { id: "a4q10", unit: 4,
    questionText: "Even if she ___ earlier, she wouldn't have caught the train.",
    options: ["left", "had left", "leaves", "would leave"], correctIndex: 1 },

  // ── Unit 5 – Subjunctive and formal grammar ───────────────────────────────
  { id: "a5q1", unit: 5,
    questionText: "It is essential that every student ___ the exam.",
    options: ["passes", "pass", "passed", "to pass"], correctIndex: 1 },
  { id: "a5q2", unit: 5,
    questionText: "The committee recommended that the policy ___ reviewed.",
    options: ["is", "was", "be", "should be"], correctIndex: 2 },
  { id: "a5q3", unit: 5,
    questionText: "I suggest that he ___ an appointment immediately.",
    options: ["makes", "make", "made", "should make"], correctIndex: 1 },
  { id: "a5q4", unit: 5,
    questionText: "It is vital that the information ___ confidential.",
    options: ["remains", "remain", "remained", "would remain"], correctIndex: 1 },
  { id: "a5q5", unit: 5,
    questionText: "He insisted that his lawyer ___ present at all times.",
    options: ["is", "was", "be", "were"], correctIndex: 2 },
  { id: "a5q6", unit: 5,
    questionText: "If I ___ in your position, I'd ask for a raise.",
    options: ["am", "was", "were", "had been"], correctIndex: 2 },
  { id: "a5q7", unit: 5,
    questionText: "It is imperative that the form ___ before midnight.",
    options: ["submits", "submit", "submitted", "is submitted"], correctIndex: 3 },
  { id: "a5q8", unit: 5,
    questionText: "The judge ordered that the evidence ___ destroyed.",
    options: ["is not", "was not", "not be", "should not"], correctIndex: 2 },
  { id: "a5q9", unit: 5,
    questionText: "She demanded that he ___ an apology.",
    options: ["gives", "give", "gave", "would give"], correctIndex: 1 },
  { id: "a5q10", unit: 5,
    questionText: "It is crucial that this information ___ public.",
    options: ["doesn't become", "not become", "won't become", "isn't becoming"], correctIndex: 1 },

  // ── Unit 6 – Wish and hypothetical meaning ────────────────────────────────
  { id: "a6q1", unit: 6,
    questionText: "I wish you ___ stop interrupting me!",
    options: ["will", "can", "would", "could"], correctIndex: 2 },
  { id: "a6q2", unit: 6,
    questionText: "If only the government ___ action sooner.",
    options: ["takes", "took", "had taken", "would take"], correctIndex: 2 },
  { id: "a6q3", unit: 6,
    questionText: "She wishes she ___ him — it caused so much trouble.",
    options: ["didn't trust", "doesn't trust", "hadn't trusted", "won't trust"], correctIndex: 2 },
  { id: "a6q4", unit: 6,
    questionText: "It's high time the company ___ its practices.",
    options: ["changes", "changed", "has changed", "would change"], correctIndex: 1 },
  { id: "a6q5", unit: 6,
    questionText: "I'd sooner you ___ mention this to anyone.",
    options: ["don't", "didn't", "hadn't", "wouldn't"], correctIndex: 1 },
  { id: "a6q6", unit: 6,
    questionText: "Suppose she ___ out — what would the consequences be?",
    options: ["found", "finds", "had found", "would find"], correctIndex: 0 },
  { id: "a6q7", unit: 6,
    questionText: "He acts as if he ___ everything.",
    options: ["knows", "knew", "had known", "would know"], correctIndex: 1 },
  { id: "a6q8", unit: 6,
    questionText: "I wish there ___ more I could do to help.",
    options: ["is", "was", "were", "had been"], correctIndex: 2 },
  { id: "a6q9", unit: 6,
    questionText: "She looked as though she ___ for hours.",
    options: ["cries", "cried", "had been crying", "was going to cry"], correctIndex: 2 },
  { id: "a6q10", unit: 6,
    questionText: "I'd rather she ___ a different approach.",
    options: ["takes", "take", "took", "had taken"], correctIndex: 2 },

  // ── Unit 7 – Complex passives ─────────────────────────────────────────────
  { id: "a7q1", unit: 7,
    questionText: "The contract is said ___ signed next week.",
    options: ["to be", "to have been", "being", "having been"], correctIndex: 0 },
  { id: "a7q2", unit: 7,
    questionText: "He is believed ___ the country last night.",
    options: ["to leave", "to have left", "leaving", "having left"], correctIndex: 1 },
  { id: "a7q3", unit: 7,
    questionText: "The company is reported ___ millions in losses.",
    options: ["to incur", "to have incurred", "incurring", "having incurred"], correctIndex: 1 },
  { id: "a7q4", unit: 7,
    questionText: "The new policy ___ implemented without proper consultation.",
    options: ["is being", "had been", "was", "has been"], correctIndex: 1 },
  { id: "a7q5", unit: 7,
    questionText: "She had her work ___ by her manager.",
    options: ["check", "to check", "checking", "checked"], correctIndex: 3 },
  { id: "a7q6", unit: 7,
    questionText: "It ___ that she knew more than she was letting on.",
    options: ["appears", "is appeared", "is appearing", "appeared"], correctIndex: 0 },
  { id: "a7q7", unit: 7,
    questionText: "Nothing ___ been done about the problem despite repeated warnings.",
    options: ["is", "was", "has", "had"], correctIndex: 2 },
  { id: "a7q8", unit: 7,
    questionText: "The suspect is alleged ___ at the scene that night.",
    options: ["to be", "to have been", "being", "having been"], correctIndex: 1 },
  { id: "a7q9", unit: 7,
    questionText: "The deal ___ finalised when the market crashed.",
    options: ["was being", "had been", "was", "is being"], correctIndex: 0 },
  { id: "a7q10", unit: 7,
    questionText: "His motives are thought ___ financial.",
    options: ["to be", "to have been", "being", "as being"], correctIndex: 0 },

  // ── Unit 8 – Emphasis and inversion (advanced) ────────────────────────────
  { id: "a8q1", unit: 8,
    questionText: "Never before ___ such widespread protests.",
    options: ["there have been", "there were", "have there been", "were there"], correctIndex: 2 },
  { id: "a8q2", unit: 8,
    questionText: "Not until she spoke ___ who she was.",
    options: ["I realised", "did I realise", "I did realise", "realised I"], correctIndex: 1 },
  { id: "a8q3", unit: 8,
    questionText: "___ is the way it's presented that makes the difference.",
    options: ["It", "That", "This", "What"], correctIndex: 0 },
  { id: "a8q4", unit: 8,
    questionText: "Only rarely ___ a discovery of this magnitude.",
    options: ["scientists make", "do scientists make", "scientists have made", "have scientists made"], correctIndex: 1 },
  { id: "a8q5", unit: 8,
    questionText: "What ___ is a complete overhaul of the system.",
    options: ["we need", "needs we", "do we need", "we do need"], correctIndex: 0 },
  { id: "a8q6", unit: 8,
    questionText: "So ___ the news that nobody could speak.",
    options: ["shocking it was", "was the news shocking", "shocking was the news", "was it shocking"], correctIndex: 2 },
  { id: "a8q7", unit: 8,
    questionText: "Under no circumstances ___ this information shared.",
    options: ["this should be", "should this be", "this must be", "must this be"], correctIndex: 1 },
  { id: "a8q8", unit: 8,
    questionText: "___ her complete dedication that brought about success.",
    options: ["That was", "What was", "It was", "There was"], correctIndex: 2 },
  { id: "a8q9", unit: 8,
    questionText: "Rarely ___ so moved by a piece of music.",
    options: ["I have been", "have I been", "I was", "was I"], correctIndex: 1 },
  { id: "a8q10", unit: 8,
    questionText: "The fact ___ she didn't call worries me.",
    options: ["which", "that", "what", "as"], correctIndex: 1 },

  // ── Unit 9 – Discourse markers ────────────────────────────────────────────
  { id: "a9q1", unit: 9,
    questionText: "The plan is risky; ___, it could work if executed well.",
    options: ["therefore", "however", "moreover", "nevertheless"], correctIndex: 3 },
  { id: "a9q2", unit: 9,
    questionText: "She worked hard. ___, she failed the exam.",
    options: ["Nevertheless", "Therefore", "Furthermore", "Consequently"], correctIndex: 0 },
  { id: "a9q3", unit: 9,
    questionText: "He's intelligent. ___, he's extremely hard-working.",
    options: ["However", "Nevertheless", "Furthermore", "Otherwise"], correctIndex: 2 },
  { id: "a9q4", unit: 9,
    questionText: "The project was completed late; ___, the client was satisfied.",
    options: ["therefore", "consequently", "nonetheless", "moreover"], correctIndex: 2 },
  { id: "a9q5", unit: 9,
    questionText: "She failed to submit the form. ___, her application was rejected.",
    options: ["Nevertheless", "Consequently", "Furthermore", "Albeit"], correctIndex: 1 },
  { id: "a9q6", unit: 9,
    questionText: "The report was thorough, ___ lacking in certain key areas.",
    options: ["albeit", "nevertheless", "therefore", "furthermore"], correctIndex: 0 },
  { id: "a9q7", unit: 9,
    questionText: "He works long hours; ___, he finds time for his family.",
    options: ["consequently", "furthermore", "nonetheless", "therefore"], correctIndex: 2 },
  { id: "a9q8", unit: 9,
    questionText: "The findings were unexpected. ___, they changed everything.",
    options: ["Furthermore", "Nevertheless", "As a result", "Albeit"], correctIndex: 2 },
  { id: "a9q9", unit: 9,
    questionText: "She agreed, ___ with some reservations.",
    options: ["albeit", "consequently", "therefore", "furthermore"], correctIndex: 0 },
  { id: "a9q10", unit: 9,
    questionText: "The economy is growing; ___, unemployment remains high.",
    options: ["moreover", "therefore", "however", "consequently"], correctIndex: 2 },

  // ── Unit 10 – Advanced reported speech ───────────────────────────────────
  { id: "a10q1", unit: 10,
    questionText: "He is alleged to ___ the fraud for years.",
    options: ["perpetrate", "have perpetrated", "perpetrating", "be perpetrating"], correctIndex: 1 },
  { id: "a10q2", unit: 10,
    questionText: "She vowed that she ___ reveal the source under any circumstances.",
    options: ["didn't", "won't", "wouldn't", "hasn't"], correctIndex: 2 },
  { id: "a10q3", unit: 10,
    questionText: "The spokesperson refused to comment, saying investigations ___.",
    options: ["are ongoing", "were ongoing", "have been ongoing", "had been ongoing"], correctIndex: 1 },
  { id: "a10q4", unit: 10,
    questionText: "He maintained that he ___ alone at the time of the incident.",
    options: ["is", "was", "had been", "were"], correctIndex: 2 },
  { id: "a10q5", unit: 10,
    questionText: "She claimed to ___ the manuscript before it was published.",
    options: ["see", "have seen", "be seeing", "have been seeing"], correctIndex: 1 },
  { id: "a10q6", unit: 10,
    questionText: "He denied ___ any knowledge of the plan.",
    options: ["to have", "having", "have", "having had"], correctIndex: 3 },
  { id: "a10q7", unit: 10,
    questionText: "The minister announced that taxes ___ the following year.",
    options: ["will rise", "rise", "would rise", "had risen"], correctIndex: 2 },
  { id: "a10q8", unit: 10,
    questionText: "She let it be known that she ___ to run for office.",
    options: ["intends", "intended", "has intended", "had intended"], correctIndex: 1 },
  { id: "a10q9", unit: 10,
    questionText: "He conceded that the strategy ___ more carefully.",
    options: ["should plan", "should be planned", "should have been planned", "should be planning"], correctIndex: 2 },
  { id: "a10q10", unit: 10,
    questionText: "They acknowledged that mistakes ___ in the report.",
    options: ["are made", "were made", "have been made", "had been made"], correctIndex: 3 },

  // ── Unit 11 – Advanced modal verbs ───────────────────────────────────────
  { id: "a11q1", unit: 11,
    questionText: "You ___ as well wait here — the next bus won't be long.",
    options: ["could", "might", "may", "might just as"], correctIndex: 1 },
  { id: "a11q2", unit: 11,
    questionText: "She ___ well be the most talented musician I've ever heard.",
    options: ["could", "might", "may", "must"], correctIndex: 1 },
  { id: "a11q3", unit: 11,
    questionText: "He ___ have known about it — he was right there.",
    options: ["must", "should", "ought to", "would"], correctIndex: 0 },
  { id: "a11q4", unit: 11,
    questionText: "This ___ not be the right address — let me double-check.",
    options: ["might", "must", "could", "should"], correctIndex: 0 },
  { id: "a11q5", unit: 11,
    questionText: "She ___ have succeeded had she been given better support.",
    options: ["can", "could", "might", "should"], correctIndex: 1 },
  { id: "a11q6", unit: 11,
    questionText: "You ___ be joking! That's absolutely absurd.",
    options: ["can", "must", "might", "should"], correctIndex: 1 },
  { id: "a11q7", unit: 11,
    questionText: "He ___ have taken offence — I'll call and apologise.",
    options: ["might", "must", "could", "should"], correctIndex: 0 },
  { id: "a11q8", unit: 11,
    questionText: "This strategy ___ have been more carefully thought out.",
    options: ["may", "might", "should", "would"], correctIndex: 2 },
  { id: "a11q9", unit: 11,
    questionText: "I ___ as well tell you now — it'll come out eventually.",
    options: ["might", "could", "may", "should"], correctIndex: 0 },
  { id: "a11q10", unit: 11,
    questionText: "You ___ have consulted her first — that was a big oversight.",
    options: ["can", "could", "would", "ought to"], correctIndex: 3 },

  // ── Unit 12 – Nominalisation and formal structures ────────────────────────
  { id: "a12q1", unit: 12,
    questionText: "The ___ of the new policy was met with widespread opposition. (introduce)",
    options: ["introduction", "introducing", "introduced", "introduces"], correctIndex: 0 },
  { id: "a12q2", unit: 12,
    questionText: "Her ___ to detail is what makes her an outstanding researcher. (attend)",
    options: ["attending", "attended", "attention", "attend"], correctIndex: 2 },
  { id: "a12q3", unit: 12,
    questionText: "The ___ of the investigation has caused significant delays. (complex)",
    options: ["complex", "complexing", "complexity", "complexed"], correctIndex: 2 },
  { id: "a12q4", unit: 12,
    questionText: "There was a significant ___ in productivity after the changes. (improve)",
    options: ["improving", "improved", "improvement", "improve"], correctIndex: 2 },
  { id: "a12q5", unit: 12,
    questionText: "His ___ of the situation was remarkably accurate. (assess)",
    options: ["assessing", "assessed", "assess", "assessment"], correctIndex: 3 },
  { id: "a12q6", unit: 12,
    questionText: "The ___ of these findings will take several months. (verify)",
    options: ["verifying", "verified", "verification", "verify"], correctIndex: 2 },
  { id: "a12q7", unit: 12,
    questionText: "She showed great ___ in dealing with the crisis. (resilient)",
    options: ["resilient", "resiliently", "resilience", "resiliency"], correctIndex: 2 },
  { id: "a12q8", unit: 12,
    questionText: "The committee called for greater ___ in decision-making. (transparent)",
    options: ["transparent", "transparently", "transparence", "transparency"], correctIndex: 3 },
  { id: "a12q9", unit: 12,
    questionText: "The ___ of evidence against him was overwhelming. (accumulate)",
    options: ["accumulating", "accumulated", "accumulation", "accumulates"], correctIndex: 2 },
  { id: "a12q10", unit: 12,
    questionText: "Her ___ of the text revealed several hidden meanings. (interpret)",
    options: ["interpreting", "interpreted", "interpretive", "interpretation"], correctIndex: 3 },
];

export function getQuestionsForAdvancedQuiz(quizId: number): PracticeQuestion[] {
  const quiz = ADVANCED_QUIZZES.find((q) => q.id === quizId);
  if (!quiz) return [];
  return questions.filter((q) => quiz.units.includes(q.unit));
}

export default questions;
