export interface PracticeQuestion {
  id: string;
  questionText: string;
  options: string[];
  correctIndex: number;
  unit: number;
}

export interface ElementaryQuiz {
  id: number;
  title: string;
  subtitle: string;
  units: number[];
  label: string;
}

export const ELEMENTARY_QUIZZES: ElementaryQuiz[] = [
  { id: 1, title: "Quiz 1", subtitle: "Verb To Be & Present Simple", units: [1, 2, 3], label: "Units 1–3" },
  { id: 2, title: "Quiz 2", subtitle: "Likes, Places & Can",         units: [4, 5, 6], label: "Units 4–6" },
  { id: 3, title: "Quiz 3", subtitle: "Past Simple",                 units: [7, 8],    label: "Units 7–8" },
  { id: 4, title: "Quiz 4", subtitle: "Some/Any & Comparatives",     units: [9, 10],   label: "Units 9–10" },
  { id: 5, title: "Quiz 5", subtitle: "Present Continuous & Future", units: [11, 12],  label: "Units 11–12" },
];

const questions: PracticeQuestion[] = [

  // ── Unit 1 – Verb to be, countries, adjectives ────────────────────────────
  { id: "e1q1", unit: 1,
    questionText: "My name ___ Anna.",
    options: ["are", "am", "is", "be"], correctIndex: 2 },
  { id: "e1q2", unit: 1,
    questionText: "They ___ from Japan.",
    options: ["is", "am", "are", "be"], correctIndex: 2 },
  { id: "e1q3", unit: 1,
    questionText: "He ___ a doctor. He's a teacher.",
    options: ["am not", "aren't", "not", "isn't"], correctIndex: 3 },
  { id: "e1q4", unit: 1,
    questionText: "'Is Rome in Spain?' 'No, it ___.'",
    options: ["is", "aren't", "isn't", "am not"], correctIndex: 2 },
  { id: "e1q5", unit: 1,
    questionText: "'How ___ you?' 'Fine, thanks.'",
    options: ["is", "am", "are", "do"], correctIndex: 2 },
  { id: "e1q6", unit: 1,
    questionText: "___ her name Elena? Yes, it is.",
    options: ["Am", "Are", "Is", "Be"], correctIndex: 2 },
  { id: "e1q7", unit: 1,
    questionText: "She's from China. She's ___.",
    options: ["Korean", "Japanese", "Chinese", "Taiwanese"], correctIndex: 2 },
  { id: "e1q8", unit: 1,
    questionText: "'Are you married?' 'No, I'm ___.'",
    options: ["alone", "single", "one", "solo"], correctIndex: 1 },
  { id: "e1q9", unit: 1,
    questionText: "We ___ students. We're teachers.",
    options: ["is", "am", "aren't", "isn't"], correctIndex: 2 },
  { id: "e1q10", unit: 1,
    questionText: "London is the ___ of England.",
    options: ["country", "capital", "village", "place"], correctIndex: 1 },

  // ── Unit 2 – Present simple I/you/we/they ────────────────────────────────
  { id: "e2q1", unit: 2,
    questionText: "I ___ English at school.",
    options: ["speaks", "speaking", "to speak", "speak"], correctIndex: 3 },
  { id: "e2q2", unit: 2,
    questionText: "They ___ in a flat in London.",
    options: ["lives", "live", "is living", "to live"], correctIndex: 1 },
  { id: "e2q3", unit: 2,
    questionText: "Do you like coffee? Yes, I ___.",
    options: ["does", "am", "do", "like"], correctIndex: 2 },
  { id: "e2q4", unit: 2,
    questionText: "We ___ have a car. We use the bus.",
    options: ["doesn't", "aren't", "don't", "not"], correctIndex: 2 },
  { id: "e2q5", unit: 2,
    questionText: "What ___ you do? I'm a teacher.",
    options: ["is", "does", "are", "do"], correctIndex: 3 },
  { id: "e2q6", unit: 2,
    questionText: "Where ___ they live? In Paris.",
    options: ["does", "is", "do", "are"], correctIndex: 2 },
  { id: "e2q7", unit: 2,
    questionText: "I ___ to music every evening.",
    options: ["listens", "listening", "listen", "listened"], correctIndex: 2 },
  { id: "e2q8", unit: 2,
    questionText: "They don't ___ football. They play tennis.",
    options: ["plays", "playing", "play", "played"], correctIndex: 2 },
  { id: "e2q9", unit: 2,
    questionText: "Do you ___ Japanese? Yes, a little.",
    options: ["talking", "talks", "speak", "spoke"], correctIndex: 2 },
  { id: "e2q10", unit: 2,
    questionText: "We ___ at 7 o'clock every morning.",
    options: ["gets up", "get up", "getting up", "got up"], correctIndex: 1 },

  // ── Unit 3 – Present simple he/she/it ────────────────────────────────────
  { id: "e3q1", unit: 3,
    questionText: "She ___ in a hospital.",
    options: ["work", "working", "works", "worked"], correctIndex: 2 },
  { id: "e3q2", unit: 3,
    questionText: "He ___ speak French. He speaks Spanish.",
    options: ["don't", "isn't", "doesn't", "not"], correctIndex: 2 },
  { id: "e3q3", unit: 3,
    questionText: "Does Maria live in Rome? No, she ___.",
    options: ["don't", "isn't", "doesn't", "not"], correctIndex: 2 },
  { id: "e3q4", unit: 3,
    questionText: "What does he ___? He's a chef.",
    options: ["make", "work", "does", "do"], correctIndex: 3 },
  { id: "e3q5", unit: 3,
    questionText: "She ___ to work by bus.",
    options: ["go", "goes", "going", "went"], correctIndex: 1 },
  { id: "e3q6", unit: 3,
    questionText: "My sister ___ two children.",
    options: ["have", "is having", "has", "are having"], correctIndex: 2 },
  { id: "e3q7", unit: 3,
    questionText: "He ___ TV every evening.",
    options: ["watch", "watching", "watches", "watched"], correctIndex: 2 },
  { id: "e3q8", unit: 3,
    questionText: "___ your mother speak English? Yes, she does.",
    options: ["Do", "Is", "Has", "Does"], correctIndex: 3 },
  { id: "e3q9", unit: 3,
    questionText: "She doesn't ___ meat. She's vegetarian.",
    options: ["eats", "eating", "ate", "eat"], correctIndex: 3 },
  { id: "e3q10", unit: 3,
    questionText: "He ___ home at 6 o'clock every day.",
    options: ["get", "getting", "gets", "got"], correctIndex: 2 },

  // ── Unit 4 – like + -ing, frequency adverbs ──────────────────────────────
  { id: "e4q1", unit: 4,
    questionText: "I love ___.",
    options: ["swim", "to swim", "swimming", "swam"], correctIndex: 2 },
  { id: "e4q2", unit: 4,
    questionText: "She doesn't like ___.",
    options: ["cook", "cooks", "cooked", "cooking"], correctIndex: 3 },
  { id: "e4q3", unit: 4,
    questionText: "Do you like ___? Yes, I love it!",
    options: ["dance", "to dancing", "dancing", "danced"], correctIndex: 2 },
  { id: "e4q4", unit: 4,
    questionText: "He ___ plays tennis. He plays every day.",
    options: ["never", "sometimes", "often", "always"], correctIndex: 3 },
  { id: "e4q5", unit: 4,
    questionText: "I ___ go to the cinema — maybe once a month.",
    options: ["always", "never", "sometimes", "usually"], correctIndex: 2 },
  { id: "e4q6", unit: 4,
    questionText: "What do you enjoy ___?",
    options: ["to do", "do", "does", "doing"], correctIndex: 3 },
  { id: "e4q7", unit: 4,
    questionText: "She likes ___ early in the morning.",
    options: ["run", "to running", "running", "ran"], correctIndex: 2 },
  { id: "e4q8", unit: 4,
    questionText: "They ___ go abroad. They prefer staying home.",
    options: ["always", "never", "usually", "often"], correctIndex: 1 },
  { id: "e4q9", unit: 4,
    questionText: "Do you enjoy ___?",
    options: ["cook", "cooking", "to cooking", "cooked"], correctIndex: 1 },
  { id: "e4q10", unit: 4,
    questionText: "He hates ___ early.",
    options: ["gets up", "get up", "getting up", "to getting up"], correctIndex: 2 },

  // ── Unit 5 – There is/are, prepositions, this/that/these/those ───────────
  { id: "e5q1", unit: 5,
    questionText: "___ a supermarket near here?",
    options: ["Is there", "There is", "Are there", "There are"], correctIndex: 0 },
  { id: "e5q2", unit: 5,
    questionText: "There ___ two cinemas in our town.",
    options: ["is", "isn't", "are", "aren't"], correctIndex: 2 },
  { id: "e5q3", unit: 5,
    questionText: "The bank is ___ the post office and the library.",
    options: ["in", "next to", "between", "on"], correctIndex: 2 },
  { id: "e5q4", unit: 5,
    questionText: "'___ are my friends Anna and Tom.'",
    options: ["These", "Those", "This", "That"], correctIndex: 0 },
  { id: "e5q5", unit: 5,
    questionText: "There ___ a park near the school.",
    options: ["are", "aren't", "isn't", "is"], correctIndex: 3 },
  { id: "e5q6", unit: 5,
    questionText: "The shop is on the ___.",
    options: ["right", "straight", "direct", "forward"], correctIndex: 0 },
  { id: "e5q7", unit: 5,
    questionText: "Is there a café near here? Yes, there ___.",
    options: ["are", "aren't", "isn't", "is"], correctIndex: 3 },
  { id: "e5q8", unit: 5,
    questionText: "The hotel is ___ the station.",
    options: ["to", "at", "opposite", "of"], correctIndex: 2 },
  { id: "e5q9", unit: 5,
    questionText: "___ any students in the classroom?",
    options: ["Is there", "Are there", "There are", "There is"], correctIndex: 1 },
  { id: "e5q10", unit: 5,
    questionText: "'___ is that building?' 'It's the town hall.'",
    options: ["These", "Those", "This", "What"], correctIndex: 3 },

  // ── Unit 6 – Can/can't, requests ─────────────────────────────────────────
  { id: "e6q1", unit: 6,
    questionText: "___ you speak Italian? No, I can't.",
    options: ["Do", "Are", "Can", "Have"], correctIndex: 2 },
  { id: "e6q2", unit: 6,
    questionText: "She can ___ very well.",
    options: ["to swim", "swims", "swimming", "swim"], correctIndex: 3 },
  { id: "e6q3", unit: 6,
    questionText: "Can I have a coffee, ___?",
    options: ["thanks", "please", "sorry", "pardon"], correctIndex: 1 },
  { id: "e6q4", unit: 6,
    questionText: "'___ I sit here?' 'Yes, of course.'",
    options: ["Do", "Are", "Can", "Have"], correctIndex: 2 },
  { id: "e6q5", unit: 6,
    questionText: "He ___ drive. He doesn't have a licence.",
    options: ["can", "can't", "doesn't", "isn't"], correctIndex: 1 },
  { id: "e6q6", unit: 6,
    questionText: "'Can you help me?' '___, no problem.'",
    options: ["Sorry", "Please", "Sure", "Thanks"], correctIndex: 2 },
  { id: "e6q7", unit: 6,
    questionText: "___ you open the window, please?",
    options: ["Do", "Are", "Have", "Can"], correctIndex: 3 },
  { id: "e6q8", unit: 6,
    questionText: "They ___ speak three languages.",
    options: ["are", "do", "can", "have"], correctIndex: 2 },
  { id: "e6q9", unit: 6,
    questionText: "I ___ find my keys. Have you seen them?",
    options: ["can", "can't", "am not", "don't"], correctIndex: 1 },
  { id: "e6q10", unit: 6,
    questionText: "Can she cook? Yes, she ___.",
    options: ["does", "is", "can", "has"], correctIndex: 2 },

  // ── Unit 7 – Past simple was/were & regular verbs ────────────────────────
  { id: "e7q1", unit: 7,
    questionText: "I ___ at home yesterday evening.",
    options: ["am", "were", "was", "be"], correctIndex: 2 },
  { id: "e7q2", unit: 7,
    questionText: "They ___ at the party last night.",
    options: ["was", "is", "are", "were"], correctIndex: 3 },
  { id: "e7q3", unit: 7,
    questionText: "'Where ___ you born?' 'In Tokyo.'",
    options: ["did", "were", "was", "are"], correctIndex: 1 },
  { id: "e7q4", unit: 7,
    questionText: "She ___ tired, so she went to bed early.",
    options: ["is", "are", "were", "was"], correctIndex: 3 },
  { id: "e7q5", unit: 7,
    questionText: "He ___ at school yesterday. He was at home.",
    options: ["wasn't", "weren't", "isn't", "don't"], correctIndex: 0 },
  { id: "e7q6", unit: 7,
    questionText: "We ___ in Paris last summer. It was beautiful.",
    options: ["were", "was", "are", "be"], correctIndex: 0 },
  { id: "e7q7", unit: 7,
    questionText: "She ___ her friend yesterday.",
    options: ["visit", "visits", "visiting", "visited"], correctIndex: 3 },
  { id: "e7q8", unit: 7,
    questionText: "They ___ in the park for two hours.",
    options: ["walk", "walks", "walked", "walking"], correctIndex: 2 },
  { id: "e7q9", unit: 7,
    questionText: "I ___ a new dress for the party.",
    options: ["want", "wanting", "wants", "wanted"], correctIndex: 3 },
  { id: "e7q10", unit: 7,
    questionText: "He ___ work at 7 o'clock this morning.",
    options: ["start", "starts", "starting", "started"], correctIndex: 3 },

  // ── Unit 8 – Past simple irregular verbs ─────────────────────────────────
  { id: "e8q1", unit: 8,
    questionText: "She ___ to the cinema last night.",
    options: ["go", "goes", "going", "went"], correctIndex: 3 },
  { id: "e8q2", unit: 8,
    questionText: "We ___ a pizza for dinner last night.",
    options: ["eat", "ate", "eaten", "eated"], correctIndex: 1 },
  { id: "e8q3", unit: 8,
    questionText: "He ___ a new car last month.",
    options: ["buy", "buys", "buying", "bought"], correctIndex: 3 },
  { id: "e8q4", unit: 8,
    questionText: "'Did you see the film?' 'Yes, I ___.'",
    options: ["did", "do", "seen", "see"], correctIndex: 0 },
  { id: "e8q5", unit: 8,
    questionText: "She ___ to me yesterday.",
    options: ["speak", "speaks", "spoke", "spoken"], correctIndex: 2 },
  { id: "e8q6", unit: 8,
    questionText: "They ___ home late last night.",
    options: ["come", "came", "comed", "coming"], correctIndex: 1 },
  { id: "e8q7", unit: 8,
    questionText: "Did he go to the party? No, he ___.",
    options: ["don't", "didn't", "wasn't", "not"], correctIndex: 1 },
  { id: "e8q8", unit: 8,
    questionText: "I ___ a lot of money on my holiday.",
    options: ["spend", "spends", "spending", "spent"], correctIndex: 3 },
  { id: "e8q9", unit: 8,
    questionText: "She ___ him at university.",
    options: ["meet", "meets", "met", "meeting"], correctIndex: 2 },
  { id: "e8q10", unit: 8,
    questionText: "We ___ a great time at the concert.",
    options: ["have", "has", "had", "having"], correctIndex: 2 },

  // ── Unit 9 – Count/uncount nouns, some/any ───────────────────────────────
  { id: "e9q1", unit: 9,
    questionText: "Can I have ___ water, please?",
    options: ["a", "an", "some", "any"], correctIndex: 2 },
  { id: "e9q2", unit: 9,
    questionText: "There aren't ___ eggs in the fridge.",
    options: ["some", "a", "an", "any"], correctIndex: 3 },
  { id: "e9q3", unit: 9,
    questionText: "I'd like ___ orange, please.",
    options: ["a", "some", "an", "any"], correctIndex: 2 },
  { id: "e9q4", unit: 9,
    questionText: "Is there ___ milk? Yes, there's a little.",
    options: ["any", "some", "a", "an"], correctIndex: 0 },
  { id: "e9q5", unit: 9,
    questionText: "We need ___ bread for the sandwiches.",
    options: ["a", "an", "any", "some"], correctIndex: 3 },
  { id: "e9q6", unit: 9,
    questionText: "There's ___ coffee in the cup.",
    options: ["any", "a", "an", "some"], correctIndex: 3 },
  { id: "e9q7", unit: 9,
    questionText: "'Are there ___ biscuits?' 'No, there aren't any.'",
    options: ["some", "a", "an", "any"], correctIndex: 3 },
  { id: "e9q8", unit: 9,
    questionText: "She bought ___ new shoes yesterday.",
    options: ["any", "a", "an", "some"], correctIndex: 3 },
  { id: "e9q9", unit: 9,
    questionText: "I don't have ___ money.",
    options: ["some", "a", "an", "any"], correctIndex: 3 },
  { id: "e9q10", unit: 9,
    questionText: "Would you like ___ tea?",
    options: ["any", "a", "an", "some"], correctIndex: 3 },

  // ── Unit 10 – Comparative adjectives ─────────────────────────────────────
  { id: "e10q1", unit: 10,
    questionText: "London is ___ than my town.",
    options: ["big", "more big", "bigger", "biggest"], correctIndex: 2 },
  { id: "e10q2", unit: 10,
    questionText: "This test is ___ than yesterday's.",
    options: ["more easy", "easiest", "easy", "easier"], correctIndex: 3 },
  { id: "e10q3", unit: 10,
    questionText: "She's ___ than her sister.",
    options: ["taller", "more tall", "most tall", "tallest"], correctIndex: 0 },
  { id: "e10q4", unit: 10,
    questionText: "A car is ___ than a bicycle.",
    options: ["more fast", "fastest", "faster", "most fast"], correctIndex: 2 },
  { id: "e10q5", unit: 10,
    questionText: "This book is ___ than that one.",
    options: ["more interesting", "interestinger", "most interesting", "interesting"], correctIndex: 0 },
  { id: "e10q6", unit: 10,
    questionText: "He's ___ at English than I am.",
    options: ["good", "best", "better", "more good"], correctIndex: 2 },
  { id: "e10q7", unit: 10,
    questionText: "The weather today is ___ than yesterday.",
    options: ["worse", "more bad", "badder", "worst"], correctIndex: 0 },
  { id: "e10q8", unit: 10,
    questionText: "My flat is ___ than my office.",
    options: ["quiet", "more quiet", "quietest", "quieter"], correctIndex: 3 },
  { id: "e10q9", unit: 10,
    questionText: "Flying is ___ than going by train.",
    options: ["expensiver", "most expensive", "more expensive", "expensive"], correctIndex: 2 },
  { id: "e10q10", unit: 10,
    questionText: "This coffee is ___ than the other one.",
    options: ["more hot", "hotter", "hottest", "most hot"], correctIndex: 1 },

  // ── Unit 11 – Present continuous ─────────────────────────────────────────
  { id: "e11q1", unit: 11,
    questionText: "She ___ a book at the moment.",
    options: ["read", "reads", "is reading", "are reading"], correctIndex: 2 },
  { id: "e11q2", unit: 11,
    questionText: "What ___ you doing right now?",
    options: ["is", "are", "do", "does"], correctIndex: 1 },
  { id: "e11q3", unit: 11,
    questionText: "They ___ TV right now.",
    options: ["are watching", "watch", "watches", "watched"], correctIndex: 0 },
  { id: "e11q4", unit: 11,
    questionText: "I ___ to music. Please don't interrupt.",
    options: ["am listening", "listen", "listens", "listened"], correctIndex: 0 },
  { id: "e11q5", unit: 11,
    questionText: "'Where's Tom?' 'He ___ a shower.'",
    options: ["has", "have", "is having", "are having"], correctIndex: 2 },
  { id: "e11q6", unit: 11,
    questionText: "Look! It ___. We can't go out.",
    options: ["rain", "rains", "rained", "is raining"], correctIndex: 3 },
  { id: "e11q7", unit: 11,
    questionText: "She usually walks to work but today she ___.",
    options: ["drives", "is driving", "drove", "drive"], correctIndex: 1 },
  { id: "e11q8", unit: 11,
    questionText: "The children ___ in the garden right now.",
    options: ["play", "plays", "played", "are playing"], correctIndex: 3 },
  { id: "e11q9", unit: 11,
    questionText: "I can't talk now. I ___ dinner.",
    options: ["cook", "cooks", "cooked", "am cooking"], correctIndex: 3 },
  { id: "e11q10", unit: 11,
    questionText: "'Can I speak to John?' 'Sorry, he ___ a meeting.'",
    options: ["has", "have", "is having", "are having"], correctIndex: 2 },

  // ── Unit 12 – Going to (future) ───────────────────────────────────────────
  { id: "e12q1", unit: 12,
    questionText: "She ___ going to visit her parents next weekend.",
    options: ["am", "are", "is", "be"], correctIndex: 2 },
  { id: "e12q2", unit: 12,
    questionText: "We ___ going to have a party.",
    options: ["is", "am", "be", "are"], correctIndex: 3 },
  { id: "e12q3", unit: 12,
    questionText: "___ you going to see the film tonight?",
    options: ["Am", "Is", "Are", "Do"], correctIndex: 2 },
  { id: "e12q4", unit: 12,
    questionText: "He isn't going to ___ tomorrow. He's ill.",
    options: ["works", "working", "worked", "work"], correctIndex: 3 },
  { id: "e12q5", unit: 12,
    questionText: "What are they going to ___?",
    options: ["does", "did", "do", "doing"], correctIndex: 2 },
  { id: "e12q6", unit: 12,
    questionText: "I'm going to ___ a new phone next month.",
    options: ["buy", "buys", "buying", "bought"], correctIndex: 0 },
  { id: "e12q7", unit: 12,
    questionText: "Are you going to call him? No, I ___.",
    options: ["am not", "don't", "won't", "haven't"], correctIndex: 0 },
  { id: "e12q8", unit: 12,
    questionText: "They're going to ___ married next year.",
    options: ["get", "gets", "getting", "got"], correctIndex: 0 },
  { id: "e12q9", unit: 12,
    questionText: "It's going to ___! Look at those dark clouds.",
    options: ["rain", "rains", "raining", "rained"], correctIndex: 0 },
  { id: "e12q10", unit: 12,
    questionText: "She's going to ___ a doctor when she grows up.",
    options: ["is", "be", "been", "being"], correctIndex: 1 },
];

export function getQuestionsForElementaryQuiz(quizId: number): PracticeQuestion[] {
  const quiz = ELEMENTARY_QUIZZES.find((q) => q.id === quizId);
  if (!quiz) return [];
  return questions.filter((q) => quiz.units.includes(q.unit));
}

export default questions;
