import type { SeedVocabSection } from "../../../types/content";

export const weeks1to26: SeedVocabSection[] = [
  { weekNumber: 1, titleEn: "Week 1: Achievement", titleTk: "1-nji Hepde: Üstünlik", words: [
    { wordEn: "achieve", wordTk: "gazanmak / ýetmek", partOfSpeech: "verb", exampleEn: "She worked hard to achieve her goal.", exampleTk: "Ol maksadyna ýetmek üçin köp zähmet çekdi.", order: 1 },
    { wordEn: "accomplish", wordTk: "amala aşyrmak", partOfSpeech: "verb", exampleEn: "We accomplished a lot today.", exampleTk: "Biz bu gün köp zat amala aşyrdyk.", order: 2 },
    { wordEn: "effort", wordTk: "tagalla / zähmet", partOfSpeech: "noun", exampleEn: "Success requires a lot of effort.", exampleTk: "Üstünlik köp tagalla talap edýär.", order: 3 },
    { wordEn: "succeed", wordTk: "üstünlik gazanmak", partOfSpeech: "verb", exampleEn: "If you try hard, you will succeed.", exampleTk: "Köp synansaň, üstünlik gazanarsyň.", order: 4 },
    { wordEn: "capable", wordTk: "başarjaň / ukyply", partOfSpeech: "adjective", exampleEn: "She is capable of doing anything.", exampleTk: "Ol islendik zady başarýar.", order: 5 },
    { wordEn: "persist", wordTk: "dowam etmek / pes bolmazlyk", partOfSpeech: "verb", exampleEn: "Persist even when it is difficult.", exampleTk: "Kyn bolsa-da dowam et.", order: 6 },
    { wordEn: "result", wordTk: "netije", partOfSpeech: "noun", exampleEn: "The result was better than expected.", exampleTk: "Netije garaşylandan gowy boldy.", order: 7 },
    { wordEn: "progress", wordTk: "öňegidişlik / ösüş", partOfSpeech: "noun", exampleEn: "I can see your progress every day.", exampleTk: "Her gün öňegidişliligiňi görýärin.", order: 8 },
    { wordEn: "reward", wordTk: "sylag / baýrak", partOfSpeech: "noun", exampleEn: "Hard work has its own reward.", exampleTk: "Zähmetiň öz sylagynyň bardyr.", order: 9 },
    { wordEn: "attempt", wordTk: "synanyşmak / hereket etmek", partOfSpeech: "verb", exampleEn: "Don't be afraid to attempt new things.", exampleTk: "Täze zatlary synanyşmakdan gorkma.", order: 10 },
  ]},
  { weekNumber: 2, titleEn: "Week 2: Anger", titleTk: "2-nji Hepde: Gahar", words: [
    { wordEn: "angry", wordTk: "gaharlanmak / öýkeli", partOfSpeech: "adjective", exampleEn: "He was angry about the decision.", exampleTk: "Ol karar barada gaharlandy.", order: 1 },
    { wordEn: "furious", wordTk: "gaty gaharlanmak / öşerimek", partOfSpeech: "adjective", exampleEn: "She was furious when she heard the news.", exampleTk: "Habary eşidende ol gaty öşerdi.", order: 2 },
    { wordEn: "temper", wordTk: "gahar / huý", partOfSpeech: "noun", exampleEn: "He has a bad temper.", exampleTk: "Onuň erbet huýy bar.", order: 3 },
    { wordEn: "irritate", wordTk: "gaharyny getirmek / biynjalyk etmek", partOfSpeech: "verb", exampleEn: "Loud noise irritates me.", exampleTk: "Ýokary ses meniň gaharyny getirýär.", order: 4 },
    { wordEn: "rage", wordTk: "gazap / öfke", partOfSpeech: "noun", exampleEn: "He was filled with rage.", exampleTk: "Ol gazaba doldy.", order: 5 },
    { wordEn: "hostile", wordTk: "duşmançylykly / ýaramazja", partOfSpeech: "adjective", exampleEn: "Why are you being so hostile?", exampleTk: "Näme üçin bu derejede duşmançylykly?", order: 6 },
    { wordEn: "bitter", wordTk: "ajy / içi ýanýan", partOfSpeech: "adjective", exampleEn: "She felt bitter after losing.", exampleTk: "Ol utulandan soň içi ýandy.", order: 7 },
    { wordEn: "violent", wordTk: "zorly / şiddetli", partOfSpeech: "adjective", exampleEn: "Violent behaviour is never acceptable.", exampleTk: "Zorluk hiç wagt kabul edilip bilinmez.", order: 8 },
    { wordEn: "annoy", wordTk: "bizar etmek / biynjalyk etmek", partOfSpeech: "verb", exampleEn: "Stop annoying your sister!", exampleTk: "Uýaňy bizar etmegi bes et!", order: 9 },
    { wordEn: "fierce", wordTk: "ýowuz / wagşy", partOfSpeech: "adjective", exampleEn: "The fierce dog scared everyone.", exampleTk: "Ýowuz it hemmäni gorkuzdy.", order: 10 },
  ]},
  { weekNumber: 3, titleEn: "Week 3: Fear", titleTk: "3-nji Hepde: Gorky", words: [
    { wordEn: "afraid", wordTk: "gorkýan / howatyrlanýan", partOfSpeech: "adjective", exampleEn: "Are you afraid of the dark?", exampleTk: "Garagaraňkylydan gorkýarsyňyzmy?", order: 1 },
    { wordEn: "dread", wordTk: "gorky / elheder", partOfSpeech: "noun", exampleEn: "She felt dread before the exam.", exampleTk: "Synagdan öň oňa gorky aralaşdy.", order: 2 },
    { wordEn: "terror", wordTk: "howp / gorkunç", partOfSpeech: "noun", exampleEn: "The storm filled them with terror.", exampleTk: "Tupan olary gorkudan doldurdy.", order: 3 },
    { wordEn: "panic", wordTk: "howsala / weswese", partOfSpeech: "noun", exampleEn: "Don't panic — stay calm.", exampleTk: "Howsala düşme — köşeş.", order: 4 },
    { wordEn: "timid", wordTk: "gorkaklyk / utanjaňlyk", partOfSpeech: "adjective", exampleEn: "He was too timid to speak up.", exampleTk: "Ol geplemäge gaty gorkakdy.", order: 5 },
    { wordEn: "tremble", wordTk: "titremek / sandyramak", partOfSpeech: "verb", exampleEn: "Her hands trembled with fear.", exampleTk: "Elleri gorkudan titredi.", order: 6 },
    { wordEn: "horror", wordTk: "elheder / gorkunçlyk", partOfSpeech: "noun", exampleEn: "The horror film scared everyone.", exampleTk: "Gorkunç film hemmäni gorkuzdy.", order: 7 },
    { wordEn: "coward", wordTk: "gorkak", partOfSpeech: "noun", exampleEn: "Don't be a coward — be brave.", exampleTk: "Gorkak bolma — mert bol.", order: 8 },
    { wordEn: "escape", wordTk: "gaçmak / sypmak", partOfSpeech: "verb", exampleEn: "They managed to escape the fire.", partOfSpeech: "verb", exampleTk: "Olar ýangyndan gaçmagy başardylar.", order: 9 },
    { wordEn: "threat", wordTk: "howp / haýbat", partOfSpeech: "noun", exampleEn: "The storm was a threat to the village.", exampleTk: "Tupan oba howp döretdi.", order: 10 },
  ]},
  { weekNumber: 4, titleEn: "Week 4: Courage", titleTk: "4-nji Hepde: Mertlik", words: [
    { wordEn: "brave", wordTk: "mert / gaýduwsyz", partOfSpeech: "adjective", exampleEn: "Be brave — don't give up.", exampleTk: "Mert bol — pes bolma.", order: 1 },
    { wordEn: "bold", wordTk: "batyr / cesur", partOfSpeech: "adjective", exampleEn: "She made a bold decision.", exampleTk: "Ol batyrly karar kabul etdi.", order: 2 },
    { wordEn: "daring", wordTk: "batyrgaý / cesur", partOfSpeech: "adjective", exampleEn: "He attempted a daring rescue.", exampleTk: "Ol batyrgaý halas ediş synanyşygyny etdi.", order: 3 },
    { wordEn: "heroic", wordTk: "gahryman ýaly / edermen", partOfSpeech: "adjective", exampleEn: "Her heroic actions saved many lives.", exampleTk: "Onuň edermen hereketleri köp adamy halas etdi.", order: 4 },
    { wordEn: "fearless", wordTk: "gorksuz / batyr", partOfSpeech: "adjective", exampleEn: "The fearless soldier never retreated.", exampleTk: "Gorksuz esger hiç wagt yza çekilmedi.", order: 5 },
    { wordEn: "noble", wordTk: "asylly / belent ýürekli", partOfSpeech: "adjective", exampleEn: "That was a noble thing to do.", exampleTk: "Bu asylly bir işdir.", order: 6 },
    { wordEn: "valor", wordTk: "mertlik / edermenlик", partOfSpeech: "noun", exampleEn: "He was given a medal for valor.", exampleTk: "Ol mertligi üçin medal aldy.", order: 7 },
    { wordEn: "risk", wordTk: "howp aşmak / töwekgelçilik", partOfSpeech: "noun", exampleEn: "She took a risk to help others.", exampleTk: "Ol başgalara kömek etmek üçin töwekgelçilik etdi.", order: 8 },
    { wordEn: "adventure", wordTk: "başdan geçirme / tolgundyryjy ýol", partOfSpeech: "noun", exampleEn: "Life is a great adventure.", exampleTk: "Durmuş — uly bir başdan geçirmedir.", order: 9 },
    { wordEn: "confident", wordTk: "özüne ynamly", partOfSpeech: "adjective", exampleEn: "Be confident in your abilities.", exampleTk: "Ukybyňa ynamly bol.", order: 10 },
  ]},
  { weekNumber: 5, titleEn: "Week 5: Crime", titleTk: "5-nji Hepde: Jenaýat", words: [
    { wordEn: "crime", wordTk: "jenaýat", partOfSpeech: "noun", exampleEn: "Crime is a serious problem in big cities.", exampleTk: "Jenaýat uly şäherlerde çynlakaý meseledir.", order: 1 },
    { wordEn: "criminal", wordTk: "jenaýatçy", partOfSpeech: "noun", exampleEn: "The criminal was arrested by police.", exampleTk: "Jenaýatçy polisiýa tarapyndan tutuldy.", order: 2 },
    { wordEn: "arrest", wordTk: "tutmak / gözaltyna almak", partOfSpeech: "verb", exampleEn: "The police arrested the suspect.", exampleTk: "Polisiýa şübhelenileni tutdy.", order: 3 },
    { wordEn: "guilty", wordTk: "günäli", partOfSpeech: "adjective", exampleEn: "He was found guilty by the court.", exampleTk: "Kazyýet ony günäli tapdy.", order: 4 },
    { wordEn: "prison", wordTk: "türme / zyndana", partOfSpeech: "noun", exampleEn: "He spent five years in prison.", exampleTk: "Ol bäş ýyl türmede oturdy.", order: 5 },
    { wordEn: "steal", wordTk: "ogurlamak", partOfSpeech: "verb", exampleEn: "It is wrong to steal.", exampleTk: "Ogurlamak nädogrudyr.", order: 6 },
    { wordEn: "victim", wordTk: "pidalы adam / ejir çeken", partOfSpeech: "noun", exampleEn: "The victim received help from police.", exampleTk: "Pida polisiýadan kömek aldy.", order: 7 },
    { wordEn: "punish", wordTk: "jezalandyrmak / jeza bermek", partOfSpeech: "verb", exampleEn: "Bad behaviour must be punished.", exampleTk: "Erbet özüň alyp baryş jezalandyrylmaly.", order: 8 },
    { wordEn: "legal", wordTk: "kanuny / hukugy", partOfSpeech: "adjective", exampleEn: "Is this action legal?", exampleTk: "Bu hereket kanunymy?", order: 9 },
    { wordEn: "rob", wordTk: "talaňçylyk etmek / ýaramaz ýol bilen almak", partOfSpeech: "verb", exampleEn: "Someone tried to rob the bank.", exampleTk: "Kim banky talap synanyşdy.", order: 10 },
  ]},
  { weekNumber: 6, titleEn: "Week 6: Poverty", titleTk: "6-njy Hepde: Garyplyk", words: [
    { wordEn: "poor", wordTk: "garyp / ýoksul", partOfSpeech: "adjective", exampleEn: "Many poor families need help.", exampleTk: "Köp garyp maşgala kömege mätäç.", order: 1 },
    { wordEn: "poverty", wordTk: "garyplyk / ýoksullyk", partOfSpeech: "noun", exampleEn: "Poverty is a global challenge.", exampleTk: "Garyplyk global mesele.", order: 2 },
    { wordEn: "lack", wordTk: "ýetmezçilik / az bolmak", partOfSpeech: "noun", exampleEn: "There is a lack of clean water.", exampleTk: "Arassa suwuň ýetmezçiligi bar.", order: 3 },
    { wordEn: "struggle", wordTk: "göreşmek / kynçylyk çekmek", partOfSpeech: "verb", exampleEn: "Many families struggle to survive.", exampleTk: "Köp maşgala ýaşaş üçin göreşýär.", order: 4 },
    { wordEn: "beg", wordTk: "dilenmek / haýyş etmek", partOfSpeech: "verb", exampleEn: "He had to beg for food.", exampleTk: "Ol nahar dilemeli boldy.", order: 5 },
    { wordEn: "suffer", wordTk: "ejir çekmek / horlanmak", partOfSpeech: "verb", exampleEn: "Children should not suffer from hunger.", exampleTk: "Çagalar açlykdan ejir çekmeli däldir.", order: 6 },
    { wordEn: "homeless", wordTk: "öýsüz / başpenasyz", partOfSpeech: "adjective", exampleEn: "The charity helps homeless people.", exampleTk: "Haýyr-sahawat guramasy öýsüz adamlara kömek edýär.", order: 7 },
    { wordEn: "charity", wordTk: "haýyr-sahawat", partOfSpeech: "noun", exampleEn: "He donated money to charity.", exampleTk: "Ol haýyr-sahawata pul berdi.", order: 8 },
    { wordEn: "support", wordTk: "goldamak / kömek etmek", partOfSpeech: "verb", exampleEn: "We must support poor communities.", exampleTk: "Garyp ýaşaýjylary goldamaly.", order: 9 },
    { wordEn: "need", wordTk: "zerurlyk / hajat", partOfSpeech: "noun", exampleEn: "Every child has basic needs.", exampleTk: "Her çaganyň esasy hajatlary bar.", order: 10 },
  ]},
  { weekNumber: 7, titleEn: "Week 7: Health", titleTk: "7-nji Hepde: Saglyk", words: [
    { wordEn: "healthy", wordTk: "sagdyn / ýaşyl", partOfSpeech: "adjective", exampleEn: "Eat healthy food every day.", exampleTk: "Her gün sagdyn nahar iý.", order: 1 },
    { wordEn: "disease", wordTk: "kesel / näsaglyk", partOfSpeech: "noun", exampleEn: "This disease spreads quickly.", exampleTk: "Bu kesel çalt ýaýraýar.", order: 2 },
    { wordEn: "cure", wordTk: "bejermek / em etmek", partOfSpeech: "verb", exampleEn: "Scientists are working to cure cancer.", exampleTk: "Alymlar rak keselini bejermegiň üstünde işleýärler.", order: 3 },
    { wordEn: "prevent", wordTk: "öňüni almak / saklajak bolmak", partOfSpeech: "verb", exampleEn: "Exercise can prevent many diseases.", exampleTk: "Maşk köp keseli öňüni alyp biler.", order: 4 },
    { wordEn: "examine", wordTk: "barlagdan geçirmek / gözden geçirmek", partOfSpeech: "verb", exampleEn: "The doctor examined the patient.", exampleTk: "Lukman näsagy barlagdan geçirdi.", order: 5 },
    { wordEn: "patient", wordTk: "näsag / hasta", partOfSpeech: "noun", exampleEn: "The patient needs rest.", exampleTk: "Näsaga dynç gerek.", order: 6 },
    { wordEn: "medicine", wordTk: "derman / lukmançylyk", partOfSpeech: "noun", exampleEn: "Take this medicine twice a day.", exampleTk: "Bu dermany günde iki gezek iç.", order: 7 },
    { wordEn: "pain", wordTk: "agyry / sancyk", partOfSpeech: "noun", exampleEn: "I feel pain in my back.", exampleTk: "Bilimde agyry duýýaryn.", order: 8 },
    { wordEn: "recover", wordTk: "sagalmak / gowulaşmak", partOfSpeech: "verb", exampleEn: "She recovered quickly after surgery.", exampleTk: "Ol operasiýadan soň tiz sagaldy.", order: 9 },
    { wordEn: "symptom", wordTk: "alamat / kesel alamaty", partOfSpeech: "noun", exampleEn: "Fever is a symptom of many diseases.", exampleTk: "Gyzdyrma köp keselleriň alamatydyr.", order: 10 },
  ]},
  { weekNumber: 8, titleEn: "Week 8: Danger", titleTk: "8-nji Hepde: Howp", words: [
    { wordEn: "dangerous", wordTk: "howply / tehlikeli", partOfSpeech: "adjective", exampleEn: "This road is very dangerous.", exampleTk: "Bu ýol gaty howpludyr.", order: 1 },
    { wordEn: "warn", wordTk: "duýdurmak / habar bermek", partOfSpeech: "verb", exampleEn: "The sign warns drivers about ice.", exampleTk: "Belgi sürüjileri buz barada duýdurýar.", order: 2 },
    { wordEn: "caution", wordTk: "seresaplylyk / ähtiýatlylyk", partOfSpeech: "noun", exampleEn: "Proceed with caution!", exampleTk: "Seresap bol!", order: 3 },
    { wordEn: "protect", wordTk: "goramak / saklajak bolmak", partOfSpeech: "verb", exampleEn: "Parents protect their children.", exampleTk: "Ene-atalar çagalaryny goraýarlar.", order: 4 },
    { wordEn: "hazard", wordTk: "howp / töwekgelçilik", partOfSpeech: "noun", exampleEn: "Ice on the road is a hazard.", exampleTk: "Ýoldaky buz howp döredýär.", order: 5 },
    { wordEn: "unsafe", wordTk: "howpsuz däl / howply", partOfSpeech: "adjective", exampleEn: "This bridge is unsafe.", exampleTk: "Bu köpri howpsuz däl.", order: 6 },
    { wordEn: "accident", wordTk: "heläkçilik / betbagtçylyk", partOfSpeech: "noun", exampleEn: "A serious accident happened on the highway.", exampleTk: "Ýollarda agyr heläkçilik boldy.", order: 7 },
    { wordEn: "survive", wordTk: "diri galmak / halas bolmak", partOfSpeech: "verb", exampleEn: "He survived the accident.", exampleTk: "Ol heläkçilikden diri galdy.", order: 8 },
    { wordEn: "risk", wordTk: "howp / töwekgelçilik", partOfSpeech: "noun", exampleEn: "There is a risk of flooding here.", exampleTk: "Bu ýerde suw joşma howpy bar.", order: 9 },
    { wordEn: "threat", wordTk: "howp / haýbat atmak", partOfSpeech: "noun", exampleEn: "Climate change is a threat to life.", exampleTk: "Howa üýtgemesi durmuşa howp döredýär.", order: 10 },
  ]},
  { weekNumber: 9, titleEn: "Week 9: Power", titleTk: "9-njy Hepde: Güýç", words: [
    { wordEn: "power", wordTk: "güýç / erk", partOfSpeech: "noun", exampleEn: "Knowledge is power.", exampleTk: "Bilim — güýçdür.", order: 1 },
    { wordEn: "control", wordTk: "gözegçilik / dolandyrmak", partOfSpeech: "noun", exampleEn: "She has control over the situation.", exampleTk: "Ol ýagdaýy dolandyrýar.", order: 2 },
    { wordEn: "force", wordTk: "güýç / zor", partOfSpeech: "noun", exampleEn: "Do not use force.", exampleTk: "Güýç ulanma.", order: 3 },
    { wordEn: "rule", wordTk: "dolandyrmak / ýolbaşçylyk etmek", partOfSpeech: "verb", exampleEn: "He ruled the country for ten years.", exampleTk: "Ol ýurdy on ýyl dolandyrdy.", order: 4 },
    { wordEn: "authority", wordTk: "ygtyýar / hukuk", partOfSpeech: "noun", exampleEn: "Teachers have authority in classrooms.", exampleTk: "Mugallymlaryň okuw otagynda ygtyýary bardyr.", order: 5 },
    { wordEn: "influence", wordTk: "täsir / nüpüz", partOfSpeech: "noun", exampleEn: "Parents have a big influence on children.", exampleTk: "Ene-atalaryň çagalara uly täsiri bardyr.", order: 6 },
    { wordEn: "govern", wordTk: "dolandyrmak / ýolbaşçylyk etmek", partOfSpeech: "verb", exampleEn: "The president governs the country.", exampleTk: "Prezident ýurdy dolandyrýar.", order: 7 },
    { wordEn: "command", wordTk: "buýruk / tabşyrma", partOfSpeech: "noun", exampleEn: "Follow the commander's orders.", exampleTk: "Serkerdäniň buýruklaryna boýun bol.", order: 8 },
    { wordEn: "strong", wordTk: "güýçli / berk", partOfSpeech: "adjective", exampleEn: "A strong leader inspires others.", exampleTk: "Güýçli ýolbaşçy başgalara ylham berýär.", order: 9 },
    { wordEn: "leader", wordTk: "ýolbaşçy / lider", partOfSpeech: "noun", exampleEn: "A good leader listens to everyone.", exampleTk: "Gowy ýolbaşçy hemmäni diňleýär.", order: 10 },
  ]},
  { weekNumber: 10, titleEn: "Week 10: Education", titleTk: "10-njy Hepde: Bilim", words: [
    { wordEn: "learn", wordTk: "öwrenmek", partOfSpeech: "verb", exampleEn: "Children learn quickly.", exampleTk: "Çagalar tiz öwrenýärler.", order: 1 },
    { wordEn: "knowledge", wordTk: "bilim / maglumat", partOfSpeech: "noun", exampleEn: "Knowledge opens many doors.", exampleTk: "Bilim köp gapyny açýar.", order: 2 },
    { wordEn: "educate", wordTk: "bilim bermek / öwretmek", partOfSpeech: "verb", exampleEn: "We must educate the next generation.", exampleTk: "Geljek nesle bilim bermeli.", order: 3 },
    { wordEn: "skill", wordTk: "ukyp / başarnyk", partOfSpeech: "noun", exampleEn: "Reading is an important skill.", exampleTk: "Okamak möhüm başarnypdyr.", order: 4 },
    { wordEn: "practice", wordTk: "türgenleşmek / ulanmak", partOfSpeech: "verb", exampleEn: "Practice makes perfect.", exampleTk: "Ulanmak kämilleşdirýär.", order: 5 },
    { wordEn: "master", wordTk: "ussatlaşmak / düýpli öwrenmek", partOfSpeech: "verb", exampleEn: "It takes time to master a language.", exampleTk: "Dile ussatlaşmak wagt talap edýär.", order: 6 },
    { wordEn: "graduate", wordTk: "gutarmak / diplom almak", partOfSpeech: "verb", exampleEn: "She graduated with top grades.", exampleTk: "Ol birinji dereje bilen gutardy.", order: 7 },
    { wordEn: "study", wordTk: "okamak / öwrenmek", partOfSpeech: "verb", exampleEn: "Study every day for the best results.", exampleTk: "Iň gowy netije üçin her gün oka.", order: 8 },
    { wordEn: "teach", wordTk: "öwretmek / sapak bermek", partOfSpeech: "verb", exampleEn: "She teaches mathematics at school.", exampleTk: "Ol mekdepde matematika öwredýär.", order: 9 },
    { wordEn: "educated", wordTk: "bilimli / sowatly", partOfSpeech: "adjective", exampleEn: "An educated person has more opportunities.", exampleTk: "Bilimli adam has köp mümkinçiligi bardyr.", order: 10 },
  ]},
  { weekNumber: 11, titleEn: "Week 11: Work", titleTk: "11-nji Hepde: Zähmet", words: [
    { wordEn: "employ", wordTk: "işe almak / zähmet bermek", partOfSpeech: "verb", exampleEn: "The company employs 500 people.", exampleTk: "Kompaniýa 500 adamy işe alýar.", order: 1 },
    { wordEn: "earn", wordTk: "gazanmak / aýlyk almak", partOfSpeech: "verb", exampleEn: "She earns a good salary.", exampleTk: "Ol gowy zähmet haky gazanýar.", order: 2 },
    { wordEn: "manage", wordTk: "dolandyrmak / başarmak", partOfSpeech: "verb", exampleEn: "He manages a team of ten people.", exampleTk: "Ol on adamdan ybarat topary dolandyrýar.", order: 3 },
    { wordEn: "task", wordTk: "tabşyryk / iş", partOfSpeech: "noun", exampleEn: "Complete your tasks on time.", exampleTk: "Tabşyryklaryňy wagtynda tamamla.", order: 4 },
    { wordEn: "career", wordTk: "karýera / iş ýoly", partOfSpeech: "noun", exampleEn: "She has a great career in medicine.", exampleTk: "Onuň lukmançylykda ajaýyp karýerasy bar.", order: 5 },
    { wordEn: "salary", wordTk: "aýlyk / zähmet haky", partOfSpeech: "noun", exampleEn: "My salary increased this year.", exampleTk: "Bu ýyl aýlygym artdy.", order: 6 },
    { wordEn: "profession", wordTk: "hünär / kär", partOfSpeech: "noun", exampleEn: "Teaching is a noble profession.", exampleTk: "Mugallymçylyk asylly hünärdir.", order: 7 },
    { wordEn: "promote", wordTk: "wezipäni ýokarlandyrmak / öňe sürmek", partOfSpeech: "verb", exampleEn: "She was promoted to manager.", exampleTk: "Ol müdirlige geçirildi.", order: 8 },
    { wordEn: "retire", wordTk: "pensiýa çykmak / işden aýrylmak", partOfSpeech: "verb", exampleEn: "He retired at 65.", exampleTk: "Ol 65-de pensiýa çykdy.", order: 9 },
    { wordEn: "effort", wordTk: "tagalla / jan çekmek", partOfSpeech: "noun", exampleEn: "Put more effort into your work.", exampleTk: "Işiňe has köp tagalla goý.", order: 10 },
  ]},
  { weekNumber: 12, titleEn: "Week 12: Money", titleTk: "12-nji Hepde: Pul", words: [
    { wordEn: "afford", wordTk: "satyn alyp bilmek / mümkinçiligi bolmak", partOfSpeech: "verb", exampleEn: "Can you afford a new phone?", exampleTk: "Täze telefon satyn alyp bilermiňiz?", order: 1 },
    { wordEn: "invest", wordTk: "maýa goýmak", partOfSpeech: "verb", exampleEn: "Invest in your education.", exampleTk: "Bilimiňe maýa goý.", order: 2 },
    { wordEn: "budget", wordTk: "býujet / çykdajy meýilnamasy", partOfSpeech: "noun", exampleEn: "Make a monthly budget.", exampleTk: "Aýlyk býujet düz.", order: 3 },
    { wordEn: "wealth", wordTk: "baýlyk / mol ýaşaýyş", partOfSpeech: "noun", exampleEn: "Health is more important than wealth.", exampleTk: "Saglyk baýlykdan möhümdir.", order: 4 },
    { wordEn: "finance", wordTk: "maliýe / pul meselesi", partOfSpeech: "noun", exampleEn: "She studied finance at university.", exampleTk: "Ol uniwersitetde maliýe okady.", order: 5 },
    { wordEn: "debt", wordTk: "karz / bergisi", partOfSpeech: "noun", exampleEn: "Pay your debts on time.", exampleTk: "Karzyňy wagtynda öde.", order: 6 },
    { wordEn: "donate", wordTk: "bagyşlamak / gurmak", partOfSpeech: "verb", exampleEn: "Please donate to help others.", exampleTk: "Başgalara kömek etmek üçin goşant goş.", order: 7 },
    { wordEn: "income", wordTk: "girdeji / girdej", partOfSpeech: "noun", exampleEn: "Her income increased last year.", exampleTk: "Onuň girdejisi geçen ýyl artdy.", order: 8 },
    { wordEn: "expense", wordTk: "çykdajy / sarp etmek", partOfSpeech: "noun", exampleEn: "Control your monthly expenses.", exampleTk: "Aýlyk çykdajylaryňy gözegçilikde sakla.", order: 9 },
    { wordEn: "save", wordTk: "tygşytlamak / goramak", partOfSpeech: "verb", exampleEn: "Save money for the future.", exampleTk: "Geljek üçin pul tygşytla.", order: 10 },
  ]},
  { weekNumber: 13, titleEn: "Week 13: Friendship", titleTk: "13-nji Hepde: Dostluk", words: [
    { wordEn: "loyal", wordTk: "wepaly / sadyk", partOfSpeech: "adjective", exampleEn: "A loyal friend stays with you through difficult times.", exampleTk: "Wepaly dost kyn döwürde hem ýanyňda durýar.", order: 1 },
    { wordEn: "trust", wordTk: "ynamy / ynanmak", partOfSpeech: "noun", exampleEn: "Trust is the basis of friendship.", exampleTk: "Ynam dostlugyň esasydyr.", order: 2 },
    { wordEn: "companion", wordTk: "ýoldaş / hemra", partOfSpeech: "noun", exampleEn: "He was my companion on the journey.", exampleTk: "Ol ýolda meniň hemramdy.", order: 3 },
    { wordEn: "sincere", wordTk: "samimi / içten", partOfSpeech: "adjective", exampleEn: "Be sincere with your friends.", exampleTk: "Dostlaryňa samimi bol.", order: 4 },
    { wordEn: "rely", wordTk: "daýanmak / bil baglamak", partOfSpeech: "verb", exampleEn: "You can always rely on good friends.", exampleTk: "Gowy dostlara hemişe daýanyp bilersiňiz.", order: 5 },
    { wordEn: "kindness", wordTk: "mähribanlyk / ýagşylyk", partOfSpeech: "noun", exampleEn: "Show kindness to everyone.", exampleTk: "Hemmä mähribanlyk görkez.", order: 6 },
    { wordEn: "respect", wordTk: "hormat / sylag", partOfSpeech: "noun", exampleEn: "Respect is earned, not given.", exampleTk: "Hormat gazanylýar, berilmeýär.", order: 7 },
    { wordEn: "bond", wordTk: "baglanyşyk / aragatnaşyk", partOfSpeech: "noun", exampleEn: "We have a strong bond.", exampleTk: "Biziň güýçli baglanyşygymyz bar.", order: 8 },
    { wordEn: "support", wordTk: "goldamak / kömek etmek", partOfSpeech: "verb", exampleEn: "Good friends support each other.", exampleTk: "Gowy dostlar bir-birini goldaýar.", order: 9 },
    { wordEn: "generous", wordTk: "eli açyk / sahawatly", partOfSpeech: "adjective", exampleEn: "She is very generous with her time.", exampleTk: "Ol wagty barada gaty eli açyk.", order: 10 },
  ]},
  { weekNumber: 14, titleEn: "Week 14: Family", titleTk: "14-nji Hepde: Maşgala", words: [
    { wordEn: "raise", wordTk: "terbiýelemek / ýetişdirmek", partOfSpeech: "verb", exampleEn: "They raised three children.", exampleTk: "Olar üç çaga terbiýelediler.", order: 1 },
    { wordEn: "depend", wordTk: "bil baglamak / garaşly bolmak", partOfSpeech: "verb", exampleEn: "Children depend on their parents.", exampleTk: "Çagalar ene-atalaryna garaşly.", order: 2 },
    { wordEn: "relative", wordTk: "garyndaş / hossarlar", partOfSpeech: "noun", exampleEn: "We visited our relatives last holiday.", exampleTk: "Geçen baýramda garyndaşlarymyza gitdik.", order: 3 },
    { wordEn: "sibling", wordTk: "dogany / uýa (dogan-uýa)", partOfSpeech: "noun", exampleEn: "I have two siblings.", exampleTk: "Meniň iki dogan-uýam bar.", order: 4 },
    { wordEn: "unite", wordTk: "birleşmek / jebisleşmek", partOfSpeech: "verb", exampleEn: "Family difficulties can unite people.", exampleTk: "Maşgala kynçylyklary adamlary birleşdirip biler.", order: 5 },
    { wordEn: "protect", wordTk: "goramak / saklamak", partOfSpeech: "verb", exampleEn: "Parents protect their children.", exampleTk: "Ene-atalar çagalaryny goraýarlar.", order: 6 },
    { wordEn: "care", wordTk: "alada etmek / seredip durmak", partOfSpeech: "verb", exampleEn: "She cares for her elderly parents.", exampleTk: "Ol garry ene-atalaryna seredýär.", order: 7 },
    { wordEn: "bond", wordTk: "maşgala baglanyşygy / birlik", partOfSpeech: "noun", exampleEn: "The family bond is very strong.", exampleTk: "Maşgala birliği gaty güýçlidir.", order: 8 },
    { wordEn: "heritage", wordTk: "miras / milli baýlyk", partOfSpeech: "noun", exampleEn: "We are proud of our cultural heritage.", exampleTk: "Medeni mirasymyza buýsanýarys.", order: 9 },
    { wordEn: "generation", wordTk: "nesil / ýaş nesil", partOfSpeech: "noun", exampleEn: "Every generation faces new challenges.", exampleTk: "Her nesil täze kynçylyklara duş gelýär.", order: 10 },
  ]},
  { weekNumber: 15, titleEn: "Week 15: Travel", titleTk: "15-nji Hepde: Syýahat", words: [
    { wordEn: "destination", wordTk: "baryljak ýer / maksat nokady", partOfSpeech: "noun", exampleEn: "What is your destination?", exampleTk: "Baryljak ýeriňiz nire?", order: 1 },
    { wordEn: "explore", wordTk: "gözlemek / açmak", partOfSpeech: "verb", exampleEn: "I love to explore new places.", exampleTk: "Men täze ýerleri gözlemegi halaýaryn.", order: 2 },
    { wordEn: "journey", wordTk: "ýol / syýahat", partOfSpeech: "noun", exampleEn: "The journey took three days.", exampleTk: "Ýol üç gün aldy.", order: 3 },
    { wordEn: "foreign", wordTk: "daşary ýurt / daşary ýurtly", partOfSpeech: "adjective", exampleEn: "I enjoy foreign cultures.", exampleTk: "Men daşary ýurt medeniýetlerini halaýaryn.", order: 4 },
    { wordEn: "depart", wordTk: "ýola düşmek / ugramak", partOfSpeech: "verb", exampleEn: "The plane departs at midnight.", exampleTk: "Uçar ýarigijede ugraýar.", order: 5 },
    { wordEn: "arrive", wordTk: "gelmek / ýetmek", partOfSpeech: "verb", exampleEn: "We arrived in the city at noon.", exampleTk: "Biz şähere günortana geldik.", order: 6 },
    { wordEn: "tour", wordTk: "gezelenç / tur", partOfSpeech: "noun", exampleEn: "We took a city tour.", exampleTk: "Biz şäher gezelenç aldyk.", order: 7 },
    { wordEn: "guide", wordTk: "gollanma / gide", partOfSpeech: "noun", exampleEn: "The tour guide was very helpful.", exampleTk: "Tur gollanmasy gaty peýdalydy.", order: 8 },
    { wordEn: "adventure", wordTk: "başdan geçirme / gaýrat", partOfSpeech: "noun", exampleEn: "Every trip is a new adventure.", exampleTk: "Her syýahat täze başdan geçirmedir.", order: 9 },
    { wordEn: "accommodation", wordTk: "ýaşaýyş / myhmanhana", partOfSpeech: "noun", exampleEn: "Book your accommodation in advance.", exampleTk: "Ýaşaýyş ýeriňizi öňünden bron ediň.", order: 10 },
  ]},
  { weekNumber: 16, titleEn: "Week 16: Food", titleTk: "16-njy Hepde: Iýmit", words: [
    { wordEn: "nourish", wordTk: "iýmitlendirmek / berkitmek", partOfSpeech: "verb", exampleEn: "Good food nourishes the body.", exampleTk: "Gowy iýmit bedeni iýmitlendirýär.", order: 1 },
    { wordEn: "appetite", wordTk: "iştah / nahara höwes", partOfSpeech: "noun", exampleEn: "I have a big appetite today.", exampleTk: "Bu gün meniň iştahym uly.", order: 2 },
    { wordEn: "recipe", wordTk: "resept / taýýarlaýyş usuly", partOfSpeech: "noun", exampleEn: "She shared her grandmother's recipe.", exampleTk: "Ol mamasynyň reseptini paýlaşdy.", order: 3 },
    { wordEn: "ingredient", wordTk: "düzüm bölegi / goşundy", partOfSpeech: "noun", exampleEn: "What ingredients do you need?", exampleTk: "Haýsy düzüm bölekleri gerek?", order: 4 },
    { wordEn: "fresh", wordTk: "täze / ter", partOfSpeech: "adjective", exampleEn: "Always buy fresh vegetables.", exampleTk: "Hemişe ter gök önüm satyn al.", order: 5 },
    { wordEn: "hunger", wordTk: "açlyk / ajygmak", partOfSpeech: "noun", exampleEn: "World hunger is a serious issue.", exampleTk: "Dünýä açlygy çynlakaý meseledir.", order: 6 },
    { wordEn: "delicious", wordTk: "lezzetli / tagamly", partOfSpeech: "adjective", exampleEn: "This meal is delicious!", exampleTk: "Bu nahar lezzetli!", order: 7 },
    { wordEn: "diet", wordTk: "iýmit tertip-düzgüni / diýeta", partOfSpeech: "noun", exampleEn: "A balanced diet keeps you healthy.", exampleTk: "Deňagramly iýmit saglyk saklaýar.", order: 8 },
    { wordEn: "taste", wordTk: "tagam / datmak", partOfSpeech: "noun", exampleEn: "The taste of this soup is amazing.", exampleTk: "Bu çorbanyň tagamy ajaýyp.", order: 9 },
    { wordEn: "prepare", wordTk: "taýýarlamak / bişirmek", partOfSpeech: "verb", exampleEn: "She prepares lunch every day.", exampleTk: "Ol her gün günortanlyk taýýarlaýar.", order: 10 },
  ]},
  { weekNumber: 17, titleEn: "Week 17: Nature", titleTk: "17-nji Hepde: Tebigat", words: [
    { wordEn: "habitat", wordTk: "ýaşaýyş gurşawy / mesgen", partOfSpeech: "noun", exampleEn: "Forests are the habitat of many animals.", exampleTk: "Tokaýlar köp haýwanyň mesgenidir.", order: 1 },
    { wordEn: "climate", wordTk: "howa / iklim", partOfSpeech: "noun", exampleEn: "The climate here is very dry.", exampleTk: "Bu ýerdäki howa gaty gurakdyr.", order: 2 },
    { wordEn: "species", wordTk: "görnüş / biologik görnüş", partOfSpeech: "noun", exampleEn: "Many species are endangered.", exampleTk: "Köp görnüşler ýitip gitmek howpy astyndadyr.", order: 3 },
    { wordEn: "ecosystem", wordTk: "ekosistema / tebigy ulgam", partOfSpeech: "noun", exampleEn: "Humans affect the ecosystem.", exampleTk: "Adamlar ekosistemäne täsir edýär.", order: 4 },
    { wordEn: "ocean", wordTk: "okean / uly deňiz", partOfSpeech: "noun", exampleEn: "The ocean covers most of Earth.", exampleTk: "Okean Ýeriň köp bölegini örtýär.", order: 5 },
    { wordEn: "forest", wordTk: "tokaý / düzlük tokaý", partOfSpeech: "noun", exampleEn: "We must protect our forests.", exampleTk: "Tokaýlarymyzy goramaly.", order: 6 },
    { wordEn: "mountain", wordTk: "dag / beýik dag", partOfSpeech: "noun", exampleEn: "The mountains are covered in snow.", exampleTk: "Daglar gar bilen örtülendir.", order: 7 },
    { wordEn: "season", wordTk: "pasyl / möwsüm", partOfSpeech: "noun", exampleEn: "Spring is my favourite season.", exampleTk: "Ýaz meniň söýgüli paslymdyr.", order: 8 },
    { wordEn: "plant", wordTk: "ösümlik / oturtmak", partOfSpeech: "noun", exampleEn: "Plants produce oxygen.", exampleTk: "Ösümlikler kislorod öndürýär.", order: 9 },
    { wordEn: "animal", wordTk: "haýwan / janly", partOfSpeech: "noun", exampleEn: "Every animal has its role in nature.", exampleTk: "Her haýwanyň tebigata öz orny bardyr.", order: 10 },
  ]},
  { weekNumber: 18, titleEn: "Week 18: Animals", titleTk: "18-nji Hepde: Haýwanlar", words: [
    { wordEn: "wild", wordTk: "ýabany / öý däl", partOfSpeech: "adjective", exampleEn: "Wild animals should not be kept at home.", exampleTk: "Ýabany haýwanlary öýde saklamaly däldir.", order: 1 },
    { wordEn: "domestic", wordTk: "öý / öýde saklanýan", partOfSpeech: "adjective", exampleEn: "Dogs and cats are domestic animals.", exampleTk: "Itler we pişikler öý haýwanlarydyr.", order: 2 },
    { wordEn: "hunt", wordTk: "aw etmek / awlamak", partOfSpeech: "verb", exampleEn: "Lions hunt at night.", exampleTk: "Arslanlaryň gijesi awlaýar.", order: 3 },
    { wordEn: "prey", wordTk: "awlan / aldanan", partOfSpeech: "noun", exampleEn: "The rabbit was the fox's prey.", exampleTk: "Towşan tilkiniň awydyr.", order: 4 },
    { wordEn: "rare", wordTk: "seýrek / az duşýan", partOfSpeech: "adjective", exampleEn: "This bird is very rare.", exampleTk: "Bu guş gaty seýrekdir.", order: 5 },
    { wordEn: "endangered", wordTk: "ýitip gitmek howpy astynda", partOfSpeech: "adjective", exampleEn: "Tigers are endangered animals.", exampleTk: "Gaplanlar ýitip gitmek howpy astyndaky haýwanlar.", order: 6 },
    { wordEn: "protect", wordTk: "goramak", partOfSpeech: "verb", exampleEn: "We must protect endangered animals.", exampleTk: "Ýitip gitmek howpy astyndaky haýwanlary goramaly.", order: 7 },
    { wordEn: "migrate", wordTk: "göçmek / ýer üýtgetmek", partOfSpeech: "verb", exampleEn: "Birds migrate to warmer places in winter.", exampleTk: "Gyşda guşlar ýyly ýerlere göçýär.", order: 8 },
    { wordEn: "predator", wordTk: "ýyrtyjy / awçy haýwan", partOfSpeech: "noun", exampleEn: "Lions are apex predators.", exampleTk: "Arslanlary iň ýokary derejeli ýyrtynjylardyr.", order: 9 },
    { wordEn: "breed", wordTk: "köpeltmek / tohumlamak", partOfSpeech: "verb", exampleEn: "These animals breed in spring.", exampleTk: "Bu haýwanlar ýazda köpelýär.", order: 10 },
  ]},
  { weekNumber: 19, titleEn: "Week 19: Weather", titleTk: "19-njy Hepde: Howa şertleri", words: [
    { wordEn: "temperature", wordTk: "temperatura / ýylylyk derejesi", partOfSpeech: "noun", exampleEn: "The temperature is 40 degrees today.", exampleTk: "Bu gün temperatura 40 dereje.", order: 1 },
    { wordEn: "storm", wordTk: "tupan / harasatly howa", partOfSpeech: "noun", exampleEn: "A big storm is coming.", exampleTk: "Uly tupan gelyär.", order: 2 },
    { wordEn: "flood", wordTk: "suw joşmasy / sil", partOfSpeech: "noun", exampleEn: "The floods destroyed many homes.", exampleTk: "Sil köp öýi ýok etdi.", order: 3 },
    { wordEn: "drought", wordTk: "gurakçylyk / guraklyk", partOfSpeech: "noun", exampleEn: "The drought lasted three months.", exampleTk: "Gurakçylyk üç aý dowam etdi.", order: 4 },
    { wordEn: "forecast", wordTk: "howa çaklamasy / öňünden aýtmak", partOfSpeech: "noun", exampleEn: "The weather forecast shows rain tomorrow.", exampleTk: "Howa çaklamasy ertir ýagmyr görkezýär.", order: 5 },
    { wordEn: "severe", wordTk: "güýçli / agyr", partOfSpeech: "adjective", exampleEn: "Severe weather is dangerous.", exampleTk: "Güýçli howa howply.", order: 6 },
    { wordEn: "humid", wordTk: "çygly / nemli", partOfSpeech: "adjective", exampleEn: "It is very humid today.", exampleTk: "Bu gün gaty çygly.", order: 7 },
    { wordEn: "freeze", wordTk: "doňmak / buz baglamak", partOfSpeech: "verb", exampleEn: "The river froze last winter.", exampleTk: "Derýa geçen gyşda doňdy.", order: 8 },
    { wordEn: "lightning", wordTk: "ýyldyrym / çakgyldym", partOfSpeech: "noun", exampleEn: "Lightning struck the tree.", exampleTk: "Ýyldyrym agaja urdy.", order: 9 },
    { wordEn: "wind", wordTk: "şemal / ýel", partOfSpeech: "noun", exampleEn: "A strong wind blew all night.", exampleTk: "Güýçli şemal bütin gije öwüsdi.", order: 10 },
  ]},
  { weekNumber: 20, titleEn: "Week 20: Science", titleTk: "20-nji Hepde: Ylym", words: [
    { wordEn: "discover", wordTk: "açmak / tapmak", partOfSpeech: "verb", exampleEn: "Scientists discovered a new planet.", exampleTk: "Alymlar täze planeta tapdylar.", order: 1 },
    { wordEn: "research", wordTk: "ylmy barlag / derňew", partOfSpeech: "noun", exampleEn: "Research takes years of work.", exampleTk: "Ylmy barlag ýyllap zähmet talap edýär.", order: 2 },
    { wordEn: "theory", wordTk: "teoriýa / çaklama", partOfSpeech: "noun", exampleEn: "Einstein developed the theory of relativity.", exampleTk: "Eýnşteýn bäbekklilik teoriýasyny işläp taýýarlady.", order: 3 },
    { wordEn: "experiment", wordTk: "tejribe / synag", partOfSpeech: "noun", exampleEn: "The experiment was a success.", exampleTk: "Tejribe üstünlikli boldy.", order: 4 },
    { wordEn: "observe", wordTk: "synlamak / gözegçilik etmek", partOfSpeech: "verb", exampleEn: "Scientists observe the stars.", exampleTk: "Alymlar ýyldyzlary synlaýarlar.", order: 5 },
    { wordEn: "analyze", wordTk: "derňemek / seljermek", partOfSpeech: "verb", exampleEn: "Analyze the data carefully.", exampleTk: "Maglumatlary ünsli derňe.", order: 6 },
    { wordEn: "data", wordTk: "maglumat / san", partOfSpeech: "noun", exampleEn: "We collected lots of data.", exampleTk: "Biz köp maglumat topladyk.", order: 7 },
    { wordEn: "prove", wordTk: "subut etmek / görkezmek", partOfSpeech: "verb", exampleEn: "She proved her theory correct.", exampleTk: "Ol teoriýasynyň dogrydygyny subut etdi.", order: 8 },
    { wordEn: "laboratory", wordTk: "laboratoriýa", partOfSpeech: "noun", exampleEn: "The work is done in a laboratory.", exampleTk: "Iş laboratoriýada ýerine ýetirilýär.", order: 9 },
    { wordEn: "invention", wordTk: "oýlap tapyş / täzelik", partOfSpeech: "noun", exampleEn: "The telephone was a great invention.", exampleTk: "Telefon ajaýyp oýlap tapyşdyr.", order: 10 },
  ]},
  { weekNumber: 21, titleEn: "Week 21: Technology", titleTk: "21-nji Hepde: Tehnologiýa", words: [
    { wordEn: "device", wordTk: "enjam / abzal", partOfSpeech: "noun", exampleEn: "This device is very useful.", exampleTk: "Bu enjam gaty peýdaly.", order: 1 },
    { wordEn: "digital", wordTk: "sanly / sanly görnüş", partOfSpeech: "adjective", exampleEn: "We live in a digital age.", exampleTk: "Biz sanly döwürde ýaşaýarys.", order: 2 },
    { wordEn: "connect", wordTk: "birikdirmek / aragatnaşyk açmak", partOfSpeech: "verb", exampleEn: "Connect to the internet.", exampleTk: "Internete birik.", order: 3 },
    { wordEn: "invent", wordTk: "oýlap tapmak / açmak", partOfSpeech: "verb", exampleEn: "Who invented the telephone?", exampleTk: "Telefony kim oýlap tapdy?", order: 4 },
    { wordEn: "system", wordTk: "ulgam / sistema", partOfSpeech: "noun", exampleEn: "The system is not working.", exampleTk: "Ulgam işlemeýär.", order: 5 },
    { wordEn: "update", wordTk: "täzelemek / güncellemek", partOfSpeech: "verb", exampleEn: "Update your software regularly.", exampleTk: "Programmaňy yzygiderli täzele.", order: 6 },
    { wordEn: "program", wordTk: "programma / kod ýazmak", partOfSpeech: "noun", exampleEn: "She wrote a computer program.", exampleTk: "Ol kompýuter programmasy ýazdy.", order: 7 },
    { wordEn: "network", wordTk: "tor / ulgam", partOfSpeech: "noun", exampleEn: "The computer network is down.", exampleTk: "Kompýuter tory işlemeýär.", order: 8 },
    { wordEn: "artificial", wordTk: "emeli / sun'y", partOfSpeech: "adjective", exampleEn: "Artificial intelligence is growing fast.", exampleTk: "Emeli intellekt çalt ösýär.", order: 9 },
    { wordEn: "efficient", wordTk: "netijelи / öndürijilikli", partOfSpeech: "adjective", exampleEn: "This machine is very efficient.", exampleTk: "Bu maşyn gaty netijelidir.", order: 10 },
  ]},
  { weekNumber: 22, titleEn: "Week 22: Communication", titleTk: "22-nji Hepde: Aragatnaşyk", words: [
    { wordEn: "express", wordTk: "aňlatmak / bildirmek", partOfSpeech: "verb", exampleEn: "Express your feelings clearly.", exampleTk: "Duýgularyňy anyk aňlat.", order: 1 },
    { wordEn: "communicate", wordTk: "habar gatnaşmak / aragatnaşyk saklamak", partOfSpeech: "verb", exampleEn: "It is important to communicate well.", exampleTk: "Gowy aragatnaşyk saklamak möhümdir.", order: 2 },
    { wordEn: "message", wordTk: "habar / bildiriş", partOfSpeech: "noun", exampleEn: "Did you get my message?", exampleTk: "Habarymymy aldyňyzmy?", order: 3 },
    { wordEn: "translate", wordTk: "terjime etmek / geçirmek", partOfSpeech: "verb", exampleEn: "Can you translate this sentence?", exampleTk: "Bu jümläni terjime edip bilersiňizmi?", order: 4 },
    { wordEn: "respond", wordTk: "jogap bermek / gaýtarmak", partOfSpeech: "verb", exampleEn: "Please respond to my email.", exampleTk: "E-poçtama jogap beriň, haýyş.", order: 5 },
    { wordEn: "discuss", wordTk: "maslahat etmek / geňeşmek", partOfSpeech: "verb", exampleEn: "Let's discuss this problem.", exampleTk: "Bu meseläni maslahat edeliň.", order: 6 },
    { wordEn: "inform", wordTk: "habar bermek / bildirmek", partOfSpeech: "verb", exampleEn: "Please inform me of any changes.", exampleTk: "Üýtgeşmeleri maňa habar beriň.", order: 7 },
    { wordEn: "understand", wordTk: "düşünmek / bilmek", partOfSpeech: "verb", exampleEn: "Do you understand the question?", exampleTk: "Soraga düşünýärsiňizmi?", order: 8 },
    { wordEn: "listen", wordTk: "diňlemek", partOfSpeech: "verb", exampleEn: "Listen carefully to the teacher.", exampleTk: "Mugallymy ünsli diňle.", order: 9 },
    { wordEn: "speak", wordTk: "gepleşmek / gürrüň etmek", partOfSpeech: "verb", exampleEn: "Speak clearly and slowly.", exampleTk: "Anyk we haýal gürle.", order: 10 },
  ]},
  { weekNumber: 23, titleEn: "Week 23: Art", titleTk: "23-nji Hepde: Sungat", words: [
    { wordEn: "create", wordTk: "döretmek / ýaratmak", partOfSpeech: "verb", exampleEn: "Artists create beautiful works.", exampleTk: "Suratkeşler owadan eserler döredýärler.", order: 1 },
    { wordEn: "design", wordTk: "taslamak / dizaýn", partOfSpeech: "verb", exampleEn: "She designed the building.", exampleTk: "Ol binany taslady.", order: 2 },
    { wordEn: "image", wordTk: "surat / keşp", partOfSpeech: "noun", exampleEn: "This image is very powerful.", exampleTk: "Bu surat gaty täsirli.", order: 3 },
    { wordEn: "style", wordTk: "stil / usul", partOfSpeech: "noun", exampleEn: "Every artist has a unique style.", exampleTk: "Her suratkeşiň özboluşly stili bar.", order: 4 },
    { wordEn: "exhibit", wordTk: "sergi açmak / görkezmek", partOfSpeech: "verb", exampleEn: "Her work is exhibited in a museum.", exampleTk: "Onuň işi muzeýde sergilenýär.", order: 5 },
    { wordEn: "imagination", wordTk: "hyýal / göz öňüne getirmek", partOfSpeech: "noun", exampleEn: "Art requires imagination.", exampleTk: "Sungat hyýal talap edýär.", order: 6 },
    { wordEn: "colour", wordTk: "reňk / boýamak", partOfSpeech: "noun", exampleEn: "She used bright colours in her painting.", exampleTk: "Ol suratyda parlak reňkleri ulandy.", order: 7 },
    { wordEn: "sculptor", wordTk: "heýkeltaraş / oýmakçy", partOfSpeech: "noun", exampleEn: "The sculptor carved a beautiful statue.", exampleTk: "Heýkeltaraş owadan heýkel ýondy.", order: 8 },
    { wordEn: "portrait", wordTk: "portret / adam suraty", partOfSpeech: "noun", exampleEn: "He painted a portrait of his mother.", exampleTk: "Ol ejesiniň portretini çekdi.", order: 9 },
    { wordEn: "gallery", wordTk: "galereýa / sungat sergi ýeri", partOfSpeech: "noun", exampleEn: "We visited the art gallery.", exampleTk: "Biz sungat galereýasyna gitdik.", order: 10 },
  ]},
  { weekNumber: 24, titleEn: "Week 24: Music", titleTk: "24-nji Hepde: Saz", words: [
    { wordEn: "rhythm", wordTk: "ritm / döwür", partOfSpeech: "noun", exampleEn: "Dance to the rhythm of the music.", exampleTk: "Sazyň ritimine görä tans et.", order: 1 },
    { wordEn: "melody", wordTk: "melodiýa / owaz", partOfSpeech: "noun", exampleEn: "I love this beautiful melody.", exampleTk: "Men bu owadan melodiýany halaýaryn.", order: 2 },
    { wordEn: "instrument", wordTk: "saz guraly", partOfSpeech: "noun", exampleEn: "She plays three instruments.", exampleTk: "Ol üç saz guraly çalýar.", order: 3 },
    { wordEn: "perform", wordTk: "çykyş etmek / ýerine ýetirmek", partOfSpeech: "verb", exampleEn: "He performed at the concert.", exampleTk: "Ol konsertde çykyş etdi.", order: 4 },
    { wordEn: "compose", wordTk: "düzmek / saz ýazmak", partOfSpeech: "verb", exampleEn: "She composed a new song.", exampleTk: "Ol täze aýdym ýazdy.", order: 5 },
    { wordEn: "concert", wordTk: "konsert", partOfSpeech: "noun", exampleEn: "The concert was amazing.", exampleTk: "Konsert ajaýypdy.", order: 6 },
    { wordEn: "talent", wordTk: "zehin / ukyp", partOfSpeech: "noun", exampleEn: "She has a great talent for music.", exampleTk: "Onuň saz üçin ajaýyp zehini bar.", order: 7 },
    { wordEn: "lyrics", wordTk: "aýdym sözleri", partOfSpeech: "noun", exampleEn: "I love the lyrics of this song.", exampleTk: "Bu aýdymyň sözlerini halaýaryn.", order: 8 },
    { wordEn: "genre", wordTk: "žanr / görnüş", partOfSpeech: "noun", exampleEn: "What music genre do you prefer?", exampleTk: "Haýsy saz žanryny gowy görýärsiňiz?", order: 9 },
    { wordEn: "band", wordTk: "topar / ansambl", partOfSpeech: "noun", exampleEn: "The band played for three hours.", exampleTk: "Topar üç sagat çaldy.", order: 10 },
  ]},
  { weekNumber: 25, titleEn: "Week 25: Sports", titleTk: "25-nji Hepde: Sport", words: [
    { wordEn: "compete", wordTk: "bäsleşmek / ýaryşmak", partOfSpeech: "verb", exampleEn: "She competes in national tournaments.", exampleTk: "Ol milli ýaryşlarda bäsleşýär.", order: 1 },
    { wordEn: "athletic", wordTk: "türgen / sport", partOfSpeech: "adjective", exampleEn: "He is very athletic.", exampleTk: "Ol gaty türgendir.", order: 2 },
    { wordEn: "championship", wordTk: "çempionat / uly ýaryş", partOfSpeech: "noun", exampleEn: "She won the world championship.", exampleTk: "Ol dünýä çempionatyny gazandy.", order: 3 },
    { wordEn: "tournament", wordTk: "ýaryş / turnir", partOfSpeech: "noun", exampleEn: "The football tournament starts next week.", exampleTk: "Futbol ýaryşy gelýän hepde başlaýar.", order: 4 },
    { wordEn: "physical", wordTk: "fiziki / beden", partOfSpeech: "adjective", exampleEn: "Physical exercise is important.", exampleTk: "Beden maşky möhümdir.", order: 5 },
    { wordEn: "coach", wordTk: "tälimçi / türgenleşdiriji", partOfSpeech: "noun", exampleEn: "The coach trains the team every day.", exampleTk: "Tälimçi topary her gün türgenleşdirýär.", order: 6 },
    { wordEn: "medal", wordTk: "medal", partOfSpeech: "noun", exampleEn: "She won a gold medal.", exampleTk: "Ol altyn medal aldy.", order: 7 },
    { wordEn: "defeat", wordTk: "ýeňmek / ýeňliş", partOfSpeech: "verb", exampleEn: "Our team defeated the champion.", exampleTk: "Biziň toparymyz çempiony ýeňdi.", order: 8 },
    { wordEn: "stadium", wordTk: "stadion", partOfSpeech: "noun", exampleEn: "The stadium holds 50,000 people.", exampleTk: "Stadion 50 000 adamy sygdyrýar.", order: 9 },
    { wordEn: "victory", wordTk: "ýeňiş / üstünlik", partOfSpeech: "noun", exampleEn: "Victory came after years of training.", exampleTk: "Ýeňiş ýyllarca türgenleşmeden soň geldi.", order: 10 },
  ]},
  { weekNumber: 26, titleEn: "Week 26: War and Peace", titleTk: "26-njy Hepde: Uruş we Parahatçylyk", words: [
    { wordEn: "conflict", wordTk: "çaknyşma / gapma-garşylyk", partOfSpeech: "noun", exampleEn: "Conflicts cause much suffering.", exampleTk: "Çaknyşmalar köp ejir getirýär.", order: 1 },
    { wordEn: "peace", wordTk: "parahatçylyk / asudalyk", partOfSpeech: "noun", exampleEn: "We all want peace in the world.", exampleTk: "Hemmämiz dünýäde parahatçylyk isleýäris.", order: 2 },
    { wordEn: "soldier", wordTk: "esger / harby", partOfSpeech: "noun", exampleEn: "Soldiers protect their country.", exampleTk: "Esgerler ýurtlaryny goraýarlar.", order: 3 },
    { wordEn: "weapon", wordTk: "ýarag / quwal", partOfSpeech: "noun", exampleEn: "Weapons should be used only for defence.", exampleTk: "Ýaraglar diňe goranyş üçin ulanylmaly.", order: 4 },
    { wordEn: "defend", wordTk: "goramak / gorananmak", partOfSpeech: "verb", exampleEn: "We must defend our country.", exampleTk: "Ýurdumyzy goramaly.", order: 5 },
    { wordEn: "negotiate", wordTk: "gepleşik geçirmek / ylalaşmak", partOfSpeech: "verb", exampleEn: "Countries must negotiate for peace.", exampleTk: "Ýurtlar parahatçylyk üçin gepleşik geçirmeli.", order: 6 },
    { wordEn: "treaty", wordTk: "şertnama / ylalaşyk", partOfSpeech: "noun", exampleEn: "The peace treaty was signed in 1945.", exampleTk: "Parahatçylyk şertnamasy 1945-nji ýylda gol çekildi.", order: 7 },
    { wordEn: "victory", wordTk: "ýeňiş", partOfSpeech: "noun", exampleEn: "They celebrated the victory.", exampleTk: "Olar ýeňişi bellediler.", order: 8 },
    { wordEn: "freedom", wordTk: "azatlyk / erkinlik", partOfSpeech: "noun", exampleEn: "Freedom is worth fighting for.", exampleTk: "Azatlyk üçin söweşmä arzydyr.", order: 9 },
    { wordEn: "alliance", wordTk: "ittifak / birleşme", partOfSpeech: "noun", exampleEn: "The two countries formed an alliance.", exampleTk: "Iki ýurt ittifak döretdi.", order: 10 },
  ]},
];
