import type { SeedVocabSection } from "../../../types/content";

export const weeks27to52: SeedVocabSection[] = [
  { weekNumber: 27, titleEn: "Week 27: Happiness", titleTk: "27-nji Hepde: Bagtlylyk", words: [
    { wordEn: "joy", wordTk: "şatlyk / begenç", partOfSpeech: "noun", exampleEn: "Her smile filled me with joy.", exampleTk: "Onuň ýylgyryşy meni şatlyga doldurdy.", order: 1 },
    { wordEn: "cheerful", wordTk: "şadyýan / güler ýüzli", partOfSpeech: "adjective", exampleEn: "She is always cheerful.", exampleTk: "Ol hemişe şadyýandyr.", order: 2 },
    { wordEn: "content", wordTk: "razy / kanagat", partOfSpeech: "adjective", exampleEn: "I am content with what I have.", exampleTk: "Bar zadyma razydyryn.", order: 3 },
    { wordEn: "optimistic", wordTk: "optimistiki / umytly", partOfSpeech: "adjective", exampleEn: "Stay optimistic about the future.", exampleTk: "Geljege umytly bol.", order: 4 },
    { wordEn: "pleasure", wordTk: "lezzet / hezil", partOfSpeech: "noun", exampleEn: "Reading gives me great pleasure.", exampleTk: "Okamak maňa lezzet berýär.", order: 5 },
    { wordEn: "laugh", wordTk: "gülmek / kahkaha urmak", partOfSpeech: "verb", exampleEn: "Laughter is the best medicine.", exampleTk: "Gülki iň gowy dermandyr.", order: 6 },
    { wordEn: "enjoy", wordTk: "hezil etmek / lezzet almak", partOfSpeech: "verb", exampleEn: "Enjoy every moment of life.", exampleTk: "Durmuşyň her pursatyndan lezzet al.", order: 7 },
    { wordEn: "smile", wordTk: "ýylgyrmak / ýylgyryş", partOfSpeech: "verb", exampleEn: "A smile can change someone's day.", exampleTk: "Ýylgyryş biriniň gününi üýtgedip biler.", order: 8 },
    { wordEn: "celebrate", wordTk: "baýramçylyk geçirmek / şatlyk etmek", partOfSpeech: "verb", exampleEn: "Let's celebrate this success!", exampleTk: "Bu üstünligi belläliň!", order: 9 },
    { wordEn: "grateful", wordTk: "minnetdar / şükürly", partOfSpeech: "adjective", exampleEn: "Be grateful for what you have.", exampleTk: "Bar zadyňa minnetdar bol.", order: 10 },
  ]},
  { weekNumber: 28, titleEn: "Week 28: Sadness", titleTk: "28-nji Hepde: Gynanç", words: [
    { wordEn: "grief", wordTk: "ýas / hasrat", partOfSpeech: "noun", exampleEn: "She was overcome with grief.", exampleTk: "Ony hasrat basdyrdy.", order: 1 },
    { wordEn: "sorrow", wordTk: "gynанç / gaýgy", partOfSpeech: "noun", exampleEn: "His sorrow was deep.", exampleTk: "Onuň gynançy çuňdy.", order: 2 },
    { wordEn: "mourn", wordTk: "yas tutmak / matam saklamak", partOfSpeech: "verb", exampleEn: "The whole village mourned his death.", exampleTk: "Tutuş oba onuň ölümüne yas tutdy.", order: 3 },
    { wordEn: "lonely", wordTk: "ýeke / ýalňyz", partOfSpeech: "adjective", exampleEn: "She felt very lonely.", exampleTk: "Ol özüni gaty ýeke duýdy.", order: 4 },
    { wordEn: "regret", wordTk: "puşman bolmak / ökünmek", partOfSpeech: "verb", exampleEn: "I regret not studying harder.", exampleTk: "Gowy okamadym, şonuň üçin ökünýärin.", order: 5 },
    { wordEn: "miss", wordTk: "küýsemek / zar çekmek", partOfSpeech: "verb", exampleEn: "I miss my family so much.", exampleTk: "Maşgalamy gaty küýseýärin.", order: 6 },
    { wordEn: "cry", wordTk: "aglamak / gözýaş dökmek", partOfSpeech: "verb", exampleEn: "She cried when she heard the news.", exampleTk: "Habary eşidende ol aglady.", order: 7 },
    { wordEn: "depress", wordTk: "gaýgylandyrmak / ruhdan düşürmek", partOfSpeech: "verb", exampleEn: "Bad news can depress people.", exampleTk: "Erbet habar adamlary ruhdan düşürip biler.", order: 8 },
    { wordEn: "loss", wordTk: "ýitgi / ýitirmek", partOfSpeech: "noun", exampleEn: "The loss of a friend is very painful.", exampleTk: "Dostundan jyda bolmak gaty agyr.", order: 9 },
    { wordEn: "comfort", wordTk: "teselli bermek / aram bermek", partOfSpeech: "verb", exampleEn: "She comforted her friend.", exampleTk: "Ol dostuna teselli berdi.", order: 10 },
  ]},
  { weekNumber: 29, titleEn: "Week 29: Memory", titleTk: "29-njy Hepde: Ýat", words: [
    { wordEn: "remember", wordTk: "ýatlamak / ýatda saklamak", partOfSpeech: "verb", exampleEn: "I remember every detail.", exampleTk: "Her jikme-jigi ýatlaýaryn.", order: 1 },
    { wordEn: "forget", wordTk: "unutmak / ýatdan çykarmak", partOfSpeech: "verb", exampleEn: "Don't forget your homework.", exampleTk: "Öý işiňi unutma.", order: 2 },
    { wordEn: "remind", wordTk: "ýatlatmak / habar bermek", partOfSpeech: "verb", exampleEn: "Remind me to call her.", exampleTk: "Oňa jaň etmegi ýatlat.", order: 3 },
    { wordEn: "recall", wordTk: "ýadyna salmak / ýatlamak", partOfSpeech: "verb", exampleEn: "I can't recall his name.", exampleTk: "Adyny ýatlap bilemok.", order: 4 },
    { wordEn: "nostalgia", wordTk: "geçmişe bolan söýgi / ýatlama", partOfSpeech: "noun", exampleEn: "I feel nostalgia for my childhood.", exampleTk: "Çagalygym üçin nostalgiýa duýýaryn.", order: 5 },
    { wordEn: "vivid", wordTk: "aýdyň / ötgür", partOfSpeech: "adjective", exampleEn: "I have vivid memories of that day.", exampleTk: "Şol günüň aýdyň ýatlamalary bar.", order: 6 },
    { wordEn: "experience", wordTk: "tejribe / başdan geçirme", partOfSpeech: "noun", exampleEn: "Experience is the best teacher.", exampleTk: "Tejribe iň gowy mugallym.", order: 7 },
    { wordEn: "past", wordTk: "geçmiş / geçen", partOfSpeech: "noun", exampleEn: "Learn from your past.", exampleTk: "Geçmişden öwren.", order: 8 },
    { wordEn: "memorize", wordTk: "ýat tutmak / ezberlemek", partOfSpeech: "verb", exampleEn: "Memorize these new words.", exampleTk: "Bu täze sözleri ýat tut.", order: 9 },
    { wordEn: "store", wordTk: "saklamak / ýatda saklamak", partOfSpeech: "verb", exampleEn: "The brain stores memories.", exampleTk: "Beýin ýatlamalary saklaýar.", order: 10 },
  ]},
  { weekNumber: 30, titleEn: "Week 30: Success", titleTk: "30-njy Hepde: Üstünlik", words: [
    { wordEn: "goal", wordTk: "maksat / wezipe", partOfSpeech: "noun", exampleEn: "Set clear goals for yourself.", exampleTk: "Özüňiz üçin anyk maksatlar goýuň.", order: 1 },
    { wordEn: "famous", wordTk: "meşhur / belli", partOfSpeech: "adjective", exampleEn: "She became famous worldwide.", exampleTk: "Ol dünýä boýunça meşhur boldy.", order: 2 },
    { wordEn: "inspire", wordTk: "ylham bermek / höweslendirmek", partOfSpeech: "verb", exampleEn: "Her story inspires many people.", exampleTk: "Onuň hekaýasy köp adama ylham berýär.", order: 3 },
    { wordEn: "lead", wordTk: "ýolbaşçylyk etmek / öňde bolmak", partOfSpeech: "verb", exampleEn: "Lead by example.", exampleTk: "Öz göreldäňle ýolbaşçylyk et.", order: 4 },
    { wordEn: "achieve", wordTk: "gazanmak / ýetmek", partOfSpeech: "verb", exampleEn: "You can achieve great things.", exampleTk: "Uly zatlar gazanyp bilersiňiz.", order: 5 },
    { wordEn: "plan", wordTk: "meýilnama / plan", partOfSpeech: "noun", exampleEn: "Make a plan and follow it.", exampleTk: "Meýilnama düz we oňa eýer.", order: 6 },
    { wordEn: "discipline", wordTk: "tertip-düzgün / özüňi dolandyrmak", partOfSpeech: "noun", exampleEn: "Discipline is the key to success.", exampleTk: "Tertip-düzgün üstünligiň açarydyr.", order: 7 },
    { wordEn: "ambition", wordTk: "tutanýerlilik / belent maksat", partOfSpeech: "noun", exampleEn: "Ambition drives people forward.", exampleTk: "Tutanýerlilik adamlary öňe itýär.", order: 8 },
    { wordEn: "accomplish", wordTk: "amala aşyrmak / bitirmek", partOfSpeech: "verb", exampleEn: "I accomplished my dream.", exampleTk: "Arzuwymi amala aşyrdym.", order: 9 },
    { wordEn: "proud", wordTk: "buýsanýan / gurply", partOfSpeech: "adjective", exampleEn: "I am proud of your progress.", exampleTk: "Öňegidişligiňize buýsanýaryn.", order: 10 },
  ]},
  { weekNumber: 31, titleEn: "Week 31: Failure", titleTk: "31-nji Hepde: Şowsuzlyk", words: [
    { wordEn: "fail", wordTk: "başartmazmak / şowsuz bolmak", partOfSpeech: "verb", exampleEn: "Failing is part of learning.", exampleTk: "Başartmazlyk öwrenmäniň bölegidir.", order: 1 },
    { wordEn: "mistake", wordTk: "ýalňyşlyk / säwlik", partOfSpeech: "noun", exampleEn: "Everyone makes mistakes.", exampleTk: "Hemmeler ýalňyşlyk edýär.", order: 2 },
    { wordEn: "error", wordTk: "ýalňyşlyk / säwlik", partOfSpeech: "noun", exampleEn: "Correct your errors and move forward.", exampleTk: "Ýalňyşlyklarňy düzelt we öňe git.", order: 3 },
    { wordEn: "blame", wordTk: "günälemek / aýyplamak", partOfSpeech: "verb", exampleEn: "Don't blame others for your mistakes.", exampleTk: "Ýalňyşlyklaryň üçin başgalary aýyplama.", order: 4 },
    { wordEn: "disappoint", wordTk: "umydyny çykmak / gynandyrmak", partOfSpeech: "verb", exampleEn: "I don't want to disappoint you.", exampleTk: "Siziň umydyňyzy çykarmak istemýärin.", order: 5 },
    { wordEn: "weakness", wordTk: "gowşaklyk / ejizlik", partOfSpeech: "noun", exampleEn: "Knowing your weakness helps you improve.", exampleTk: "Gowşaklygyňy bilmek gowulaşmaga kömek edýär.", order: 6 },
    { wordEn: "recover", wordTk: "dikelip gelmek / düzelmek", partOfSpeech: "verb", exampleEn: "Recover from failure and try again.", exampleTk: "Şowsuzlukdan diklenip, gaýtadan synanyş.", order: 7 },
    { wordEn: "improve", wordTk: "gowulaşdyrmak / has gowy etmek", partOfSpeech: "verb", exampleEn: "Always try to improve yourself.", exampleTk: "Hemişe özüňi gowulaşdyrmaga çalyş.", order: 8 },
    { wordEn: "lesson", wordTk: "sapak / öwrenmeli zat", partOfSpeech: "noun", exampleEn: "Every failure teaches a lesson.", exampleTk: "Her şowsuzlyk bir sapak öwredýär.", order: 9 },
    { wordEn: "overcome", wordTk: "ýeňmek / aşmak", partOfSpeech: "verb", exampleEn: "She overcame every difficulty.", exampleTk: "Ol her kynçylygy ýeňdi.", order: 10 },
  ]},
  { weekNumber: 32, titleEn: "Week 32: Justice", titleTk: "32-nji Hepde: Adalat", words: [
    { wordEn: "fair", wordTk: "adalatly / deň", partOfSpeech: "adjective", exampleEn: "Be fair to everyone.", exampleTk: "Hemmä adalatly bol.", order: 1 },
    { wordEn: "equal", wordTk: "deň / birmeňzeş", partOfSpeech: "adjective", exampleEn: "Everyone deserves equal rights.", exampleTk: "Hemmeler deň hukuklara mynasybydyr.", order: 2 },
    { wordEn: "law", wordTk: "kanun / hukuk", partOfSpeech: "noun", exampleEn: "Everyone must follow the law.", exampleTk: "Hemmeler kanuna boýun bolmaly.", order: 3 },
    { wordEn: "judge", wordTk: "kazyýet / kazyýetçi", partOfSpeech: "noun", exampleEn: "The judge made a fair decision.", exampleTk: "Kazyýetçi adalatly karar berdi.", order: 4 },
    { wordEn: "innocent", wordTk: "bigünä / günäsiz", partOfSpeech: "adjective", exampleEn: "She was proved innocent.", exampleTk: "Ol bigünä subut edildi.", order: 5 },
    { wordEn: "truth", wordTk: "hakykat / dogrulyk", partOfSpeech: "noun", exampleEn: "Always tell the truth.", exampleTk: "Hemişe hakykaty aýt.", order: 6 },
    { wordEn: "right", wordTk: "hukuk / dogry", partOfSpeech: "noun", exampleEn: "Education is a basic right.", exampleTk: "Bilim esasy hukukdur.", order: 7 },
    { wordEn: "court", wordTk: "kazyýet / sud", partOfSpeech: "noun", exampleEn: "The case was heard in court.", exampleTk: "Iş kazyýetde garaldy.", order: 8 },
    { wordEn: "punish", wordTk: "jezalandyrmak", partOfSpeech: "verb", exampleEn: "Crime must be punished.", exampleTk: "Jenaýat jezalandyrylmaly.", order: 9 },
    { wordEn: "protect", wordTk: "goramak", partOfSpeech: "verb", exampleEn: "Laws protect citizens.", exampleTk: "Kanunlar raýatlary goraýar.", order: 10 },
  ]},
  { weekNumber: 33, titleEn: "Week 33: Leadership", titleTk: "33-nji Hepde: Liderlik", words: [
    { wordEn: "motivate", wordTk: "höweslendirmek / ruhlandyrmak", partOfSpeech: "verb", exampleEn: "A good leader motivates the team.", exampleTk: "Gowy ýolbaşçy topary höweslendirýär.", order: 1 },
    { wordEn: "vision", wordTk: "görüş / maksatly pikir", partOfSpeech: "noun", exampleEn: "She has a clear vision for the future.", exampleTk: "Onuň geljek üçin anyk görüşi bar.", order: 2 },
    { wordEn: "responsible", wordTk: "jogapkär / borçly", partOfSpeech: "adjective", exampleEn: "Leaders must be responsible.", exampleTk: "Ýolbaşçylar jogapkär bolmaly.", order: 3 },
    { wordEn: "decide", wordTk: "karar bermek / çözgüt çykarmak", partOfSpeech: "verb", exampleEn: "Leaders must decide quickly.", exampleTk: "Ýolbaşçylar çalt karar bermeli.", order: 4 },
    { wordEn: "direct", wordTk: "ugur bermek / dolandyrmak", partOfSpeech: "verb", exampleEn: "She directs a team of 20 people.", exampleTk: "Ol 20 adamdan ybarat topara ugur berýär.", order: 5 },
    { wordEn: "teamwork", wordTk: "topar işi / bilelikde çalyşma", partOfSpeech: "noun", exampleEn: "Teamwork achieves great results.", exampleTk: "Topar işi ajaýyp netijelere ýetirýär.", order: 6 },
    { wordEn: "initiative", wordTk: "başlangyç / inisiatiwа", partOfSpeech: "noun", exampleEn: "Take initiative and lead.", exampleTk: "Başlangyç al we ýolbaşçylyk et.", order: 7 },
    { wordEn: "delegate", wordTk: "tabşyrmagy başgaça berip",  partOfSpeech: "verb", exampleEn: "Good leaders delegate tasks.", exampleTk: "Gowy ýolbaşçylar tabşyryklary paýlaýarlar.", order: 8 },
    { wordEn: "trust", wordTk: "ynanmak / bil baglamak", partOfSpeech: "verb", exampleEn: "Team members must trust each other.", exampleTk: "Topar agzalary bir-birine ynanmaly.", order: 9 },
    { wordEn: "guide", wordTk: "gollanmak / ýol görkezmek", partOfSpeech: "verb", exampleEn: "Leaders guide their teams.", exampleTk: "Ýolbaşçylar toparlaryna ýol görkezýärler.", order: 10 },
  ]},
  { weekNumber: 34, titleEn: "Week 34: Responsibility", titleTk: "34-nji Hepde: Jogapkärçilik", words: [
    { wordEn: "duty", wordTk: "borç / wezipe", partOfSpeech: "noun", exampleEn: "It is our duty to help others.", exampleTk: "Başgalara kömek etmek biziň borjumyz.", order: 1 },
    { wordEn: "obligation", wordTk: "borçnama / hökmanlyk", partOfSpeech: "noun", exampleEn: "We have an obligation to our community.", exampleTk: "Jemgyýetimize borçnamyz bar.", order: 2 },
    { wordEn: "accountable", wordTk: "jogapkär / hasap beriji", partOfSpeech: "adjective", exampleEn: "Be accountable for your actions.", exampleTk: "Hereketleriňiz üçin jogapkär bol.", order: 3 },
    { wordEn: "reliable", wordTk: "ygtybarly / bil baglanýan", partOfSpeech: "adjective", exampleEn: "She is a reliable person.", exampleTk: "Ol ygtybarly adamdyr.", order: 4 },
    { wordEn: "commit", wordTk: "borçlanmak / karar bermek", partOfSpeech: "verb", exampleEn: "Commit to your goals.", exampleTk: "Maksatlaryna borçlan.", order: 5 },
    { wordEn: "fulfill", wordTk: "ýerine ýetirmek / amala aşyrmak", partOfSpeech: "verb", exampleEn: "Fulfill your promises.", exampleTk: "Sözüňi ýerine ýetir.", order: 6 },
    { wordEn: "careful", wordTk: "seresap / ünsli", partOfSpeech: "adjective", exampleEn: "Be careful with important tasks.", exampleTk: "Möhüm işlerde seresap bol.", order: 7 },
    { wordEn: "accept", wordTk: "kabul etmek / boýun almak", partOfSpeech: "verb", exampleEn: "Accept responsibility for your mistakes.", exampleTk: "Ýalňyşlyklaryň üçin jogapkärçiligi boýun al.", order: 8 },
    { wordEn: "promise", wordTk: "söz bermek / wada etmek", partOfSpeech: "noun", exampleEn: "Keep your promises.", exampleTk: "Sözüňde dur.", order: 9 },
    { wordEn: "dependable", wordTk: "ynançly / bill baglanýan", partOfSpeech: "adjective", exampleEn: "She is a dependable colleague.", exampleTk: "Ol ynançly kärdeş.", order: 10 },
  ]},
  { weekNumber: 35, titleEn: "Week 35: Change", titleTk: "35-nji Hepde: Üýtgeşme", words: [
    { wordEn: "adapt", wordTk: "uýgunlaşmak / üýtgemek", partOfSpeech: "verb", exampleEn: "You must adapt to new situations.", exampleTk: "Täze ýagdaýlara uýgunlaşmaly.", order: 1 },
    { wordEn: "transform", wordTk: "üýtgedip gurmak / özgertmek", partOfSpeech: "verb", exampleEn: "Exercise can transform your health.", exampleTk: "Maşk saglygyňy özgerdip biler.", order: 2 },
    { wordEn: "reform", wordTk: "özgertme / reforma", partOfSpeech: "noun", exampleEn: "Education reform is needed.", exampleTk: "Bilim özgertmesi gerek.", order: 3 },
    { wordEn: "modify", wordTk: "üýtgetmek / düzetmek", partOfSpeech: "verb", exampleEn: "We need to modify our plan.", exampleTk: "Meýilnamany üýtgetmeli.", order: 4 },
    { wordEn: "develop", wordTk: "ösdürmek / kämilleşdirmek", partOfSpeech: "verb", exampleEn: "Develop your skills every day.", exampleTk: "Her gün ukyplaryny ösdür.", order: 5 },
    { wordEn: "shift", wordTk: "üýtgeme / geçiş", partOfSpeech: "noun", exampleEn: "There has been a shift in attitudes.", exampleTk: "Garaýyşlarda üýtgeme boldy.", order: 6 },
    { wordEn: "transition", wordTk: "geçiş / özgerme", partOfSpeech: "noun", exampleEn: "The transition to a new system takes time.", exampleTk: "Täze ulgama geçmek wagt talap edýär.", order: 7 },
    { wordEn: "adjust", wordTk: "sazlamak / düzetmek", partOfSpeech: "verb", exampleEn: "Adjust your plan if needed.", exampleTk: "Zerur bolsa meýilnamaňy sazla.", order: 8 },
    { wordEn: "improve", wordTk: "gowulaşdyrmak", partOfSpeech: "verb", exampleEn: "Always strive to improve.", exampleTk: "Hemişe gowulaşmaga çalyş.", order: 9 },
    { wordEn: "progress", wordTk: "öňegidişlik / ösüş", partOfSpeech: "noun", exampleEn: "Change brings progress.", exampleTk: "Üýtgeşme öňegidişlik getirýär.", order: 10 },
  ]},
  { weekNumber: 36, titleEn: "Week 36: Time", titleTk: "36-njy Hepde: Wagt", words: [
    { wordEn: "moment", wordTk: "pursat / wagt", partOfSpeech: "noun", exampleEn: "Enjoy every moment.", exampleTk: "Her pursaty höwes bilen geçir.", order: 1 },
    { wordEn: "deadline", wordTk: "möhlet / soňky wagt", partOfSpeech: "noun", exampleEn: "Submit your work before the deadline.", exampleTk: "Möhletden öň işiňi tabşyr.", order: 2 },
    { wordEn: "schedule", wordTk: "tertip / meýilnama", partOfSpeech: "noun", exampleEn: "Follow your daily schedule.", exampleTk: "Gündelik tertibiňe eýer.", order: 3 },
    { wordEn: "delay", wordTk: "yza süyşürmek / wagtynda gelmezlik", partOfSpeech: "noun", exampleEn: "There was a delay in the flight.", exampleTk: "Uçarda giçikme boldy.", order: 4 },
    { wordEn: "urgent", wordTk: "gyssagly / derrew edilmeli", partOfSpeech: "adjective", exampleEn: "This is urgent — do it now!", exampleTk: "Bu gyssagly — şindi et!", order: 5 },
    { wordEn: "priority", wordTk: "ileri tutulmaly zat / esasy wezipe", partOfSpeech: "noun", exampleEn: "Family is my priority.", exampleTk: "Maşgala meniň ileri tutýan zadym.", order: 6 },
    { wordEn: "manage", wordTk: "dolandyrmak / başarmak", partOfSpeech: "verb", exampleEn: "Manage your time wisely.", exampleTk: "Wagtyňy akylly dolandyr.", order: 7 },
    { wordEn: "punctual", wordTk: "wagtynda gelýän / takyk", partOfSpeech: "adjective", exampleEn: "Always be punctual.", exampleTk: "Hemişe wagtynda gel.", order: 8 },
    { wordEn: "waste", wordTk: "boşa harçlamak / ýitirmek", partOfSpeech: "verb", exampleEn: "Don't waste your time.", exampleTk: "Wagtyňy boşa harçlama.", order: 9 },
    { wordEn: "spare", wordTk: "boş wagt / artykmaç wagt", partOfSpeech: "adjective", exampleEn: "What do you do in your spare time?", exampleTk: "Boş wagtyňda näme edýärsiňiz?", order: 10 },
  ]},
  { weekNumber: 37, titleEn: "Week 37: Love", titleTk: "37-nji Hepde: Söýgi", words: [
    { wordEn: "affection", wordTk: "mähir / ýakyn duýgy", partOfSpeech: "noun", exampleEn: "She showed great affection.", exampleTk: "Ol uly mähir görkezdi.", order: 1 },
    { wordEn: "tender", wordTk: "mähirli / näzli", partOfSpeech: "adjective", exampleEn: "She spoke in a tender voice.", exampleTk: "Ol mähirli ses bilen gürledi.", order: 2 },
    { wordEn: "romantic", wordTk: "romantiki / söýgi bilen", partOfSpeech: "adjective", exampleEn: "He planned a romantic dinner.", exampleTk: "Ol romantiki agşam naharyny meýilleşdirdi.", order: 3 },
    { wordEn: "devote", wordTk: "bagyşlamak / bermek", partOfSpeech: "verb", exampleEn: "She devoted her life to others.", exampleTk: "Ol ömrüni başgalara bagyşlady.", order: 4 },
    { wordEn: "passion", wordTk: "joşgun / güýçli söýgi", partOfSpeech: "noun", exampleEn: "He has a passion for music.", exampleTk: "Onuň saza bolan güýçli söýgüsi bar.", order: 5 },
    { wordEn: "faithful", wordTk: "wepaly / sadyk", partOfSpeech: "adjective", exampleEn: "Be faithful to the people you love.", exampleTk: "Söýen adamlaryňa wepaly bol.", order: 6 },
    { wordEn: "cherish", wordTk: "gymmat tutmak / söýmek", partOfSpeech: "verb", exampleEn: "Cherish every moment with family.", exampleTk: "Maşgala bilen her pursaty gymmat tut.", order: 7 },
    { wordEn: "admire", wordTk: "haýran galmak / sarpalamak", partOfSpeech: "verb", exampleEn: "I admire her courage.", exampleTk: "Onuň mertligine haýran galýaryn.", order: 8 },
    { wordEn: "care", wordTk: "alada etmek / söýgi", partOfSpeech: "verb", exampleEn: "She cares deeply for her family.", exampleTk: "Ol maşgalasyna çuňňur alada edýär.", order: 9 },
    { wordEn: "bond", wordTk: "baglanyşyk / ýakynlyk", partOfSpeech: "noun", exampleEn: "Love creates a strong bond.", exampleTk: "Söýgi güýçli baglanyşyk döredýär.", order: 10 },
  ]},
  { weekNumber: 38, titleEn: "Week 38: Marriage", titleTk: "38-nji Hepde: Nikah", words: [
    { wordEn: "marry", wordTk: "öýlenmek / durmuşa çykmak", partOfSpeech: "verb", exampleEn: "They married last spring.", exampleTk: "Olar geçen ýazda öýlendiler.", order: 1 },
    { wordEn: "spouse", wordTk: "är-aýal / ýanýoldaş", partOfSpeech: "noun", exampleEn: "Introduce me to your spouse.", exampleTk: "Ýanýoldaşyňyz bilen tanyşdyryň.", order: 2 },
    { wordEn: "wedding", wordTk: "toý / toý dabarasy", partOfSpeech: "noun", exampleEn: "Their wedding was beautiful.", exampleTk: "Olaryň toýy ajaýypdy.", order: 3 },
    { wordEn: "vow", wordTk: "kasam / söz bermek", partOfSpeech: "noun", exampleEn: "They exchanged wedding vows.", exampleTk: "Olar toý kasam alyşdylar.", order: 4 },
    { wordEn: "partner", wordTk: "ýanýoldaş / hyzmatdaş", partOfSpeech: "noun", exampleEn: "She is my business partner.", exampleTk: "Ol meniň iş hyzmatdaşym.", order: 5 },
    { wordEn: "celebrate", wordTk: "bellemek / toý etmek", partOfSpeech: "verb", exampleEn: "They celebrated their anniversary.", exampleTk: "Olar ýyllygyny bellediler.", order: 6 },
    { wordEn: "commit", wordTk: "borçlanmak / wepaly bolmak", partOfSpeech: "verb", exampleEn: "Marriage requires commitment.", exampleTk: "Nikah borçlulyk talap edýär.", order: 7 },
    { wordEn: "anniversary", wordTk: "ýyllyk / bayram güni", partOfSpeech: "noun", exampleEn: "Happy wedding anniversary!", exampleTk: "Toý ýyllygyňyz gutly bolsun!", order: 8 },
    { wordEn: "together", wordTk: "bilelikde / birlikde", partOfSpeech: "adverb", exampleEn: "They work well together.", exampleTk: "Olar bilelikde gowy işleýärler.", order: 9 },
    { wordEn: "divorce", wordTk: "aýrylyşmak / boşanmak", partOfSpeech: "noun", exampleEn: "Divorce is sometimes necessary.", exampleTk: "Käwagt aýrylyşmak zerur bolýar.", order: 10 },
  ]},
  { weekNumber: 39, titleEn: "Week 39: Children", titleTk: "39-njy Hepde: Çagalar", words: [
    { wordEn: "grow", wordTk: "ösüp ulaşmak / ösmek", partOfSpeech: "verb", exampleEn: "Children grow up so fast.", exampleTk: "Çagalar gaty çalt ulalýar.", order: 1 },
    { wordEn: "curious", wordTk: "gyzyklanmaçyl / soragly", partOfSpeech: "adjective", exampleEn: "Children are naturally curious.", exampleTk: "Çagalar tebigy häsiýetde gyzyklanmaçyldyr.", order: 2 },
    { wordEn: "innocent", wordTk: "bigünä / päk", partOfSpeech: "adjective", exampleEn: "Children are innocent.", exampleTk: "Çagalar bigünädir.", order: 3 },
    { wordEn: "playful", wordTk: "oýnawaç / şadyýan", partOfSpeech: "adjective", exampleEn: "My daughter is very playful.", exampleTk: "Gyzym gaty oýnawaçdyr.", order: 4 },
    { wordEn: "nurture", wordTk: "ýetişdirmek / terbiýelemek", partOfSpeech: "verb", exampleEn: "Nurture your child's talents.", exampleTk: "Çagaňyň zehinini ýetişdir.", order: 5 },
    { wordEn: "educate", wordTk: "öwretmek / terbiýe bermek", partOfSpeech: "verb", exampleEn: "Educate your children well.", exampleTk: "Çagalaryňa gowy bilim ber.", order: 6 },
    { wordEn: "protect", wordTk: "goramak", partOfSpeech: "verb", exampleEn: "Protect children from danger.", exampleTk: "Çagalary howpdan gorа.", order: 7 },
    { wordEn: "guide", wordTk: "ýol görkezmek / gollamak", partOfSpeech: "verb", exampleEn: "Parents guide their children.", exampleTk: "Ene-atalar çagalaryna ýol görkezýärler.", order: 8 },
    { wordEn: "develop", wordTk: "ösdürmek / ulaltmak", partOfSpeech: "verb", exampleEn: "Activities develop children's skills.", exampleTk: "Işjeňlik çagalaryň ukyplaryny ösdürýär.", order: 9 },
    { wordEn: "childhood", wordTk: "çagalyk / balалык döwri", partOfSpeech: "noun", exampleEn: "I have happy childhood memories.", exampleTk: "Bagtly çagalyk ýatlamalarym bar.", order: 10 },
  ]},
  { weekNumber: 40, titleEn: "Week 40: Old Age", titleTk: "40-njy Hepde: Garryçylyk", words: [
    { wordEn: "elderly", wordTk: "garry / ýaşuly", partOfSpeech: "adjective", exampleEn: "Respect elderly people.", exampleTk: "Ýaşululara hormat goý.", order: 1 },
    { wordEn: "retire", wordTk: "pensiýa çykmak", partOfSpeech: "verb", exampleEn: "He retired after 40 years of work.", exampleTk: "Ol 40 ýyl işländen soň pensiýa çykdy.", order: 2 },
    { wordEn: "wisdom", wordTk: "paýhas / pähim", partOfSpeech: "noun", exampleEn: "Old age brings wisdom.", exampleTk: "Garryçylyk paýhas getirýär.", order: 3 },
    { wordEn: "legacy", wordTk: "miras / yz", partOfSpeech: "noun", exampleEn: "Leave a positive legacy.", exampleTk: "Oňat miras galdyr.", order: 4 },
    { wordEn: "experience", wordTk: "tejribe / iş başardanlyk", partOfSpeech: "noun", exampleEn: "Her experience is invaluable.", exampleTk: "Onuň tejribesi çäksiz gymmatly.", order: 5 },
    { wordEn: "respect", wordTk: "hormat / sylag", partOfSpeech: "noun", exampleEn: "Show respect to your elders.", exampleTk: "Uly ýaşlylara hormat görkez.", order: 6 },
    { wordEn: "memory", wordTk: "ýat / ýatlama", partOfSpeech: "noun", exampleEn: "Her memory is still sharp.", exampleTk: "Onuň ýady henizem ötgürdür.", order: 7 },
    { wordEn: "senior", wordTk: "uly ýaşly / kätda adam", partOfSpeech: "adjective", exampleEn: "Senior citizens deserve care.", exampleTk: "Uly ýaşly raýatlar alada mynasypdyr.", order: 8 },
    { wordEn: "health", wordTk: "saglyk", partOfSpeech: "noun", exampleEn: "Good health is a gift in old age.", exampleTk: "Garryçylykda gowy saglyk — sowgatdyr.", order: 9 },
    { wordEn: "generation", wordTk: "nesil", partOfSpeech: "noun", exampleEn: "The older generation has much to teach.", exampleTk: "Uly nesliň öwredere köp zady bar.", order: 10 },
  ]},
  { weekNumber: 41, titleEn: "Week 41: Death", titleTk: "41-nji Hepde: Ölüm", words: [
    { wordEn: "death", wordTk: "ölüm / wepat bolmak", partOfSpeech: "noun", exampleEn: "Death is part of life.", exampleTk: "Ölüm durmuşyň bir bölegidir.", order: 1 },
    { wordEn: "funeral", wordTk: "jaýlamak / jenaza", partOfSpeech: "noun", exampleEn: "The funeral was attended by many people.", exampleTk: "Jeňazä köp adam gatnaşdy.", order: 2 },
    { wordEn: "mourn", wordTk: "yas tutmak", partOfSpeech: "verb", exampleEn: "The family mourned for a week.", exampleTk: "Maşgala bir hepde yas tutdy.", order: 3 },
    { wordEn: "memorial", wordTk: "ýatlaýyş / hatyra", partOfSpeech: "noun", exampleEn: "They built a memorial for the hero.", exampleTk: "Olar gahryman üçin hatyra bina gurdylar.", order: 4 },
    { wordEn: "grieve", wordTk: "hasratlanmak / yas çekmek", partOfSpeech: "verb", exampleEn: "It is normal to grieve.", exampleTk: "Yas çekmek tebigy ýagdaý.", order: 5 },
    { wordEn: "soul", wordTk: "jan / ruh", partOfSpeech: "noun", exampleEn: "May his soul rest in peace.", exampleTk: "Jany jennetde bolsun.", order: 6 },
    { wordEn: "legacy", wordTk: "miras / yz goýmak", partOfSpeech: "noun", exampleEn: "She left a wonderful legacy.", exampleTk: "Ol ajaýyp miras galdyrdy.", order: 7 },
    { wordEn: "remember", wordTk: "ýatlamak / ýatda saklamak", partOfSpeech: "verb", exampleEn: "We remember those who have gone.", exampleTk: "Ötenleri ýatlaýarys.", order: 8 },
    { wordEn: "peace", wordTk: "rahatçylyk / dынçlyk", partOfSpeech: "noun", exampleEn: "May she rest in peace.", exampleTk: "Arwаhy şat bolsun.", order: 9 },
    { wordEn: "loss", wordTk: "ýitgi / azap", partOfSpeech: "noun", exampleEn: "The loss of a parent is very hard.", exampleTk: "Ene-atadan jyda bolmak gaty agyr.", order: 10 },
  ]},
  { weekNumber: 42, titleEn: "Week 42: Religion", titleTk: "42-nji Hepde: Din", words: [
    { wordEn: "faith", wordTk: "iman / ynanç", partOfSpeech: "noun", exampleEn: "Faith gives people hope.", exampleTk: "Iman adamlara umyt berýär.", order: 1 },
    { wordEn: "believe", wordTk: "ynanmak / iman etmek", partOfSpeech: "verb", exampleEn: "People believe in different things.", exampleTk: "Adamlar dürli zatlara ynanýarlar.", order: 2 },
    { wordEn: "pray", wordTk: "namaz okamak / doga etmek", partOfSpeech: "verb", exampleEn: "She prays every morning.", exampleTk: "Ol her irden namaz okäýar.", order: 3 },
    { wordEn: "spiritual", wordTk: "ruhy / manewi", partOfSpeech: "adjective", exampleEn: "He is a very spiritual person.", exampleTk: "Ol gaty ruhy adamdyr.", order: 4 },
    { wordEn: "holy", wordTk: "mukaddes / päk", partOfSpeech: "adjective", exampleEn: "Mecca is a holy city.", exampleTk: "Mekge mukaddes şäherdır.", order: 5 },
    { wordEn: "worship", wordTk: "sežde etmek / pygamber tutmak", partOfSpeech: "verb", exampleEn: "People worship in many different ways.", exampleTk: "Adamlar dürli usullarda yhlas edýärler.", order: 6 },
    { wordEn: "tradition", wordTk: "däp / dessur", partOfSpeech: "noun", exampleEn: "Religious traditions are important.", exampleTk: "Dini däpler möhümdir.", order: 7 },
    { wordEn: "morality", wordTk: "ahlak / edep-ekram", partOfSpeech: "noun", exampleEn: "Religion guides morality.", exampleTk: "Din ahlagy gollaýar.", order: 8 },
    { wordEn: "mosque", wordTk: "metjit", partOfSpeech: "noun", exampleEn: "The mosque is beautiful.", exampleTk: "Metjit owadandyr.", order: 9 },
    { wordEn: "pilgrimage", wordTk: "hajy / mukaddes ýere syýahat", partOfSpeech: "noun", exampleEn: "He went on a pilgrimage to Mecca.", exampleTk: "Ol Mekkä hajy etdi.", order: 10 },
  ]},
  { weekNumber: 43, titleEn: "Week 43: Freedom", titleTk: "43-nji Hepde: Azatlyk", words: [
    { wordEn: "freedom", wordTk: "azatlyk / erkinlik", partOfSpeech: "noun", exampleEn: "Freedom is a precious right.", exampleTk: "Azatlyk gymmatly hukukdyr.", order: 1 },
    { wordEn: "independence", wordTk: "garaşsyzlyk / özbaşdaklyk", partOfSpeech: "noun", exampleEn: "Independence Day is celebrated every year.", exampleTk: "Garaşsyzlyk güni her ýyl bellenilýär.", order: 2 },
    { wordEn: "liberty", wordTk: "azatlyk / erk", partOfSpeech: "noun", exampleEn: "Liberty is the right of every person.", exampleTk: "Azatlyk her adamyň hukukdyr.", order: 3 },
    { wordEn: "choice", wordTk: "saýlamak / talap etmek", partOfSpeech: "noun", exampleEn: "Everyone has the right to choice.", exampleTk: "Her adamyň saýlamak hukugy bar.", order: 4 },
    { wordEn: "democracy", wordTk: "demokratiýa", partOfSpeech: "noun", exampleEn: "Democracy gives power to the people.", exampleTk: "Demokratiýa halka güýç berýär.", order: 5 },
    { wordEn: "release", wordTk: "boşatmak / serbest goýbermek", partOfSpeech: "verb", exampleEn: "They released the prisoners.", exampleTk: "Olar tussaglary boşatdylar.", order: 6 },
    { wordEn: "escape", wordTk: "gaçmak / sypmak", partOfSpeech: "verb", exampleEn: "He escaped from the difficult situation.", exampleTk: "Ol kyn ýagdaýdan sypdy.", order: 7 },
    { wordEn: "rights", wordTk: "hukuklar", partOfSpeech: "noun", exampleEn: "Protect human rights.", exampleTk: "Adam hukuklaryny gora.", order: 8 },
    { wordEn: "open", wordTk: "açyk / erkin", partOfSpeech: "adjective", exampleEn: "An open society values freedom.", exampleTk: "Açyk jemgyýet azatlygy gadyrlaýar.", order: 9 },
    { wordEn: "express", wordTk: "aňlatmak / bildirmek", partOfSpeech: "verb", exampleEn: "Express yourself freely.", exampleTk: "Özüňi erkin aňlat.", order: 10 },
  ]},
  { weekNumber: 44, titleEn: "Week 44: Government", titleTk: "44-nji Hepde: Hökümet", words: [
    { wordEn: "government", wordTk: "hökümet / döwlet", partOfSpeech: "noun", exampleEn: "The government makes laws.", exampleTk: "Hökümet kanunlar kabul edýär.", order: 1 },
    { wordEn: "elect", wordTk: "saýlamak / ses bermek", partOfSpeech: "verb", exampleEn: "Citizens elect their leaders.", exampleTk: "Raýatlar ýolbaşçylaryny saýlaýarlar.", order: 2 },
    { wordEn: "vote", wordTk: "ses bermek / saýlaw", partOfSpeech: "verb", exampleEn: "Vote for a better future.", exampleTk: "Has gowy geljek üçin ses ber.", order: 3 },
    { wordEn: "policy", wordTk: "syýasat / maksatnama", partOfSpeech: "noun", exampleEn: "New education policy was announced.", exampleTk: "Täze bilim syýasaty yglan edildi.", order: 4 },
    { wordEn: "citizen", wordTk: "raýat / ýerli adam", partOfSpeech: "noun", exampleEn: "Every citizen has rights.", exampleTk: "Her raýatyň hukuklary bar.", order: 5 },
    { wordEn: "tax", wordTk: "salgyt / töleg", partOfSpeech: "noun", exampleEn: "Citizens pay taxes.", exampleTk: "Raýatlar salgyt töleýärler.", order: 6 },
    { wordEn: "represent", wordTk: "wekilçilik etmek / bilen höküm sürmek", partOfSpeech: "verb", exampleEn: "Parliament represents the people.", exampleTk: "Parlament halky wekilçilik edýär.", order: 7 },
    { wordEn: "parliament", wordTk: "parlament / mejlis", partOfSpeech: "noun", exampleEn: "The parliament passed the law.", exampleTk: "Parlament kanuny kabul etdi.", order: 8 },
    { wordEn: "leader", wordTk: "ýolbaşçy / lider", partOfSpeech: "noun", exampleEn: "A good leader serves the people.", exampleTk: "Gowy ýolbaşçy halka hyzmat edýär.", order: 9 },
    { wordEn: "minister", wordTk: "ministr / wezipeli adam", partOfSpeech: "noun", exampleEn: "The minister announced new plans.", exampleTk: "Ministr täze meýilnamalary yglan etdi.", order: 10 },
  ]},
  { weekNumber: 45, titleEn: "Week 45: Environment", titleTk: "45-nji Hepde: Daşky Gurşaw", words: [
    { wordEn: "pollute", wordTk: "hapalaýmak / zaýalamak", partOfSpeech: "verb", exampleEn: "Factories pollute the air.", exampleTk: "Zawodlar howany hapalanýar.", order: 1 },
    { wordEn: "recycle", wordTk: "gaýtadan işlemek / ullanmak", partOfSpeech: "verb", exampleEn: "Recycle paper and plastic.", exampleTk: "Kagyzy we plastiki gaýtadan işle.", order: 2 },
    { wordEn: "waste", wordTk: "galyndylar / hapa", partOfSpeech: "noun", exampleEn: "Reduce your waste.", exampleTk: "Galyndylaryňy azalt.", order: 3 },
    { wordEn: "climate change", wordTk: "howa üýtgemesi / klimat üýtgemesi", partOfSpeech: "noun", exampleEn: "Climate change affects everyone.", exampleTk: "Howa üýtgemesi hemmä täsir edýär.", order: 4 },
    { wordEn: "sustainable", wordTk: "durnukly / uzak möhletli", partOfSpeech: "adjective", exampleEn: "Use sustainable energy.", exampleTk: "Durnukly energiýa ulan.", order: 5 },
    { wordEn: "renewable", wordTk: "täzelenip bolýan / gaýtalanyp bolýan", partOfSpeech: "adjective", exampleEn: "Solar power is renewable energy.", exampleTk: "Gün energiýasy täzelenip bolýan energiýa.", order: 6 },
    { wordEn: "carbon", wordTk: "uglerod / kömür gazy", partOfSpeech: "noun", exampleEn: "Reduce your carbon footprint.", exampleTk: "Uglerod yzyny azalt.", order: 7 },
    { wordEn: "green", wordTk: "ýaşyl / daşky gurşawa dostlukly", partOfSpeech: "adjective", exampleEn: "Choose green products.", exampleTk: "Ýaşyl önümleri saý.", order: 8 },
    { wordEn: "protect", wordTk: "goramak", partOfSpeech: "verb", exampleEn: "Protect the environment for future generations.", exampleTk: "Geljek nesiller üçin daşky gurşawy gora.", order: 9 },
    { wordEn: "natural", wordTk: "tebigy / tebigata degişli", partOfSpeech: "adjective", exampleEn: "Use natural materials.", exampleTk: "Tebigy materiallary ulan.", order: 10 },
  ]},
  { weekNumber: 46, titleEn: "Week 46: Poverty and Wealth", titleTk: "46-njy Hepde: Garyplyk we Baýlyk", words: [
    { wordEn: "wealthy", wordTk: "baý / bol-telkilik", partOfSpeech: "adjective", exampleEn: "Being wealthy doesn't mean being happy.", exampleTk: "Baý bolmak bagtly bolmak däldir.", order: 1 },
    { wordEn: "gap", wordTk: "araçäk / tapawut", partOfSpeech: "noun", exampleEn: "The gap between rich and poor is growing.", exampleTk: "Baý we garyplygyň araçäki ösýär.", order: 2 },
    { wordEn: "income", wordTk: "girdeji", partOfSpeech: "noun", exampleEn: "His income is very low.", exampleTk: "Onuň girdejisi gaty pesdir.", order: 3 },
    { wordEn: "luxury", wordTk: "lüks / parhly ýaşaýyş", partOfSpeech: "noun", exampleEn: "They live in luxury.", exampleTk: "Olar lüks durmuşda ýaşaýarlar.", order: 4 },
    { wordEn: "distribute", wordTk: "paýlamak / üleşmek", partOfSpeech: "verb", exampleEn: "Distribute resources fairly.", exampleTk: "Serişdeleri adalatly paýla.", order: 5 },
    { wordEn: "economic", wordTk: "ykdysady / maliýe", partOfSpeech: "adjective", exampleEn: "Economic growth helps everyone.", exampleTk: "Ykdysady ösüş hemmä kömek edýär.", order: 6 },
    { wordEn: "donate", wordTk: "bagyşlamak / goşant goşmak", partOfSpeech: "verb", exampleEn: "Please donate to help the poor.", exampleTk: "Garplara kömek üçin goşant goş.", order: 7 },
    { wordEn: "afford", wordTk: "satyn alyp bilmek", partOfSpeech: "verb", exampleEn: "Not everyone can afford medicine.", exampleTk: "Hemmeler derman satyn alyp bilmeýär.", order: 8 },
    { wordEn: "resources", wordTk: "serişdeler / mümkinçilikler", partOfSpeech: "noun", exampleEn: "Use resources wisely.", exampleTk: "Serişdeleri akylly ulan.", order: 9 },
    { wordEn: "equality", wordTk: "deňlik / adalat", partOfSpeech: "noun", exampleEn: "Economic equality is a goal.", exampleTk: "Ykdysady deňlik maksat.", order: 10 },
  ]},
  { weekNumber: 47, titleEn: "Week 47: Literature", titleTk: "47-nji Hepde: Edebiýat", words: [
    { wordEn: "author", wordTk: "ýazyjy / awtor", partOfSpeech: "noun", exampleEn: "Who is your favourite author?", exampleTk: "Siziň söýgüli ýazyjyňyz kim?", order: 1 },
    { wordEn: "fiction", wordTk: "çeper edebiýat / toslama", partOfSpeech: "noun", exampleEn: "I love reading science fiction.", exampleTk: "Men ylmy çeper edebiýat okamaklygy halaýaryn.", order: 2 },
    { wordEn: "character", wordTk: "gahryman / esasy şahsyýet", partOfSpeech: "noun", exampleEn: "The main character is very brave.", exampleTk: "Baş gahryman gaty mertdir.", order: 3 },
    { wordEn: "chapter", wordTk: "bap / bölüm", partOfSpeech: "noun", exampleEn: "I read three chapters last night.", exampleTk: "Düýn agşam üç bap okadym.", order: 4 },
    { wordEn: "publish", wordTk: "neşir etmek / çap etmek", partOfSpeech: "verb", exampleEn: "The book was published last year.", exampleTk: "Kitap geçen ýyl neşir edildi.", order: 5 },
    { wordEn: "poem", wordTk: "şygyr / goşgy", partOfSpeech: "noun", exampleEn: "Magtymguly wrote beautiful poems.", exampleTk: "Magtymguly owadan şygyrlary ýazdy.", order: 6 },
    { wordEn: "novel", wordTk: "roman / çeper kitap", partOfSpeech: "noun", exampleEn: "She wrote a famous novel.", exampleTk: "Ol meşhur roman ýazdy.", order: 7 },
    { wordEn: "describe", wordTk: "suratlandyrmak / beýan etmek", partOfSpeech: "verb", exampleEn: "The author describes the city beautifully.", exampleTk: "Ýazyjy şäheri owadan suratlandyrýar.", order: 8 },
    { wordEn: "imagine", wordTk: "göz öňüne getirmek / hyýal etmek", partOfSpeech: "verb", exampleEn: "Imagine a world without problems.", exampleTk: "Meselesi bolmadyk dünýäni göz öňüne getir.", order: 9 },
    { wordEn: "plot", wordTk: "sýužet / oturgyç", partOfSpeech: "noun", exampleEn: "The plot of this novel is exciting.", exampleTk: "Bu romanyň sýužeti gyzykly.", order: 10 },
  ]},
  { weekNumber: 48, titleEn: "Week 48: History", titleTk: "48-nji Hepde: Taryh", words: [
    { wordEn: "ancient", wordTk: "gadymy / eski", partOfSpeech: "adjective", exampleEn: "Turkmenistan has ancient civilizations.", exampleTk: "Türkmenistanda gadymy medeniýetler bar.", order: 1 },
    { wordEn: "event", wordTk: "waka / hadysa", partOfSpeech: "noun", exampleEn: "This was an important historical event.", exampleTk: "Bu möhüm taryhy wakady.", order: 2 },
    { wordEn: "empire", wordTk: "imperiýa / gulçulyk döwleti", partOfSpeech: "noun", exampleEn: "The Roman Empire was powerful.", exampleTk: "Rim imperiýasy güýçlüdi.", order: 3 },
    { wordEn: "conquer", wordTk: "basyp almak / ýeňmek", partOfSpeech: "verb", exampleEn: "Alexander conquered many lands.", exampleTk: "Aleksandr köp ýerleri basyp aldy.", order: 4 },
    { wordEn: "civilization", wordTk: "medeniýet / sivilizasiýa", partOfSpeech: "noun", exampleEn: "Great civilizations have built this world.", exampleTk: "Beýik medeniýetler bu dünýäni gurdy.", order: 5 },
    { wordEn: "century", wordTk: "asyr / ýüz ýyl", partOfSpeech: "noun", exampleEn: "This building is from the 19th century.", exampleTk: "Bu bina 19-njy asyra degişli.", order: 6 },
    { wordEn: "record", wordTk: "ýazga almak / belgelemek", partOfSpeech: "verb", exampleEn: "Historians record important events.", exampleTk: "Taryhçylar möhüm wakalary belgeläýärler.", order: 7 },
    { wordEn: "revolution", wordTk: "rewolýusiýa / uly özgerme", partOfSpeech: "noun", exampleEn: "The Industrial Revolution changed the world.", exampleTk: "Senagat rewolýusiýasy dünýäni üýtgetdi.", order: 8 },
    { wordEn: "monument", wordTk: "ýadygärlik / abadanlyk", partOfSpeech: "noun", exampleEn: "The monument was built in memory of heroes.", exampleTk: "Ýadygärlik gahrymanlaryň hatyrasyna guruldy.", order: 9 },
    { wordEn: "heritage", wordTk: "miras / geçmiş mirasy", partOfSpeech: "noun", exampleEn: "Protect your cultural heritage.", exampleTk: "Medeni mirasynňy gora.", order: 10 },
  ]},
  { weekNumber: 49, titleEn: "Week 49: Language", titleTk: "49-njy Hepde: Dil", words: [
    { wordEn: "grammar", wordTk: "grammatika / dil düzgüni", partOfSpeech: "noun", exampleEn: "Good grammar helps you communicate.", exampleTk: "Gowy grammatika aragatnaşyga kömek edýär.", order: 1 },
    { wordEn: "vocabulary", wordTk: "sözlük / söz baýlygy", partOfSpeech: "noun", exampleEn: "Expand your vocabulary every day.", exampleTk: "Her gün söz baýlygyňy giňelt.", order: 2 },
    { wordEn: "fluent", wordTk: "erkin gepleşik / akymly", partOfSpeech: "adjective", exampleEn: "She speaks fluent English.", exampleTk: "Ol Iňlisçe erkin gepleşýär.", order: 3 },
    { wordEn: "accent", wordTk: "aksan / gürrüň tarzy", partOfSpeech: "noun", exampleEn: "She has a beautiful accent.", exampleTk: "Onuň owadan aksany bar.", order: 4 },
    { wordEn: "dialect", wordTk: "dialekt / şywe", partOfSpeech: "noun", exampleEn: "Different regions have different dialects.", exampleTk: "Dürli sebitlerde dürli şyweler bar.", order: 5 },
    { wordEn: "translate", wordTk: "terjime etmek", partOfSpeech: "verb", exampleEn: "Can you translate this sentence?", exampleTk: "Bu jümläni terjime edip bilersiňizmi?", order: 6 },
    { wordEn: "bilingual", wordTk: "iki dilli / iki dilden bilen", partOfSpeech: "adjective", exampleEn: "She is bilingual in English and Turkmen.", exampleTk: "Ol Iňlis we Türkmen dillerini bilýär.", order: 7 },
    { wordEn: "native", wordTk: "ene dili / doğal", partOfSpeech: "adjective", exampleEn: "Turkmen is my native language.", exampleTk: "Türkmen meniň ene dilim.", order: 8 },
    { wordEn: "phrase", wordTk: "jümle / söz düzmesi", partOfSpeech: "noun", exampleEn: "Learn useful phrases first.", exampleTk: "Ilki peýdaly jümleleri öwren.", order: 9 },
    { wordEn: "pronounce", wordTk: "aýtmak / telaffuz etmek", partOfSpeech: "verb", exampleEn: "Pronounce each word clearly.", exampleTk: "Her sözi anyk aýt.", order: 10 },
  ]},
  { weekNumber: 50, titleEn: "Week 50: Cities and Buildings", titleTk: "50-nji Hepde: Şäherler we Binalar", words: [
    { wordEn: "urban", wordTk: "şäher / şähere degişli", partOfSpeech: "adjective", exampleEn: "Urban life is very busy.", exampleTk: "Şäher durmuşy gaty güýçli.", order: 1 },
    { wordEn: "construct", wordTk: "gurmak / inşa etmek", partOfSpeech: "verb", exampleEn: "They constructed a new bridge.", exampleTk: "Olar täze köpri gurdylar.", order: 2 },
    { wordEn: "architect", wordTk: "arhitektor / bina inženeri", partOfSpeech: "noun", exampleEn: "She is a famous architect.", exampleTk: "Ol meşhur arhitektor.", order: 3 },
    { wordEn: "modern", wordTk: "häzirki zaman / täze", partOfSpeech: "adjective", exampleEn: "Ashgabat has many modern buildings.", exampleTk: "Aşgabatda köp häzirki zaman bina bar.", order: 4 },
    { wordEn: "bridge", wordTk: "köpri", partOfSpeech: "noun", exampleEn: "The bridge was built last year.", exampleTk: "Köpri geçen ýyl guruldy.", order: 5 },
    { wordEn: "monument", wordTk: "ýadygärlik / abadanlyk", partOfSpeech: "noun", exampleEn: "The monument is very impressive.", exampleTk: "Ýadygärlik gaty täsirli.", order: 6 },
    { wordEn: "crowd", wordTk: "märeke / köp adam", partOfSpeech: "noun", exampleEn: "A large crowd gathered in the square.", exampleTk: "Meýdanda uly märeke ýygnandy.", order: 7 },
    { wordEn: "street", wordTk: "köçe / ýol", partOfSpeech: "noun", exampleEn: "The streets of Ashgabat are clean.", exampleTk: "Aşgabadyň köçeleri arassadyr.", order: 8 },
    { wordEn: "skyscraper", wordTk: "gök deşýän bina / uly bina", partOfSpeech: "noun", exampleEn: "Dubai has many skyscrapers.", exampleTk: "Dubaýda köp gök deşýän bina bar.", order: 9 },
    { wordEn: "district", wordTk: "etrap / raýon", partOfSpeech: "noun", exampleEn: "I live in the central district.", exampleTk: "Men merkezi etrapda ýaşaýaryn.", order: 10 },
  ]},
  { weekNumber: 51, titleEn: "Week 51: Jobs and Careers", titleTk: "51-nji Hepde: Hünärler we Karýera", words: [
    { wordEn: "qualify", wordTk: "hünär gazanmak / taýýar bolmak", partOfSpeech: "verb", exampleEn: "You need to qualify for this job.", exampleTk: "Bu iş üçin hünär gazanmaly.", order: 1 },
    { wordEn: "interview", wordTk: "söhbet / iş söhbeti", partOfSpeech: "noun", exampleEn: "I have a job interview tomorrow.", exampleTk: "Ertir iş söhbetim bar.", order: 2 },
    { wordEn: "experience", wordTk: "tejribe / iş tejribesi", partOfSpeech: "noun", exampleEn: "This job requires three years of experience.", exampleTk: "Bu iş üç ýyl tejribe talap edýär.", order: 3 },
    { wordEn: "promote", wordTk: "wezipäni ýokarlandyrmak", partOfSpeech: "verb", exampleEn: "She was promoted to manager.", exampleTk: "Ol müdirlige geçirildi.", order: 4 },
    { wordEn: "compete", wordTk: "bäsleşmek / ýaryşmak", partOfSpeech: "verb", exampleEn: "Many people compete for this job.", exampleTk: "Bu iş üçin köp adam bäsleşýär.", order: 5 },
    { wordEn: "application", wordTk: "arzа / üstünlik isleg", partOfSpeech: "noun", exampleEn: "Send your job application today.", exampleTk: "Iş arzaňy bu gün iber.", order: 6 },
    { wordEn: "employer", wordTk: "işgär alyjy / iş beriji", partOfSpeech: "noun", exampleEn: "The employer was impressed.", exampleTk: "Iş beriji täsir aldy.", order: 7 },
    { wordEn: "employee", wordTk: "işgär / zähmetçi", partOfSpeech: "noun", exampleEn: "She is a hardworking employee.", exampleTk: "Ol yhlaslы işgär.", order: 8 },
    { wordEn: "resign", wordTk: "işden çykmak / wezipeden aýrylmak", partOfSpeech: "verb", exampleEn: "He resigned from his position.", exampleTk: "Ol wezipesinden aýryldy.", order: 9 },
    { wordEn: "professional", wordTk: "hünärmen / professional", partOfSpeech: "adjective", exampleEn: "Always behave professionally.", exampleTk: "Hemişe hünärmen ýaly hereket et.", order: 10 },
  ]},
  { weekNumber: 52, titleEn: "Week 52: The Future", titleTk: "52-nji Hepde: Geljek", words: [
    { wordEn: "predict", wordTk: "çaklamak / öňünden aýtmak", partOfSpeech: "verb", exampleEn: "It is hard to predict the future.", exampleTk: "Geljegi çaklamak kyn.", order: 1 },
    { wordEn: "hope", wordTk: "umyt / ynam", partOfSpeech: "noun", exampleEn: "Never lose hope.", exampleTk: "Hiç wagt umydyňy ýitirme.", order: 2 },
    { wordEn: "possibility", wordTk: "mümkinçilik / ähtimallyk", partOfSpeech: "noun", exampleEn: "The possibilities are endless.", exampleTk: "Mümkinçilikler çäksizdir.", order: 3 },
    { wordEn: "expect", wordTk: "garaşmak / umyt etmek", partOfSpeech: "verb", exampleEn: "I expect great things from you.", exampleTk: "Sizden uly zatlar garaşýaryn.", order: 4 },
    { wordEn: "vision", wordTk: "görüş / maksat", partOfSpeech: "noun", exampleEn: "Have a clear vision for your future.", exampleTk: "Geljekligiňiz üçin anyk görüşiňiz bolsun.", order: 5 },
    { wordEn: "innovative", wordTk: "täzelikçi / döredijili", partOfSpeech: "adjective", exampleEn: "The future needs innovative thinkers.", exampleTk: "Geljek täzelikçi pikirleri talap edýär.", order: 6 },
    { wordEn: "sustainable", wordTk: "durnukly / uzak möhletli", partOfSpeech: "adjective", exampleEn: "Build a sustainable future.", exampleTk: "Durnukly geljek gur.", order: 7 },
    { wordEn: "generation", wordTk: "nesil / ýaş nesil", partOfSpeech: "noun", exampleEn: "Future generations depend on us.", exampleTk: "Geljek nesil bize bagly.", order: 8 },
    { wordEn: "challenge", wordTk: "kynçylyk / synag", partOfSpeech: "noun", exampleEn: "Future challenges require creativity.", exampleTk: "Geljek kynçylyklary döredijilik talap edýär.", order: 9 },
    { wordEn: "goal", wordTk: "maksat / wezipe", partOfSpeech: "noun", exampleEn: "Set goals for your future.", exampleTk: "Geljekligiňiz üçin maksat goýuň.", order: 10 },
  ]},
];
